/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.Media.FaceAnalysis.h>

HRESULT wmefa_face_detector_new(WMEFA_FaceDetector **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.FaceAnalysis.FaceDetector", NULL, (void **)out);
}

HRESULT wmefa_face_detector_detect_faces_async(WMEFA_FaceDetector *self, WGRIM_SoftwareBitmap* image, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_SoftwareBitmap* image, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, image, out);
}

HRESULT wmefa_face_detector_detect_faces_async_p_bitmap_bounds_p(WMEFA_FaceDetector *self, WGRIM_SoftwareBitmap* image, WGRIM_BitmapBounds searchArea, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_SoftwareBitmap* image, WGRIM_BitmapBounds searchArea, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, image, searchArea, out);
}

HRESULT wmefa_face_detector_get__min_detectable_face_size(WMEFA_FaceDetector *self, WGRIM_BitmapSize *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_BitmapSize *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmefa_face_detector_put__min_detectable_face_size(WMEFA_FaceDetector *self, WGRIM_BitmapSize value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_BitmapSize value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmefa_face_detector_get__max_detectable_face_size(WMEFA_FaceDetector *self, WGRIM_BitmapSize *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_BitmapSize *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wmefa_face_detector_put__max_detectable_face_size(WMEFA_FaceDetector *self, WGRIM_BitmapSize value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceDetector *self, WGRIM_BitmapSize value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wmefa_face_detector_create_async(WF_IAsyncOperation_WMEFA_FaceDetector** out)
{
    WMEFA_IFaceDetectorStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceDetector", &CWINRT_IID_WMEFA_IFaceDetectorStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceDetectorStatics *self, WF_IAsyncOperation_WMEFA_FaceDetector** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_detector_get_supported_bitmap_pixel_formats(WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out)
{
    WMEFA_IFaceDetectorStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceDetector", &CWINRT_IID_WMEFA_IFaceDetectorStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceDetectorStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_detector_is_bitmap_pixel_format_supported(WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out)
{
    WMEFA_IFaceDetectorStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceDetector", &CWINRT_IID_WMEFA_IFaceDetectorStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceDetectorStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[8];
        hr = fn(statics, bitmapPixelFormat, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_detector_get__is_supported(BOOL *value)
{
    WMEFA_IFaceDetectorStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceDetector", &CWINRT_IID_WMEFA_IFaceDetectorStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceDetectorStatics *self, BOOL *value);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[9];
        hr = fn(statics, value);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_tracker_new(WMEFA_FaceTracker **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.FaceAnalysis.FaceTracker", NULL, (void **)out);
}

HRESULT wmefa_face_tracker_process_next_frame_async(WMEFA_FaceTracker *self, WME_VideoFrame* videoFrame, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceTracker *self, WME_VideoFrame* videoFrame, WF_IAsyncOperation_WFOCO_IVector_WMEFA_DetectedFace** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, videoFrame, out);
}

HRESULT wmefa_face_tracker_get__min_detectable_face_size(WMEFA_FaceTracker *self, WGRIM_BitmapSize *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceTracker *self, WGRIM_BitmapSize *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmefa_face_tracker_put__min_detectable_face_size(WMEFA_FaceTracker *self, WGRIM_BitmapSize value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceTracker *self, WGRIM_BitmapSize value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmefa_face_tracker_get__max_detectable_face_size(WMEFA_FaceTracker *self, WGRIM_BitmapSize *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceTracker *self, WGRIM_BitmapSize *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmefa_face_tracker_put__max_detectable_face_size(WMEFA_FaceTracker *self, WGRIM_BitmapSize value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_FaceTracker *self, WGRIM_BitmapSize value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wmefa_face_tracker_create_async(WF_IAsyncOperation_WMEFA_FaceTracker** out)
{
    WMEFA_IFaceTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceTracker", &CWINRT_IID_WMEFA_IFaceTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceTrackerStatics *self, WF_IAsyncOperation_WMEFA_FaceTracker** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_tracker_get_supported_bitmap_pixel_formats(WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out)
{
    WMEFA_IFaceTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceTracker", &CWINRT_IID_WMEFA_IFaceTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceTrackerStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_tracker_is_bitmap_pixel_format_supported(WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out)
{
    WMEFA_IFaceTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceTracker", &CWINRT_IID_WMEFA_IFaceTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceTrackerStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[8];
        hr = fn(statics, bitmapPixelFormat, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_tracker_get__is_supported(BOOL *value)
{
    WMEFA_IFaceTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.FaceAnalysis.FaceTracker", &CWINRT_IID_WMEFA_IFaceTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEFA_IFaceTrackerStatics *self, BOOL *value);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[9];
        hr = fn(statics, value);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmefa_face_detector_statics_create_async(WMEFA_IFaceDetectorStatics *self, WF_IAsyncOperation_WMEFA_FaceDetector** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceDetectorStatics *self, WF_IAsyncOperation_WMEFA_FaceDetector** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wmefa_face_detector_statics_get_supported_bitmap_pixel_formats(WMEFA_IFaceDetectorStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceDetectorStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, out);
}

HRESULT wmefa_face_detector_statics_is_bitmap_pixel_format_supported(WMEFA_IFaceDetectorStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceDetectorStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, bitmapPixelFormat, out);
}

HRESULT wmefa_face_detector_statics_get__is_supported(WMEFA_IFaceDetectorStatics *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceDetectorStatics *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmefa_face_tracker_statics_create_async(WMEFA_IFaceTrackerStatics *self, WF_IAsyncOperation_WMEFA_FaceTracker** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceTrackerStatics *self, WF_IAsyncOperation_WMEFA_FaceTracker** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wmefa_face_tracker_statics_get_supported_bitmap_pixel_formats(WMEFA_IFaceTrackerStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceTrackerStatics *self, WFOCO_IVectorView_WGRIM_BitmapPixelFormat** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, out);
}

HRESULT wmefa_face_tracker_statics_is_bitmap_pixel_format_supported(WMEFA_IFaceTrackerStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceTrackerStatics *self, WGRIM_BitmapPixelFormat bitmapPixelFormat, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, bitmapPixelFormat, out);
}

HRESULT wmefa_face_tracker_statics_get__is_supported(WMEFA_IFaceTrackerStatics *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_IFaceTrackerStatics *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmefa_detected_face_new(WMEFA_DetectedFace **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.FaceAnalysis.DetectedFace", NULL, (void **)out);
}

HRESULT wmefa_detected_face_get__face_box(WMEFA_DetectedFace *self, WGRIM_BitmapBounds *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEFA_DetectedFace *self, WGRIM_BitmapBounds *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

