/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.ApplicationModel.Wallet.h>

HRESULT wapwa_wallet_barcode_factory_create_wallet_barcode(WAPWA_IWalletBarcodeFactory *self, WAPWA_WalletBarcodeSymbology symbology, cwinrt_hstring value, WAPWA_WalletBarcode** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletBarcodeFactory *self, WAPWA_WalletBarcodeSymbology symbology, cwinrt_hstring value, WAPWA_WalletBarcode** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, symbology, value, out);
}

HRESULT wapwa_wallet_barcode_factory_create_custom_wallet_barcode(WAPWA_IWalletBarcodeFactory *self, WSTST_IRandomAccessStreamReference* streamToBarcodeImage, WAPWA_WalletBarcode** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletBarcodeFactory *self, WSTST_IRandomAccessStreamReference* streamToBarcodeImage, WAPWA_WalletBarcode** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, streamToBarcodeImage, out);
}

HRESULT wapwa_wallet_item_custom_property_factory_create_wallet_item_custom_property(WAPWA_IWalletItemCustomPropertyFactory *self, cwinrt_hstring name, cwinrt_hstring value, WAPWA_WalletItemCustomProperty** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletItemCustomPropertyFactory *self, cwinrt_hstring name, cwinrt_hstring value, WAPWA_WalletItemCustomProperty** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, name, value, out);
}

HRESULT wapwa_wallet_item_factory_create_wallet_item(WAPWA_IWalletItemFactory *self, WAPWA_WalletItemKind kind, cwinrt_hstring displayName, WAPWA_WalletItem** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletItemFactory *self, WAPWA_WalletItemKind kind, cwinrt_hstring displayName, WAPWA_WalletItem** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, kind, displayName, out);
}

HRESULT wapwa_wallet_manager_statics_request_store_async(WAPWA_IWalletManagerStatics *self, WF_IAsyncOperation_WAPWA_WalletItemStore** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletManagerStatics *self, WF_IAsyncOperation_WAPWA_WalletItemStore** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wapwa_wallet_verb_factory_create_wallet_verb(WAPWA_IWalletVerbFactory *self, cwinrt_hstring name, WAPWA_WalletVerb** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_IWalletVerbFactory *self, cwinrt_hstring name, WAPWA_WalletVerb** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, name, out);
}

HRESULT wapwa_wallet_transaction_new(WAPWA_WalletTransaction **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletTransaction", NULL, (void **)out);
}

HRESULT wapwa_wallet_transaction_get__description(WAPWA_WalletTransaction *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__description(WAPWA_WalletTransaction *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_get__display_amount(WAPWA_WalletTransaction *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__display_amount(WAPWA_WalletTransaction *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_get__ignore_time_of_day(WAPWA_WalletTransaction *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__ignore_time_of_day(WAPWA_WalletTransaction *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_get__display_location(WAPWA_WalletTransaction *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__display_location(WAPWA_WalletTransaction *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_get__transaction_date(WAPWA_WalletTransaction *self, WF_DateTime** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, WF_DateTime** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__transaction_date(WAPWA_WalletTransaction *self, WF_DateTime* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, WF_DateTime* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_get__is_launchable(WAPWA_WalletTransaction *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wapwa_wallet_transaction_put__is_launchable(WAPWA_WalletTransaction *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletTransaction *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, value);
}

HRESULT wapwa_wallet_relevant_location_new(WAPWA_WalletRelevantLocation **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletRelevantLocation", NULL, (void **)out);
}

HRESULT wapwa_wallet_relevant_location_get__position(WAPWA_WalletRelevantLocation *self, WDEGE_BasicGeoposition *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletRelevantLocation *self, WDEGE_BasicGeoposition *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_relevant_location_put__position(WAPWA_WalletRelevantLocation *self, WDEGE_BasicGeoposition value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletRelevantLocation *self, WDEGE_BasicGeoposition value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_relevant_location_get__display_message(WAPWA_WalletRelevantLocation *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletRelevantLocation *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wapwa_wallet_relevant_location_put__display_message(WAPWA_WalletRelevantLocation *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletRelevantLocation *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wapwa_wallet_verb_new(WAPWA_WalletVerb **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletVerb", NULL, (void **)out);
}

HRESULT wapwa_wallet_verb_get__name(WAPWA_WalletVerb *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletVerb *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_verb_put__name(WAPWA_WalletVerb *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletVerb *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_manager_new(WAPWA_WalletManager **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletManager", NULL, (void **)out);
}

HRESULT wapwa_wallet_manager_request_store_async(WF_IAsyncOperation_WAPWA_WalletItemStore** out)
{
    WAPWA_IWalletManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Wallet.WalletManager", &CWINRT_IID_WAPWA_IWalletManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPWA_IWalletManagerStatics *self, WF_IAsyncOperation_WAPWA_WalletItemStore** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapwa_wallet_item_store_new(WAPWA_WalletItemStore **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletItemStore", NULL, (void **)out);
}

HRESULT wapwa_wallet_item_store_add_async(WAPWA_WalletItemStore *self, cwinrt_hstring id, WAPWA_WalletItem* item, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, cwinrt_hstring id, WAPWA_WalletItem* item, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, id, item, out);
}

HRESULT wapwa_wallet_item_store_clear_async(WAPWA_WalletItemStore *self, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, out);
}

HRESULT wapwa_wallet_item_store_get_wallet_item_async(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncOperation_WAPWA_WalletItem** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncOperation_WAPWA_WalletItem** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, id, out);
}

HRESULT wapwa_wallet_item_store_get_items_async(WAPWA_WalletItemStore *self, WF_IAsyncOperation_WFOCO_IVectorView_WAPWA_WalletItem** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WF_IAsyncOperation_WFOCO_IVectorView_WAPWA_WalletItem** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, out);
}

HRESULT wapwa_wallet_item_store_get_items_async_wallet_item_kind_p(WAPWA_WalletItemStore *self, WAPWA_WalletItemKind kind, WF_IAsyncOperation_WFOCO_IVectorView_WAPWA_WalletItem** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WAPWA_WalletItemKind kind, WF_IAsyncOperation_WFOCO_IVectorView_WAPWA_WalletItem** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, kind, out);
}

HRESULT wapwa_wallet_item_store_import_item_async(WAPWA_WalletItemStore *self, WSTST_IRandomAccessStreamReference* stream, WF_IAsyncOperation_WAPWA_WalletItem** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WSTST_IRandomAccessStreamReference* stream, WF_IAsyncOperation_WAPWA_WalletItem** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, stream, out);
}

HRESULT wapwa_wallet_item_store_delete_async(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, id, out);
}

HRESULT wapwa_wallet_item_store_show_async(WAPWA_WalletItemStore *self, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, out);
}

HRESULT wapwa_wallet_item_store_show_async_str_p(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, cwinrt_hstring id, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, id, out);
}

HRESULT wapwa_wallet_item_store_update_async(WAPWA_WalletItemStore *self, WAPWA_WalletItem* item, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemStore *self, WAPWA_WalletItem* item, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, item, out);
}

HRESULT wapwa_wallet_barcode_new(WAPWA_WalletBarcode **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletBarcode", NULL, (void **)out);
}

HRESULT wapwa_wallet_barcode_get__symbology(WAPWA_WalletBarcode *self, WAPWA_WalletBarcodeSymbology *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletBarcode *self, WAPWA_WalletBarcodeSymbology *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_barcode_get__value(WAPWA_WalletBarcode *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletBarcode *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_barcode_get_image_async(WAPWA_WalletBarcode *self, WF_IAsyncOperation_WSTST_IRandomAccessStreamReference** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletBarcode *self, WF_IAsyncOperation_WSTST_IRandomAccessStreamReference** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, out);
}

HRESULT wapwa_wallet_item_new(WAPWA_WalletItem **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletItem", NULL, (void **)out);
}

HRESULT wapwa_wallet_item_get__display_name(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__display_name(WAPWA_WalletItem *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__id(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__is_acknowledged(WAPWA_WalletItem *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__is_acknowledged(WAPWA_WalletItem *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__issuer_display_name(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__issuer_display_name(WAPWA_WalletItem *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__last_updated(WAPWA_WalletItem *self, WF_DateTime** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__last_updated(WAPWA_WalletItem *self, WF_DateTime* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__kind(WAPWA_WalletItem *self, WAPWA_WalletItemKind *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WAPWA_WalletItemKind *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__barcode(WAPWA_WalletItem *self, WAPWA_WalletBarcode** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WAPWA_WalletBarcode** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__barcode(WAPWA_WalletItem *self, WAPWA_WalletBarcode* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WAPWA_WalletBarcode* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__expiration_date(WAPWA_WalletItem *self, WF_DateTime** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__expiration_date(WAPWA_WalletItem *self, WF_DateTime* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__logo159x159(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[20];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__logo159x159(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[21];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__logo336x336(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[22];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__logo336x336(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[23];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__logo99x99(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[24];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__logo99x99(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[25];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__display_message(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[26];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__display_message(WAPWA_WalletItem *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[27];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__is_display_message_launchable(WAPWA_WalletItem *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[28];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__is_display_message_launchable(WAPWA_WalletItem *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[29];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__logo_text(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[30];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__logo_text(WAPWA_WalletItem *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[31];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__header_color(WAPWA_WalletItem *self, WUI_Color *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[32];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__header_color(WAPWA_WalletItem *self, WUI_Color value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[33];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__body_color(WAPWA_WalletItem *self, WUI_Color *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[34];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__body_color(WAPWA_WalletItem *self, WUI_Color value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[35];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__header_font_color(WAPWA_WalletItem *self, WUI_Color *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[36];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__header_font_color(WAPWA_WalletItem *self, WUI_Color value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[37];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__body_font_color(WAPWA_WalletItem *self, WUI_Color *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[38];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__body_font_color(WAPWA_WalletItem *self, WUI_Color value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WUI_Color value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[39];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__header_background_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[40];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__header_background_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[41];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__body_background_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[42];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__body_background_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[43];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__logo_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[44];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__logo_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[45];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__promotional_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[46];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__promotional_image(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WSTST_IRandomAccessStreamReference* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[47];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__relevant_date(WAPWA_WalletItem *self, WF_DateTime** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[48];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__relevant_date(WAPWA_WalletItem *self, WF_DateTime* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WF_DateTime* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[49];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__relevant_date_display_message(WAPWA_WalletItem *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[50];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__relevant_date_display_message(WAPWA_WalletItem *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[51];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__transaction_history(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletTransaction** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletTransaction** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[52];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__relevant_locations(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletRelevantLocation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletRelevantLocation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[53];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__is_more_transaction_history_launchable(WAPWA_WalletItem *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[54];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_put__is_more_transaction_history_launchable(WAPWA_WalletItem *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[55];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__display_properties(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletItemCustomProperty** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletItemCustomProperty** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[56];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_get__verbs(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletVerb** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItem *self, WFOCO_IMap_HSTRING_WAPWA_WalletVerb** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[57];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_new(WAPWA_WalletItemCustomProperty **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Wallet.WalletItemCustomProperty", NULL, (void **)out);
}

HRESULT wapwa_wallet_item_custom_property_get__name(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_put__name(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_get__value(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_put__value(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, cwinrt_hstring value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_get__auto_detect_links(WAPWA_WalletItemCustomProperty *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_put__auto_detect_links(WAPWA_WalletItemCustomProperty *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_get__detail_view_position(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletDetailViewPosition *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletDetailViewPosition *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_put__detail_view_position(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletDetailViewPosition value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletDetailViewPosition value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_get__summary_view_position(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletSummaryViewPosition *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletSummaryViewPosition *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wapwa_wallet_item_custom_property_put__summary_view_position(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletSummaryViewPosition value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPWA_WalletItemCustomProperty *self, WAPWA_WalletSummaryViewPosition value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

