/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.ApplicationModel.CommunicationBlocking.h>

HRESULT wapco_communication_blocking_app_manager_statics_2_request_set_as_active_blocking_app_async(WAPCO_ICommunicationBlockingAppManagerStatics_2 *self, WF_IAsyncOperation_Bool** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics_2 *self, WF_IAsyncOperation_Bool** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wapco_communication_blocking_access_manager_statics_get__is_blocking_active(WAPCO_ICommunicationBlockingAccessManagerStatics *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapco_communication_blocking_access_manager_statics_is_blocked_number_async(WAPCO_ICommunicationBlockingAccessManagerStatics *self, cwinrt_hstring number, WF_IAsyncOperation_Bool** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, cwinrt_hstring number, WF_IAsyncOperation_Bool** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, number, out);
}

HRESULT wapco_communication_blocking_access_manager_statics_show_block_numbers_u_i(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, phoneNumbers, out);
}

HRESULT wapco_communication_blocking_access_manager_statics_show_unblock_numbers_u_i(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, phoneNumbers, out);
}

HRESULT wapco_communication_blocking_access_manager_statics_show_blocked_calls_u_i(WAPCO_ICommunicationBlockingAccessManagerStatics *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self);
}

HRESULT wapco_communication_blocking_access_manager_statics_show_blocked_messages_u_i(WAPCO_ICommunicationBlockingAccessManagerStatics *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self);
}

HRESULT wapco_communication_blocking_app_manager_new(WAPCO_CommunicationBlockingAppManager **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAppManager", NULL, (void **)out);
}

HRESULT wapco_communication_blocking_app_manager_request_set_as_active_blocking_app_async(WF_IAsyncOperation_Bool** out)
{
    WAPCO_ICommunicationBlockingAppManagerStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAppManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAppManagerStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics_2 *self, WF_IAsyncOperation_Bool** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_app_manager_get__is_current_app_active_blocking_app(BOOL *value)
{
    WAPCO_ICommunicationBlockingAppManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAppManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAppManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics *self, BOOL *value);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, value);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_app_manager_show_communication_blocking_settings_u_i(void)
{
    WAPCO_ICommunicationBlockingAppManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAppManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAppManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics *self);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_new(WAPCO_CommunicationBlockingAccessManager **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", NULL, (void **)out);
}

HRESULT wapco_communication_blocking_access_manager_get__is_blocking_active(BOOL *value)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, BOOL *value);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, value);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_is_blocked_number_async(cwinrt_hstring number, WF_IAsyncOperation_Bool** out)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, cwinrt_hstring number, WF_IAsyncOperation_Bool** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, number, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_show_block_numbers_u_i(WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[8];
        hr = fn(statics, phoneNumbers, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_show_unblock_numbers_u_i(WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self, WFOCO_IIterable_HSTRING* phoneNumbers, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[9];
        hr = fn(statics, phoneNumbers, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_show_blocked_calls_u_i(void)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[10];
        hr = fn(statics);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_access_manager_show_blocked_messages_u_i(void)
{
    WAPCO_ICommunicationBlockingAccessManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingAccessManager", &CWINRT_IID_WAPCO_ICommunicationBlockingAccessManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPCO_ICommunicationBlockingAccessManagerStatics *self);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[11];
        hr = fn(statics);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapco_communication_blocking_app_manager_statics_get__is_current_app_active_blocking_app(WAPCO_ICommunicationBlockingAppManagerStatics *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapco_communication_blocking_app_manager_statics_show_communication_blocking_settings_u_i(WAPCO_ICommunicationBlockingAppManagerStatics *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPCO_ICommunicationBlockingAppManagerStatics *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self);
}

