/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.Devices.Radios.h>

HRESULT wdera_radio_statics_get_radios_async(WDERA_IRadioStatics *self, WF_IAsyncOperation_WFOCO_IVectorView_WDERA_Radio** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_IRadioStatics *self, WF_IAsyncOperation_WFOCO_IVectorView_WDERA_Radio** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wdera_radio_statics_get_device_selector(WDERA_IRadioStatics *self, cwinrt_hstring *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_IRadioStatics *self, cwinrt_hstring *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, out);
}

HRESULT wdera_radio_statics_from_id_async(WDERA_IRadioStatics *self, cwinrt_hstring deviceId, WF_IAsyncOperation_WDERA_Radio** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_IRadioStatics *self, cwinrt_hstring deviceId, WF_IAsyncOperation_WDERA_Radio** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, deviceId, out);
}

HRESULT wdera_radio_statics_request_access_async(WDERA_IRadioStatics *self, WF_IAsyncOperation_WDERA_RadioAccessStatus** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_IRadioStatics *self, WF_IAsyncOperation_WDERA_RadioAccessStatus** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, out);
}

HRESULT wdera_radio_new(WDERA_Radio **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Devices.Radios.Radio", NULL, (void **)out);
}

HRESULT wdera_radio_set_state_async(WDERA_Radio *self, WDERA_RadioState value, WF_IAsyncOperation_WDERA_RadioAccessStatus** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_Radio *self, WDERA_RadioState value, WF_IAsyncOperation_WDERA_RadioAccessStatus** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value, out);
}

HRESULT wdera_radio_get__state(WDERA_Radio *self, WDERA_RadioState *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_Radio *self, WDERA_RadioState *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wdera_radio_get__name(WDERA_Radio *self, cwinrt_hstring *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_Radio *self, cwinrt_hstring *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wdera_radio_get__kind(WDERA_Radio *self, WDERA_RadioKind *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WDERA_Radio *self, WDERA_RadioKind *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wdera_radio_get_radios_async(WF_IAsyncOperation_WFOCO_IVectorView_WDERA_Radio** out)
{
    WDERA_IRadioStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Devices.Radios.Radio", &CWINRT_IID_WDERA_IRadioStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WDERA_IRadioStatics *self, WF_IAsyncOperation_WFOCO_IVectorView_WDERA_Radio** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wdera_radio_get_device_selector(cwinrt_hstring *out)
{
    WDERA_IRadioStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Devices.Radios.Radio", &CWINRT_IID_WDERA_IRadioStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WDERA_IRadioStatics *self, cwinrt_hstring *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wdera_radio_from_id_async(cwinrt_hstring deviceId, WF_IAsyncOperation_WDERA_Radio** out)
{
    WDERA_IRadioStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Devices.Radios.Radio", &CWINRT_IID_WDERA_IRadioStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WDERA_IRadioStatics *self, cwinrt_hstring deviceId, WF_IAsyncOperation_WDERA_Radio** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[8];
        hr = fn(statics, deviceId, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wdera_radio_request_access_async(WF_IAsyncOperation_WDERA_RadioAccessStatus** out)
{
    WDERA_IRadioStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Devices.Radios.Radio", &CWINRT_IID_WDERA_IRadioStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WDERA_IRadioStatics *self, WF_IAsyncOperation_WDERA_RadioAccessStatus** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[9];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

cwinrt_token wdera_radio_on_state_changed(WDERA_Radio *self, cwinrt_event_fn fn, void *ctx)
{
    IUnknown *handler = NULL;
    cwinrt_event_handle eh = { 0 };
    cwinrt_token tok = { 0 };
    HRESULT hr = cwinrt_event_handler_create(fn, ctx, &handler);
    if (FAILED(hr)) return tok;
    hr = cwinrt_event_subscribe((IUnknown *)self, 7u, 8u, handler, &eh);
    handler->lpVtbl->Release(handler);
    if (FAILED(hr)) return tok;
    return eh.token;
}

void wdera_radio_off_state_changed(WDERA_Radio *self, cwinrt_token token)
{
    cwinrt_event_handle eh = { (IUnknown *)self, 8u, token };
    cwinrt_event_unsubscribe(&eh);
}

