/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.UI.Xaml.Interop.h>

HRESULT wuixain_bindable_vector_changed_event_handler_invoke(WUIXAIN_BindableVectorChangedEventHandler *self, WUIXAIN_IBindableObservableVector* vector, IInspectable* e)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_BindableVectorChangedEventHandler *self, WUIXAIN_IBindableObservableVector* vector, IInspectable* e);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[3];
    return fn(self, vector, e);
}

HRESULT wuixain_bindable_iterator_get__current(WUIXAIN_IBindableIterator *self, IInspectable** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableIterator *self, IInspectable** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuixain_bindable_iterator_get__has_current(WUIXAIN_IBindableIterator *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableIterator *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuixain_bindable_iterator_move_next(WUIXAIN_IBindableIterator *self, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableIterator *self, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, out);
}

HRESULT wuixain_bindable_vector_view_get_at(WUIXAIN_IBindableVectorView *self, uint32_t index, IInspectable** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVectorView *self, uint32_t index, IInspectable** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, index, out);
}

HRESULT wuixain_bindable_vector_view_get__size(WUIXAIN_IBindableVectorView *self, uint32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVectorView *self, uint32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuixain_bindable_vector_view_index_of(WUIXAIN_IBindableVectorView *self, IInspectable* value, uint32_t index, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVectorView *self, IInspectable* value, uint32_t index, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value, index, out);
}

HRESULT wuixain_notify_collection_changed_event_args_factory_create_instance_with_all_parameters(WUIXAIN_INotifyCollectionChangedEventArgsFactory *self, WUIXAIN_NotifyCollectionChangedAction action, WUIXAIN_IBindableVector* newItems, WUIXAIN_IBindableVector* oldItems, int32_t newIndex, int32_t oldIndex, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAIN_NotifyCollectionChangedEventArgs** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_INotifyCollectionChangedEventArgsFactory *self, WUIXAIN_NotifyCollectionChangedAction action, WUIXAIN_IBindableVector* newItems, WUIXAIN_IBindableVector* oldItems, int32_t newIndex, int32_t oldIndex, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAIN_NotifyCollectionChangedEventArgs** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, action, newItems, oldItems, newIndex, oldIndex, baseInterface, innerInterface, out);
}

HRESULT wuixain_notify_collection_changed_event_args_get__action(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_NotifyCollectionChangedAction *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_NotifyCollectionChangedAction *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuixain_notify_collection_changed_event_args_get__new_items(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_IBindableVector** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_IBindableVector** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuixain_notify_collection_changed_event_args_get__old_items(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_IBindableVector** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventArgs *self, WUIXAIN_IBindableVector** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuixain_notify_collection_changed_event_args_get__new_starting_index(WUIXAIN_NotifyCollectionChangedEventArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuixain_notify_collection_changed_event_args_get__old_starting_index(WUIXAIN_NotifyCollectionChangedEventArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuixain_notify_collection_changed_event_handler_invoke(WUIXAIN_NotifyCollectionChangedEventHandler *self, IInspectable* sender, WUIXAIN_NotifyCollectionChangedEventArgs* e)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_NotifyCollectionChangedEventHandler *self, IInspectable* sender, WUIXAIN_NotifyCollectionChangedEventArgs* e);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[3];
    return fn(self, sender, e);
}

HRESULT wuixain_bindable_vector_get_at(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, index, out);
}

HRESULT wuixain_bindable_vector_get__size(WUIXAIN_IBindableVector *self, uint32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, uint32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuixain_bindable_vector_get_view(WUIXAIN_IBindableVector *self, WUIXAIN_IBindableVectorView** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, WUIXAIN_IBindableVectorView** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, out);
}

HRESULT wuixain_bindable_vector_index_of(WUIXAIN_IBindableVector *self, IInspectable* value, uint32_t index, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, IInspectable* value, uint32_t index, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value, index, out);
}

HRESULT wuixain_bindable_vector_set_at(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, index, value);
}

HRESULT wuixain_bindable_vector_insert_at(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, uint32_t index, IInspectable* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, index, value);
}

HRESULT wuixain_bindable_vector_remove_at(WUIXAIN_IBindableVector *self, uint32_t index)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, uint32_t index);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, index);
}

HRESULT wuixain_bindable_vector_append(WUIXAIN_IBindableVector *self, IInspectable* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self, IInspectable* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wuixain_bindable_vector_remove_at_end(WUIXAIN_IBindableVector *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self);
}

HRESULT wuixain_bindable_vector_clear(WUIXAIN_IBindableVector *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableVector *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self);
}

HRESULT wuixain_bindable_iterable_first(WUIXAIN_IBindableIterable *self, WUIXAIN_IBindableIterator** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUIXAIN_IBindableIterable *self, WUIXAIN_IBindableIterator** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

