/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.ApplicationModel.Store.LicenseManagement.h>

HRESULT wapstli_license_manager_statics_2_refresh_licenses_async(WAPSTLI_ILicenseManagerStatics_2 *self, WAPSTLI_LicenseRefreshOption refreshOption, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_ILicenseManagerStatics_2 *self, WAPSTLI_LicenseRefreshOption refreshOption, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, refreshOption, out);
}

HRESULT wapstli_license_manager_new(WAPSTLI_LicenseManager **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseManager", NULL, (void **)out);
}

HRESULT wapstli_license_manager_refresh_licenses_async(WAPSTLI_LicenseRefreshOption refreshOption, WF_IAsyncAction** out)
{
    WAPSTLI_ILicenseManagerStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseManager", &CWINRT_IID_WAPSTLI_ILicenseManagerStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPSTLI_ILicenseManagerStatics_2 *self, WAPSTLI_LicenseRefreshOption refreshOption, WF_IAsyncAction** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, refreshOption, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapstli_license_manager_add_license_async(WSTST_IBuffer* license, WF_IAsyncAction** out)
{
    WAPSTLI_ILicenseManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseManager", &CWINRT_IID_WAPSTLI_ILicenseManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPSTLI_ILicenseManagerStatics *self, WSTST_IBuffer* license, WF_IAsyncAction** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, license, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapstli_license_manager_get_satisfaction_infos_async(WFOCO_IIterable_HSTRING* contentIds, WFOCO_IIterable_HSTRING* keyIds, WF_IAsyncOperation_WAPSTLI_LicenseSatisfactionResult** out)
{
    WAPSTLI_ILicenseManagerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseManager", &CWINRT_IID_WAPSTLI_ILicenseManagerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPSTLI_ILicenseManagerStatics *self, WFOCO_IIterable_HSTRING* contentIds, WFOCO_IIterable_HSTRING* keyIds, WF_IAsyncOperation_WAPSTLI_LicenseSatisfactionResult** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, contentIds, keyIds, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapstli_license_satisfaction_info_new(WAPSTLI_LicenseSatisfactionInfo **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseSatisfactionInfo", NULL, (void **)out);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_device(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_open_license(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_trial(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_pass(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_install_media(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__satisfied_by_signed_in_user(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_info_get__is_satisfied(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionInfo *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_result_new(WAPSTLI_LicenseSatisfactionResult **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Store.LicenseManagement.LicenseSatisfactionResult", NULL, (void **)out);
}

HRESULT wapstli_license_satisfaction_result_get__license_satisfaction_infos(WAPSTLI_LicenseSatisfactionResult *self, WFOCO_IMapView_HSTRING_WAPSTLI_LicenseSatisfactionInfo** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionResult *self, WFOCO_IMapView_HSTRING_WAPSTLI_LicenseSatisfactionInfo** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wapstli_license_satisfaction_result_get__extended_error(WAPSTLI_LicenseSatisfactionResult *self, HRESULT *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_LicenseSatisfactionResult *self, HRESULT *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wapstli_license_manager_statics_add_license_async(WAPSTLI_ILicenseManagerStatics *self, WSTST_IBuffer* license, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_ILicenseManagerStatics *self, WSTST_IBuffer* license, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, license, out);
}

HRESULT wapstli_license_manager_statics_get_satisfaction_infos_async(WAPSTLI_ILicenseManagerStatics *self, WFOCO_IIterable_HSTRING* contentIds, WFOCO_IIterable_HSTRING* keyIds, WF_IAsyncOperation_WAPSTLI_LicenseSatisfactionResult** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPSTLI_ILicenseManagerStatics *self, WFOCO_IIterable_HSTRING* contentIds, WFOCO_IIterable_HSTRING* keyIds, WF_IAsyncOperation_WAPSTLI_LicenseSatisfactionResult** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, contentIds, keyIds, out);
}

