/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.ApplicationModel.Preview.Holographic.h>

HRESULT wapprho_holographic_keyboard_placement_override_preview_new(WAPPRHO_HolographicKeyboardPlacementOverridePreview **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Preview.Holographic.HolographicKeyboardPlacementOverridePreview", NULL, (void **)out);
}

HRESULT wapprho_holographic_keyboard_placement_override_preview_set_placement_override(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self, WPESP_SpatialCoordinateSystem* coordinateSystem, WFN_Vector_3 topCenterPosition, WFN_Vector_3 normal)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self, WPESP_SpatialCoordinateSystem* coordinateSystem, WFN_Vector_3 topCenterPosition, WFN_Vector_3 normal);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, coordinateSystem, topCenterPosition, normal);
}

HRESULT wapprho_holographic_keyboard_placement_override_preview_set_placement_override_p_3_3_2(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self, WPESP_SpatialCoordinateSystem* coordinateSystem, WFN_Vector_3 topCenterPosition, WFN_Vector_3 normal, WFN_Vector_2 maxSize)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self, WPESP_SpatialCoordinateSystem* coordinateSystem, WFN_Vector_3 topCenterPosition, WFN_Vector_3 normal, WFN_Vector_2 maxSize);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, coordinateSystem, topCenterPosition, normal, maxSize);
}

HRESULT wapprho_holographic_keyboard_placement_override_preview_reset_placement_override(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_HolographicKeyboardPlacementOverridePreview *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self);
}

HRESULT wapprho_holographic_keyboard_placement_override_preview_get_for_current_view(WAPPRHO_HolographicKeyboardPlacementOverridePreview** out)
{
    WAPPRHO_IHolographicKeyboardPlacementOverridePreviewStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Preview.Holographic.HolographicKeyboardPlacementOverridePreview", &CWINRT_IID_WAPPRHO_IHolographicKeyboardPlacementOverridePreviewStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPPRHO_IHolographicKeyboardPlacementOverridePreviewStatics *self, WAPPRHO_HolographicKeyboardPlacementOverridePreview** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapprho_holographic_application_preview_statics_is_current_view_presented_on_holographic_display(WAPPRHO_IHolographicApplicationPreviewStatics *self, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_IHolographicApplicationPreviewStatics *self, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wapprho_holographic_application_preview_statics_is_holographic_activation(WAPPRHO_IHolographicApplicationPreviewStatics *self, WAPAC_IActivatedEventArgs* activatedEventArgs, BOOL *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_IHolographicApplicationPreviewStatics *self, WAPAC_IActivatedEventArgs* activatedEventArgs, BOOL *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, activatedEventArgs, out);
}

HRESULT wapprho_holographic_keyboard_placement_override_preview_statics_get_for_current_view(WAPPRHO_IHolographicKeyboardPlacementOverridePreviewStatics *self, WAPPRHO_HolographicKeyboardPlacementOverridePreview** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WAPPRHO_IHolographicKeyboardPlacementOverridePreviewStatics *self, WAPPRHO_HolographicKeyboardPlacementOverridePreview** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wapprho_holographic_application_preview_new(WAPPRHO_HolographicApplicationPreview **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.ApplicationModel.Preview.Holographic.HolographicApplicationPreview", NULL, (void **)out);
}

HRESULT wapprho_holographic_application_preview_is_current_view_presented_on_holographic_display(BOOL *out)
{
    WAPPRHO_IHolographicApplicationPreviewStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Preview.Holographic.HolographicApplicationPreview", &CWINRT_IID_WAPPRHO_IHolographicApplicationPreviewStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPPRHO_IHolographicApplicationPreviewStatics *self, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wapprho_holographic_application_preview_is_holographic_activation(WAPAC_IActivatedEventArgs* activatedEventArgs, BOOL *out)
{
    WAPPRHO_IHolographicApplicationPreviewStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.ApplicationModel.Preview.Holographic.HolographicApplicationPreview", &CWINRT_IID_WAPPRHO_IHolographicApplicationPreviewStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WAPPRHO_IHolographicApplicationPreviewStatics *self, WAPAC_IActivatedEventArgs* activatedEventArgs, BOOL *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, activatedEventArgs, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

