/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.Media.Editing.h>

HRESULT wmeed_media_clip_statics_create_from_color(WMEED_IMediaClipStatics *self, WUI_Color color, WF_TimeSpan originalDuration, WMEED_MediaClip** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaClipStatics *self, WUI_Color color, WF_TimeSpan originalDuration, WMEED_MediaClip** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, color, originalDuration, out);
}

HRESULT wmeed_media_clip_statics_create_from_file_async(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_MediaClip** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_MediaClip** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, file, out);
}

HRESULT wmeed_media_clip_statics_create_from_image_file_async(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_TimeSpan originalDuration, WF_IAsyncOperation_WMEED_MediaClip** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_TimeSpan originalDuration, WF_IAsyncOperation_WMEED_MediaClip** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, file, originalDuration, out);
}

HRESULT wmeed_media_clip_statics_2_create_from_surface(WMEED_IMediaClipStatics_2 *self, WGRDIDI_IDirect3DSurface* surface, WF_TimeSpan originalDuration, WMEED_MediaClip** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaClipStatics_2 *self, WGRDIDI_IDirect3DSurface* surface, WF_TimeSpan originalDuration, WMEED_MediaClip** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, surface, originalDuration, out);
}

HRESULT wmeed_background_audio_track_statics_create_from_embedded_audio_track(WMEED_IBackgroundAudioTrackStatics *self, WMEED_EmbeddedAudioTrack* embeddedAudioTrack, WMEED_BackgroundAudioTrack** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IBackgroundAudioTrackStatics *self, WMEED_EmbeddedAudioTrack* embeddedAudioTrack, WMEED_BackgroundAudioTrack** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, embeddedAudioTrack, out);
}

HRESULT wmeed_background_audio_track_statics_create_from_file_async(WMEED_IBackgroundAudioTrackStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_BackgroundAudioTrack** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IBackgroundAudioTrackStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_BackgroundAudioTrack** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, file, out);
}

HRESULT wmeed_embedded_audio_track_new(WMEED_EmbeddedAudioTrack **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.EmbeddedAudioTrack", NULL, (void **)out);
}

HRESULT wmeed_embedded_audio_track_get_audio_encoding_properties(WMEED_EmbeddedAudioTrack *self, WMEME_AudioEncodingProperties** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_EmbeddedAudioTrack *self, WMEME_AudioEncodingProperties** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wmeed_background_audio_track_new(WMEED_BackgroundAudioTrack **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.BackgroundAudioTrack", NULL, (void **)out);
}

HRESULT wmeed_background_audio_track_get__trim_time_from_start(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_put__trim_time_from_start(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__trim_time_from_end(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_put__trim_time_from_end(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__original_duration(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__trimmed_duration(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__user_data(WMEED_BackgroundAudioTrack *self, WFOCO_IMap_HSTRING_HSTRING** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WFOCO_IMap_HSTRING_HSTRING** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_put__delay(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__delay(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_put__volume(WMEED_BackgroundAudioTrack *self, double value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, double value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_get__volume(WMEED_BackgroundAudioTrack *self, double *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, double *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_clone(WMEED_BackgroundAudioTrack *self, WMEED_BackgroundAudioTrack** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WMEED_BackgroundAudioTrack** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, out);
}

HRESULT wmeed_background_audio_track_get_audio_encoding_properties(WMEED_BackgroundAudioTrack *self, WMEME_AudioEncodingProperties** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WMEME_AudioEncodingProperties** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, out);
}

HRESULT wmeed_background_audio_track_get__audio_effect_definitions(WMEED_BackgroundAudioTrack *self, WFOCO_IVector_WMEEF_IAudioEffectDefinition** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_BackgroundAudioTrack *self, WFOCO_IVector_WMEEF_IAudioEffectDefinition** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, value);
}

HRESULT wmeed_background_audio_track_create_from_embedded_audio_track(WMEED_EmbeddedAudioTrack* embeddedAudioTrack, WMEED_BackgroundAudioTrack** out)
{
    WMEED_IBackgroundAudioTrackStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.BackgroundAudioTrack", &CWINRT_IID_WMEED_IBackgroundAudioTrackStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IBackgroundAudioTrackStatics *self, WMEED_EmbeddedAudioTrack* embeddedAudioTrack, WMEED_BackgroundAudioTrack** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, embeddedAudioTrack, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_background_audio_track_create_from_file_async(WS_IStorageFile* file, WF_IAsyncOperation_WMEED_BackgroundAudioTrack** out)
{
    WMEED_IBackgroundAudioTrackStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.BackgroundAudioTrack", &CWINRT_IID_WMEED_IBackgroundAudioTrackStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IBackgroundAudioTrackStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_BackgroundAudioTrack** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, file, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_composition_statics_load_async(WMEED_IMediaCompositionStatics *self, WS_StorageFile* file, WF_IAsyncOperation_WMEED_MediaComposition** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaCompositionStatics *self, WS_StorageFile* file, WF_IAsyncOperation_WMEED_MediaComposition** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, file, out);
}

HRESULT wmeed_media_overlay_factory_create(WMEED_IMediaOverlayFactory *self, WMEED_MediaClip* clip, WMEED_MediaOverlay** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaOverlayFactory *self, WMEED_MediaClip* clip, WMEED_MediaOverlay** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, clip, out);
}

HRESULT wmeed_media_overlay_factory_create_with_position_and_opacity(WMEED_IMediaOverlayFactory *self, WMEED_MediaClip* clip, WF_Rect position, double opacity, WMEED_MediaOverlay** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaOverlayFactory *self, WMEED_MediaClip* clip, WF_Rect position, double opacity, WMEED_MediaOverlay** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, clip, position, opacity, out);
}

HRESULT wmeed_media_overlay_layer_factory_create_with_compositor_definition(WMEED_IMediaOverlayLayerFactory *self, WMEEF_IVideoCompositorDefinition* compositorDefinition, WMEED_MediaOverlayLayer** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaOverlayLayerFactory *self, WMEEF_IVideoCompositorDefinition* compositorDefinition, WMEED_MediaOverlayLayer** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositorDefinition, out);
}

HRESULT wmeed_media_clip_new(WMEED_MediaClip **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.MediaClip", NULL, (void **)out);
}

HRESULT wmeed_media_clip_get__trim_time_from_start(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wmeed_media_clip_put__trim_time_from_start(WMEED_MediaClip *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__trim_time_from_end(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmeed_media_clip_put__trim_time_from_end(WMEED_MediaClip *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__original_duration(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__trimmed_duration(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__user_data(WMEED_MediaClip *self, WFOCO_IMap_HSTRING_HSTRING** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WFOCO_IMap_HSTRING_HSTRING** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wmeed_media_clip_clone(WMEED_MediaClip *self, WMEED_MediaClip** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WMEED_MediaClip** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, out);
}

HRESULT wmeed_media_clip_get__start_time_in_composition(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__end_time_in_composition(WMEED_MediaClip *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__embedded_audio_tracks(WMEED_MediaClip *self, WFOCO_IVectorView_WMEED_EmbeddedAudioTrack** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WFOCO_IVectorView_WMEED_EmbeddedAudioTrack** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__selected_embedded_audio_track_index(WMEED_MediaClip *self, uint32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, uint32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, value);
}

HRESULT wmeed_media_clip_put__selected_embedded_audio_track_index(WMEED_MediaClip *self, uint32_t value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, uint32_t value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, value);
}

HRESULT wmeed_media_clip_put__volume(WMEED_MediaClip *self, double value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, double value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__volume(WMEED_MediaClip *self, double *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, double *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[20];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get_video_encoding_properties(WMEED_MediaClip *self, WMEME_VideoEncodingProperties** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WMEME_VideoEncodingProperties** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[21];
    return fn(self, out);
}

HRESULT wmeed_media_clip_get__audio_effect_definitions(WMEED_MediaClip *self, WFOCO_IVector_WMEEF_IAudioEffectDefinition** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WFOCO_IVector_WMEEF_IAudioEffectDefinition** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[22];
    return fn(self, value);
}

HRESULT wmeed_media_clip_get__video_effect_definitions(WMEED_MediaClip *self, WFOCO_IVector_WMEEF_IVideoEffectDefinition** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaClip *self, WFOCO_IVector_WMEEF_IVideoEffectDefinition** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[23];
    return fn(self, value);
}

HRESULT wmeed_media_clip_create_from_surface(WGRDIDI_IDirect3DSurface* surface, WF_TimeSpan originalDuration, WMEED_MediaClip** out)
{
    WMEED_IMediaClipStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.MediaClip", &CWINRT_IID_WMEED_IMediaClipStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IMediaClipStatics_2 *self, WGRDIDI_IDirect3DSurface* surface, WF_TimeSpan originalDuration, WMEED_MediaClip** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, surface, originalDuration, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_clip_create_from_color(WUI_Color color, WF_TimeSpan originalDuration, WMEED_MediaClip** out)
{
    WMEED_IMediaClipStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.MediaClip", &CWINRT_IID_WMEED_IMediaClipStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IMediaClipStatics *self, WUI_Color color, WF_TimeSpan originalDuration, WMEED_MediaClip** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, color, originalDuration, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_clip_create_from_file_async(WS_IStorageFile* file, WF_IAsyncOperation_WMEED_MediaClip** out)
{
    WMEED_IMediaClipStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.MediaClip", &CWINRT_IID_WMEED_IMediaClipStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_IAsyncOperation_WMEED_MediaClip** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, file, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_clip_create_from_image_file_async(WS_IStorageFile* file, WF_TimeSpan originalDuration, WF_IAsyncOperation_WMEED_MediaClip** out)
{
    WMEED_IMediaClipStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.MediaClip", &CWINRT_IID_WMEED_IMediaClipStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IMediaClipStatics *self, WS_IStorageFile* file, WF_TimeSpan originalDuration, WF_IAsyncOperation_WMEED_MediaClip** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[8];
        hr = fn(statics, file, originalDuration, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_composition_new(WMEED_MediaComposition **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.MediaComposition", NULL, (void **)out);
}

HRESULT wmeed_media_composition_get__duration(WMEED_MediaComposition *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wmeed_media_composition_get__clips(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_MediaClip** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_MediaClip** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmeed_media_composition_get__background_audio_tracks(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_BackgroundAudioTrack** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_BackgroundAudioTrack** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmeed_media_composition_get__user_data(WMEED_MediaComposition *self, WFOCO_IMap_HSTRING_HSTRING** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WFOCO_IMap_HSTRING_HSTRING** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmeed_media_composition_clone(WMEED_MediaComposition *self, WMEED_MediaComposition** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WMEED_MediaComposition** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, out);
}

HRESULT wmeed_media_composition_save_async(WMEED_MediaComposition *self, WS_IStorageFile* file, WF_IAsyncAction** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WS_IStorageFile* file, WF_IAsyncAction** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, file, out);
}

HRESULT wmeed_media_composition_get_thumbnail_async(WMEED_MediaComposition *self, WF_TimeSpan timeFromStart, int32_t scaledWidth, int32_t scaledHeight, WMEED_VideoFramePrecision framePrecision, WF_IAsyncOperation_WGRIM_ImageStream** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WF_TimeSpan timeFromStart, int32_t scaledWidth, int32_t scaledHeight, WMEED_VideoFramePrecision framePrecision, WF_IAsyncOperation_WGRIM_ImageStream** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, timeFromStart, scaledWidth, scaledHeight, framePrecision, out);
}

HRESULT wmeed_media_composition_get_thumbnails_async(WMEED_MediaComposition *self, WFOCO_IIterable_WF_TimeSpan* timesFromStart, int32_t scaledWidth, int32_t scaledHeight, WMEED_VideoFramePrecision framePrecision, WF_IAsyncOperation_WFOCO_IVectorView_WGRIM_ImageStream** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WFOCO_IIterable_WF_TimeSpan* timesFromStart, int32_t scaledWidth, int32_t scaledHeight, WMEED_VideoFramePrecision framePrecision, WF_IAsyncOperation_WFOCO_IVectorView_WGRIM_ImageStream** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, timesFromStart, scaledWidth, scaledHeight, framePrecision, out);
}

HRESULT wmeed_media_composition_render_to_file_async(WMEED_MediaComposition *self, WS_IStorageFile* destination, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WS_IStorageFile* destination, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, destination, out);
}

HRESULT wmeed_media_composition_render_to_file_async_p_media_trimming_preference_p(WMEED_MediaComposition *self, WS_IStorageFile* destination, WMEED_MediaTrimmingPreference trimmingPreference, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WS_IStorageFile* destination, WMEED_MediaTrimmingPreference trimmingPreference, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, destination, trimmingPreference, out);
}

HRESULT wmeed_media_composition_render_to_file_async_p_media_trimming_preference_p_p(WMEED_MediaComposition *self, WS_IStorageFile* destination, WMEED_MediaTrimmingPreference trimmingPreference, WMEME_MediaEncodingProfile* encodingProfile, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WS_IStorageFile* destination, WMEED_MediaTrimmingPreference trimmingPreference, WMEME_MediaEncodingProfile* encodingProfile, WF_IAsyncOperationWithProgress_WMETR_TranscodeFailureReason_F64** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, destination, trimmingPreference, encodingProfile, out);
}

HRESULT wmeed_media_composition_create_default_encoding_profile(WMEED_MediaComposition *self, WMEME_MediaEncodingProfile** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WMEME_MediaEncodingProfile** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, out);
}

HRESULT wmeed_media_composition_generate_media_stream_source(WMEED_MediaComposition *self, WMECO_MediaStreamSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WMECO_MediaStreamSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, out);
}

HRESULT wmeed_media_composition_generate_media_stream_source_p_p(WMEED_MediaComposition *self, WMEME_MediaEncodingProfile* encodingProfile, WMECO_MediaStreamSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WMEME_MediaEncodingProfile* encodingProfile, WMECO_MediaStreamSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, encodingProfile, out);
}

HRESULT wmeed_media_composition_generate_preview_media_stream_source(WMEED_MediaComposition *self, int32_t scaledWidth, int32_t scaledHeight, WMECO_MediaStreamSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, int32_t scaledWidth, int32_t scaledHeight, WMECO_MediaStreamSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[20];
    return fn(self, scaledWidth, scaledHeight, out);
}

HRESULT wmeed_media_composition_get__overlay_layers(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_MediaOverlayLayer** value)
{
    WMEED_IMediaComposition_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WMEED_IMediaComposition_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaComposition *self, WFOCO_IVector_WMEED_MediaOverlayLayer** value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wmeed_media_composition_load_async(WS_StorageFile* file, WF_IAsyncOperation_WMEED_MediaComposition** out)
{
    WMEED_IMediaCompositionStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.Media.Editing.MediaComposition", &CWINRT_IID_WMEED_IMediaCompositionStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WMEED_IMediaCompositionStatics *self, WS_StorageFile* file, WF_IAsyncOperation_WMEED_MediaComposition** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, file, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wmeed_media_overlay_new(WMEED_MediaOverlay **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.MediaOverlay", NULL, (void **)out);
}

HRESULT wmeed_media_overlay_get__position(WMEED_MediaOverlay *self, WF_Rect *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WF_Rect *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_put__position(WMEED_MediaOverlay *self, WF_Rect value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WF_Rect value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_put__delay(WMEED_MediaOverlay *self, WF_TimeSpan value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WF_TimeSpan value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_get__delay(WMEED_MediaOverlay *self, WF_TimeSpan *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WF_TimeSpan *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_get__opacity(WMEED_MediaOverlay *self, double *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, double *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_put__opacity(WMEED_MediaOverlay *self, double value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, double value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_clone(WMEED_MediaOverlay *self, WMEED_MediaOverlay** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WMEED_MediaOverlay** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, out);
}

HRESULT wmeed_media_overlay_get__clip(WMEED_MediaOverlay *self, WMEED_MediaClip** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, WMEED_MediaClip** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_get__audio_enabled(WMEED_MediaOverlay *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_put__audio_enabled(WMEED_MediaOverlay *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlay *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_layer_new(WMEED_MediaOverlayLayer **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.Media.Editing.MediaOverlayLayer", NULL, (void **)out);
}

HRESULT wmeed_media_overlay_layer_clone(WMEED_MediaOverlayLayer *self, WMEED_MediaOverlayLayer** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlayLayer *self, WMEED_MediaOverlayLayer** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, out);
}

HRESULT wmeed_media_overlay_layer_get__overlays(WMEED_MediaOverlayLayer *self, WFOCO_IVector_WMEED_MediaOverlay** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlayLayer *self, WFOCO_IVector_WMEED_MediaOverlay** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wmeed_media_overlay_layer_get__custom_compositor_definition(WMEED_MediaOverlayLayer *self, WMEEF_IVideoCompositorDefinition** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_MediaOverlayLayer *self, WMEEF_IVideoCompositorDefinition** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wmeed_media_composition_2_get__overlay_layers(WMEED_IMediaComposition_2 *self, WFOCO_IVector_WMEED_MediaOverlayLayer** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WMEED_IMediaComposition_2 *self, WFOCO_IVector_WMEED_MediaOverlayLayer** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

