/* Generated by cwinrt-gen; do not edit. */

#include <windows.h>
#include <unknwn.h>
#include <cwinrt/factory.h>
#include <cwinrt/event.h>
#include <cwinrt/Windows.UI.Composition.Interactions.h>

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_statics_create(WUICOIN_IInteractionTrackerVector2InertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerVector2InertiaNaturalMotion** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerVector2InertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerVector2InertiaNaturalMotion** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_visual_interaction_source_statics_create(WUICOIN_IVisualInteractionSourceStatics *self, WUC_Visual* source, WUICOIN_VisualInteractionSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSourceStatics *self, WUC_Visual* source, WUICOIN_VisualInteractionSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, source, out);
}

HRESULT wuicoin_visual_interaction_source_statics_2_create_from_i_visual_element(WUICOIN_IVisualInteractionSourceStatics_2 *self, WUC_IVisualElement* source, WUICOIN_VisualInteractionSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSourceStatics_2 *self, WUC_IVisualElement* source, WUICOIN_VisualInteractionSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, source, out);
}

HRESULT wuicoin_interaction_source_configuration_new(WUICOIN_InteractionSourceConfiguration **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionSourceConfiguration", NULL, (void **)out);
}

HRESULT wuicoin_interaction_source_configuration_get__position_x_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_source_configuration_put__position_x_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_source_configuration_get__position_y_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_source_configuration_put__position_y_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_source_configuration_get__scale_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuicoin_interaction_source_configuration_put__scale_source_mode(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionSourceConfiguration *self, WUICOIN_InteractionSourceRedirectionMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_new(WUICOIN_InteractionTracker **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTracker", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_get__interaction_sources(WUICOIN_InteractionTracker *self, WUICOIN_CompositionInteractionSourceCollection** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WUICOIN_CompositionInteractionSourceCollection** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__is_position_rounding_suggested(WUICOIN_InteractionTracker *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__max_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__max_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__max_scale(WUICOIN_InteractionTracker *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__max_scale(WUICOIN_InteractionTracker *self, float value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__min_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__min_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__min_scale(WUICOIN_InteractionTracker *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__min_scale(WUICOIN_InteractionTracker *self, float value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__natural_resting_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__natural_resting_scale(WUICOIN_InteractionTracker *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__owner(WUICOIN_InteractionTracker *self, WUICOIN_IInteractionTrackerOwner** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WUICOIN_IInteractionTrackerOwner** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__position(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__position_inertia_decay_rate(WUICOIN_InteractionTracker *self, WFN_Vector_3** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[20];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__position_inertia_decay_rate(WUICOIN_InteractionTracker *self, WFN_Vector_3* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[21];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__position_velocity_in_pixels_per_second(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[22];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__scale(WUICOIN_InteractionTracker *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[23];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__scale_inertia_decay_rate(WUICOIN_InteractionTracker *self, float** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[24];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_put__scale_inertia_decay_rate(WUICOIN_InteractionTracker *self, float* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[25];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_get__scale_velocity_in_percent_per_second(WUICOIN_InteractionTracker *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[26];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_adjust_position_x_if_greater_than_threshold(WUICOIN_InteractionTracker *self, float adjustment, float positionThreshold)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float adjustment, float positionThreshold);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[27];
    return fn(self, adjustment, positionThreshold);
}

HRESULT wuicoin_interaction_tracker_adjust_position_y_if_greater_than_threshold(WUICOIN_InteractionTracker *self, float adjustment, float positionThreshold)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float adjustment, float positionThreshold);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[28];
    return fn(self, adjustment, positionThreshold);
}

HRESULT wuicoin_interaction_tracker_configure_position_x_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[29];
    return fn(self, modifiers);
}

HRESULT wuicoin_interaction_tracker_configure_position_y_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[30];
    return fn(self, modifiers);
}

HRESULT wuicoin_interaction_tracker_configure_scale_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerInertiaModifier* modifiers);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[31];
    return fn(self, modifiers);
}

HRESULT wuicoin_interaction_tracker_try_update_position(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[32];
    return fn(self, value, out);
}

HRESULT wuicoin_interaction_tracker_try_update_position_by(WUICOIN_InteractionTracker *self, WFN_Vector_3 amount, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 amount, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[33];
    return fn(self, amount, out);
}

HRESULT wuicoin_interaction_tracker_try_update_position_with_animation(WUICOIN_InteractionTracker *self, WUC_CompositionAnimation* animation, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WUC_CompositionAnimation* animation, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[34];
    return fn(self, animation, out);
}

HRESULT wuicoin_interaction_tracker_try_update_position_with_additional_velocity(WUICOIN_InteractionTracker *self, WFN_Vector_3 velocityInPixelsPerSecond, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 velocityInPixelsPerSecond, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[35];
    return fn(self, velocityInPixelsPerSecond, out);
}

HRESULT wuicoin_interaction_tracker_try_update_scale(WUICOIN_InteractionTracker *self, float value, WFN_Vector_3 centerPoint, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float value, WFN_Vector_3 centerPoint, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[36];
    return fn(self, value, centerPoint, out);
}

HRESULT wuicoin_interaction_tracker_try_update_scale_with_animation(WUICOIN_InteractionTracker *self, WUC_CompositionAnimation* animation, WFN_Vector_3 centerPoint, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WUC_CompositionAnimation* animation, WFN_Vector_3 centerPoint, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[37];
    return fn(self, animation, centerPoint, out);
}

HRESULT wuicoin_interaction_tracker_try_update_scale_with_additional_velocity(WUICOIN_InteractionTracker *self, float velocityInPercentPerSecond, WFN_Vector_3 centerPoint, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, float velocityInPercentPerSecond, WFN_Vector_3 centerPoint, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[38];
    return fn(self, velocityInPercentPerSecond, centerPoint, out);
}

HRESULT wuicoin_interaction_tracker_configure_center_point_x_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IInteractionTracker_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_configure_center_point_y_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IInteractionTracker_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[7];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_configure_vector2_position_inertia_modifiers(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerVector2InertiaModifier* modifiers)
{
    WUICOIN_IInteractionTracker_3 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_3, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFOCO_IIterable_WUICOIN_InteractionTrackerVector2InertiaModifier* modifiers);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, modifiers);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_try_update_position_3_interaction_tracker_clamping_option_i32(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, int32_t *out)
{
    WUICOIN_IInteractionTracker_4 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_4, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, int32_t *out);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value, option, out);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_try_update_position_by_3_interaction_tracker_clamping_option_i32(WUICOIN_InteractionTracker *self, WFN_Vector_3 amount, WUICOIN_InteractionTrackerClampingOption option, int32_t *out)
{
    WUICOIN_IInteractionTracker_4 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_4, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 amount, WUICOIN_InteractionTrackerClampingOption option, int32_t *out);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[7];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, amount, option, out);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_get__is_inertia_from_impulse(WUICOIN_InteractionTracker *self, BOOL *value)
{
    WUICOIN_IInteractionTracker_4 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_4, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[8];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_try_update_position_3_interaction_tracker_clamping_optio_624bbfb9(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, WUICOIN_InteractionTrackerPositionUpdateOption posUpdateOption, int32_t *out)
{
    WUICOIN_IInteractionTracker_5 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTracker_5, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTracker *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, WUICOIN_InteractionTrackerPositionUpdateOption posUpdateOption, int32_t *out);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value, option, posUpdateOption, out);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_set_binding_mode(WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes axisMode)
{
    WUICOIN_IInteractionTrackerStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTracker", &CWINRT_IID_WUICOIN_IInteractionTrackerStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes axisMode);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, boundTracker1, boundTracker2, axisMode);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_get_binding_mode(WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes *out)
{
    WUICOIN_IInteractionTrackerStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTracker", &CWINRT_IID_WUICOIN_IInteractionTrackerStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes *out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, boundTracker1, boundTracker2, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_create(WUC_Comp* compositor, WUICOIN_InteractionTracker** out)
{
    WUICOIN_IInteractionTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTracker", &CWINRT_IID_WUICOIN_IInteractionTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTracker** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_create_with_owner(WUC_Comp* compositor, WUICOIN_IInteractionTrackerOwner* owner, WUICOIN_InteractionTracker** out)
{
    WUICOIN_IInteractionTrackerStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTracker", &CWINRT_IID_WUICOIN_IInteractionTrackerStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_IInteractionTrackerOwner* owner, WUICOIN_InteractionTracker** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[7];
        hr = fn(statics, compositor, owner, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_custom_animation_state_entered_args_new(WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerCustomAnimationStateEnteredArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_custom_animation_state_entered_args_get__request_id(WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_custom_animation_state_entered_args_get__is_from_binding(WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs *self, BOOL *value)
{
    WUICOIN_IInteractionTrackerCustomAnimationStateEnteredArgs_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTrackerCustomAnimationStateEnteredArgs_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_idle_state_entered_args_new(WUICOIN_InteractionTrackerIdleStateEnteredArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerIdleStateEnteredArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_idle_state_entered_args_get__request_id(WUICOIN_InteractionTrackerIdleStateEnteredArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerIdleStateEnteredArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_idle_state_entered_args_get__is_from_binding(WUICOIN_InteractionTrackerIdleStateEnteredArgs *self, BOOL *value)
{
    WUICOIN_IInteractionTrackerIdleStateEnteredArgs_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTrackerIdleStateEnteredArgs_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerIdleStateEnteredArgs *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_inertia_motion_new(WUICOIN_InteractionTrackerInertiaMotion **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaMotion", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_get__condition(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_put__condition(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_get__motion(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_put__motion(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaMotion *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_create(WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaMotion** out)
{
    WUICOIN_IInteractionTrackerInertiaMotionStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaMotion", &CWINRT_IID_WUICOIN_IInteractionTrackerInertiaMotionStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerInertiaMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaMotion** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_new(WUICOIN_InteractionTrackerInertiaNaturalMotion **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaNaturalMotion", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_get__condition(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_put__condition(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_get__natural_motion(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ScalarNaturalMotionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ScalarNaturalMotionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_put__natural_motion(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ScalarNaturalMotionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaNaturalMotion *self, WUC_ScalarNaturalMotionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_create(WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaNaturalMotion** out)
{
    WUICOIN_IInteractionTrackerInertiaNaturalMotionStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaNaturalMotion", &CWINRT_IID_WUICOIN_IInteractionTrackerInertiaNaturalMotionStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerInertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaNaturalMotion** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_new(WUICOIN_InteractionTrackerInertiaRestingValue **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaRestingValue", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_get__condition(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_put__condition(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_get__resting_value(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_put__resting_value(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaRestingValue *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_create(WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaRestingValue** out)
{
    WUICOIN_IInteractionTrackerInertiaRestingValueStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaRestingValue", &CWINRT_IID_WUICOIN_IInteractionTrackerInertiaRestingValueStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerInertiaRestingValueStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaRestingValue** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_statics_2_set_binding_mode(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes axisMode)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes axisMode);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, boundTracker1, boundTracker2, axisMode);
}

HRESULT wuicoin_interaction_tracker_statics_2_get_binding_mode(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerStatics_2 *self, WUICOIN_InteractionTracker* boundTracker1, WUICOIN_InteractionTracker* boundTracker2, WUICOIN_InteractionBindingAxisModes *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, boundTracker1, boundTracker2, out);
}

HRESULT wuicoin_interaction_tracker_interacting_state_entered_args_new(WUICOIN_InteractionTrackerInteractingStateEnteredArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerInteractingStateEnteredArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_interacting_state_entered_args_get__request_id(WUICOIN_InteractionTrackerInteractingStateEnteredArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInteractingStateEnteredArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_interacting_state_entered_args_get__is_from_binding(WUICOIN_InteractionTrackerInteractingStateEnteredArgs *self, BOOL *value)
{
    WUICOIN_IInteractionTrackerInteractingStateEnteredArgs_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTrackerInteractingStateEnteredArgs_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInteractingStateEnteredArgs *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_request_ignored_args_new(WUICOIN_InteractionTrackerRequestIgnoredArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerRequestIgnoredArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_request_ignored_args_get__request_id(WUICOIN_InteractionTrackerRequestIgnoredArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerRequestIgnoredArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_values_changed_args_new(WUICOIN_InteractionTrackerValuesChangedArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerValuesChangedArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_values_changed_args_get__position(WUICOIN_InteractionTrackerValuesChangedArgs *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerValuesChangedArgs *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_values_changed_args_get__request_id(WUICOIN_InteractionTrackerValuesChangedArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerValuesChangedArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_values_changed_args_get__scale(WUICOIN_InteractionTrackerValuesChangedArgs *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerValuesChangedArgs *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_new(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerVector2InertiaNaturalMotion", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_get__condition(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_put__condition(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_get__natural_motion(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_Vector2NaturalMotionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_Vector2NaturalMotionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_put__natural_motion(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_Vector2NaturalMotionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerVector2InertiaNaturalMotion *self, WUC_Vector2NaturalMotionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_vector2_inertia_natural_motion_create(WUC_Comp* compositor, WUICOIN_InteractionTrackerVector2InertiaNaturalMotion** out)
{
    WUICOIN_IInteractionTrackerVector2InertiaNaturalMotionStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.InteractionTrackerVector2InertiaNaturalMotion", &CWINRT_IID_WUICOIN_IInteractionTrackerVector2InertiaNaturalMotionStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IInteractionTrackerVector2InertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerVector2InertiaNaturalMotion** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_visual_interaction_source_get__is_position_x_rails_enabled(WUICOIN_VisualInteractionSource *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__is_position_x_rails_enabled(WUICOIN_VisualInteractionSource *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__is_position_y_rails_enabled(WUICOIN_VisualInteractionSource *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__is_position_y_rails_enabled(WUICOIN_VisualInteractionSource *self, BOOL value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, BOOL value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__manipulation_redirection_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_VisualInteractionSourceRedirectionMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_VisualInteractionSourceRedirectionMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__manipulation_redirection_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_VisualInteractionSourceRedirectionMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_VisualInteractionSourceRedirectionMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__position_x_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__position_x_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__position_x_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__position_x_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__position_y_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__position_y_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[17];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__position_y_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[18];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__position_y_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[19];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__scale_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[20];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__scale_chaining_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionChainingMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[21];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__scale_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[22];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_put__scale_source_mode(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceMode value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[23];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_get__source(WUICOIN_VisualInteractionSource *self, WUC_Visual** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUC_Visual** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[24];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_try_redirect_for_manipulation(WUICOIN_VisualInteractionSource *self, WUIIN_PointerPoint* pointerPoint)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUIIN_PointerPoint* pointerPoint);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[25];
    return fn(self, pointerPoint);
}

HRESULT wuicoin_visual_interaction_source_get__delta_position(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__delta_scale(WUICOIN_VisualInteractionSource *self, float *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, float *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[7];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__position(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[8];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__position_velocity(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFN_Vector_3 *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[9];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__scale(WUICOIN_VisualInteractionSource *self, float *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, float *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[10];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__scale_velocity(WUICOIN_VisualInteractionSource *self, float *value)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, float *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[11];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_configure_center_point_x_modifiers(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[12];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_configure_center_point_y_modifiers(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[13];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_configure_delta_position_x_modifiers(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[14];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_configure_delta_position_y_modifiers(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[15];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_configure_delta_scale_modifiers(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    WUICOIN_IVisualInteractionSource_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[16];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, conditionalValues);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_get__pointer_wheel_config(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceConfiguration** value)
{
    WUICOIN_IVisualInteractionSource_3 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IVisualInteractionSource_3, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_VisualInteractionSource *self, WUICOIN_InteractionSourceConfiguration** value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_visual_interaction_source_create_from_i_visual_element(WUC_IVisualElement* source, WUICOIN_VisualInteractionSource** out)
{
    WUICOIN_IVisualInteractionSourceStatics_2 *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.VisualInteractionSource", &CWINRT_IID_WUICOIN_IVisualInteractionSourceStatics_2, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IVisualInteractionSourceStatics_2 *self, WUC_IVisualElement* source, WUICOIN_VisualInteractionSource** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, source, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_visual_interaction_source_create(WUC_Visual* source, WUICOIN_VisualInteractionSource** out)
{
    WUICOIN_IVisualInteractionSourceStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.VisualInteractionSource", &CWINRT_IID_WUICOIN_IVisualInteractionSourceStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_IVisualInteractionSourceStatics *self, WUC_Visual* source, WUICOIN_VisualInteractionSource** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, source, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_composition_conditional_value_statics_create(WUICOIN_ICompositionConditionalValueStatics *self, WUC_Comp* compositor, WUICOIN_CompositionConditionalValue** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_ICompositionConditionalValueStatics *self, WUC_Comp* compositor, WUICOIN_CompositionConditionalValue** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_composition_conditional_value_new(WUICOIN_CompositionConditionalValue **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.CompositionConditionalValue", NULL, (void **)out);
}

HRESULT wuicoin_composition_conditional_value_get__condition(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_composition_conditional_value_put__condition(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_composition_conditional_value_get__value(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_composition_conditional_value_put__value(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionConditionalValue *self, WUC_ExpressionAnimation* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_composition_conditional_value_create(WUC_Comp* compositor, WUICOIN_CompositionConditionalValue** out)
{
    WUICOIN_ICompositionConditionalValueStatics *statics = NULL;
    HRESULT hr = cwinrt_factory_get_statics(L"Windows.UI.Composition.Interactions.CompositionConditionalValue", &CWINRT_IID_WUICOIN_ICompositionConditionalValueStatics, (void **)&statics);
    if (FAILED(hr)) return hr;
    {
        typedef HRESULT (__stdcall *cwinrt_static_fn_t)(WUICOIN_ICompositionConditionalValueStatics *self, WUC_Comp* compositor, WUICOIN_CompositionConditionalValue** out);
        cwinrt_static_fn_t fn = (cwinrt_static_fn_t)((void **)((IUnknown *)statics)->lpVtbl)[6];
        hr = fn(statics, compositor, out);
    }
    ((IUnknown *)statics)->lpVtbl->Release((IUnknown *)statics);
    return hr;
}

HRESULT wuicoin_interaction_tracker_statics_create(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTracker** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTracker** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_interaction_tracker_statics_create_with_owner(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_IInteractionTrackerOwner* owner, WUICOIN_InteractionTracker** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerStatics *self, WUC_Comp* compositor, WUICOIN_IInteractionTrackerOwner* owner, WUICOIN_InteractionTracker** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, compositor, owner, out);
}

HRESULT wuicoin_interaction_tracker_owner_custom_animation_state_entered(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerCustomAnimationStateEnteredArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_owner_idle_state_entered(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerIdleStateEnteredArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerIdleStateEnteredArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_owner_inertia_state_entered(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerInertiaStateEnteredArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerInertiaStateEnteredArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_owner_interacting_state_entered(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerInteractingStateEnteredArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerInteractingStateEnteredArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_owner_request_ignored(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerRequestIgnoredArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerRequestIgnoredArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_owner_values_changed(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerValuesChangedArgs* args)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerOwner *self, WUICOIN_InteractionTracker* sender, WUICOIN_InteractionTrackerValuesChangedArgs* args);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, sender, args);
}

HRESULT wuicoin_interaction_tracker_inertia_resting_value_statics_create(WUICOIN_IInteractionTrackerInertiaRestingValueStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaRestingValue** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInertiaRestingValueStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaRestingValue** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_interaction_tracker_inertia_natural_motion_statics_create(WUICOIN_IInteractionTrackerInertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaNaturalMotion** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInertiaNaturalMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaNaturalMotion** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_interaction_tracker_inertia_motion_statics_create(WUICOIN_IInteractionTrackerInertiaMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaMotion** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInertiaMotionStatics *self, WUC_Comp* compositor, WUICOIN_InteractionTrackerInertiaMotion** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, compositor, out);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_new(WUICOIN_InteractionTrackerInertiaStateEnteredArgs **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.InteractionTrackerInertiaStateEnteredArgs", NULL, (void **)out);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__modified_resting_position(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__modified_resting_scale(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__natural_resting_position(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__natural_resting_scale(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__position_velocity_in_pixels_per_second(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__request_id(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__scale_velocity_in_percent_per_second(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__is_inertia_from_impulse(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, BOOL *value)
{
    WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_2 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_2, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_get__is_from_binding(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, BOOL *value)
{
    WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_3 *cwinrt_disp_ = NULL;
    HRESULT cwinrt_hr_ = ((IUnknown *)self)->lpVtbl->QueryInterface((IUnknown *)self, &CWINRT_IID_WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_3, (void **)&cwinrt_disp_);
    if (FAILED(cwinrt_hr_)) return cwinrt_hr_;
    {
        typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_InteractionTrackerInertiaStateEnteredArgs *self, BOOL *value);
        cwinrt_fn_t fn = (cwinrt_fn_t)((void **)((IUnknown *)cwinrt_disp_)->lpVtbl)[6];
        cwinrt_hr_ = fn((void *)cwinrt_disp_, value);
    }
    ((IUnknown *)cwinrt_disp_)->lpVtbl->Release((IUnknown *)cwinrt_disp_);
    return cwinrt_hr_;
}

HRESULT wuicoin_composition_interaction_source_collection_new(WUICOIN_CompositionInteractionSourceCollection **out)
{
    if (!out) return E_POINTER;
    *out = NULL;
    return cwinrt_factory_activate(L"Windows.UI.Composition.Interactions.CompositionInteractionSourceCollection", NULL, (void **)out);
}

HRESULT wuicoin_composition_interaction_source_collection_get__count(WUICOIN_CompositionInteractionSourceCollection *self, int32_t *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionInteractionSourceCollection *self, int32_t *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_composition_interaction_source_collection_add(WUICOIN_CompositionInteractionSourceCollection *self, WUICOIN_ICompositionInteractionSource* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionInteractionSourceCollection *self, WUICOIN_ICompositionInteractionSource* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_composition_interaction_source_collection_remove(WUICOIN_CompositionInteractionSourceCollection *self, WUICOIN_ICompositionInteractionSource* value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionInteractionSourceCollection *self, WUICOIN_ICompositionInteractionSource* value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_composition_interaction_source_collection_remove_all(WUICOIN_CompositionInteractionSourceCollection *self)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionInteractionSourceCollection *self);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self);
}

HRESULT wuicoin_composition_interaction_source_collection_first(WUICOIN_CompositionInteractionSourceCollection *self, WFOCO_IIterator_WUICOIN_ICompositionInteractionSource** out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_CompositionInteractionSourceCollection *self, WFOCO_IIterator_WUICOIN_ICompositionInteractionSource** out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, out);
}

HRESULT wuicoin_interaction_tracker_2_configure_center_point_x_inertia_modifiers(WUICOIN_IInteractionTracker_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_interaction_tracker_2_configure_center_point_y_inertia_modifiers(WUICOIN_IInteractionTracker_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_interaction_tracker_3_configure_vector2_position_inertia_modifiers(WUICOIN_IInteractionTracker_3 *self, WFOCO_IIterable_WUICOIN_InteractionTrackerVector2InertiaModifier* modifiers)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_3 *self, WFOCO_IIterable_WUICOIN_InteractionTrackerVector2InertiaModifier* modifiers);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, modifiers);
}

HRESULT wuicoin_interaction_tracker_4_try_update_position(WUICOIN_IInteractionTracker_4 *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_4 *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value, option, out);
}

HRESULT wuicoin_interaction_tracker_4_try_update_position_by(WUICOIN_IInteractionTracker_4 *self, WFN_Vector_3 amount, WUICOIN_InteractionTrackerClampingOption option, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_4 *self, WFN_Vector_3 amount, WUICOIN_InteractionTrackerClampingOption option, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, amount, option, out);
}

HRESULT wuicoin_interaction_tracker_4_get__is_inertia_from_impulse(WUICOIN_IInteractionTracker_4 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_4 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_5_try_update_position(WUICOIN_IInteractionTracker_5 *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, WUICOIN_InteractionTrackerPositionUpdateOption posUpdateOption, int32_t *out)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTracker_5 *self, WFN_Vector_3 value, WUICOIN_InteractionTrackerClampingOption option, WUICOIN_InteractionTrackerPositionUpdateOption posUpdateOption, int32_t *out);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value, option, posUpdateOption, out);
}

HRESULT wuicoin_interaction_tracker_custom_animation_state_entered_args_2_get__is_from_binding(WUICOIN_IInteractionTrackerCustomAnimationStateEnteredArgs_2 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerCustomAnimationStateEnteredArgs_2 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_idle_state_entered_args_2_get__is_from_binding(WUICOIN_IInteractionTrackerIdleStateEnteredArgs_2 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerIdleStateEnteredArgs_2 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_interacting_state_entered_args_2_get__is_from_binding(WUICOIN_IInteractionTrackerInteractingStateEnteredArgs_2 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInteractingStateEnteredArgs_2 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__delta_position(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__delta_scale(WUICOIN_IVisualInteractionSource_2 *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[7];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__position(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[8];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__position_velocity(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFN_Vector_3 *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[9];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__scale(WUICOIN_IVisualInteractionSource_2 *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[10];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_get__scale_velocity(WUICOIN_IVisualInteractionSource_2 *self, float *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, float *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[11];
    return fn(self, value);
}

HRESULT wuicoin_visual_interaction_source_2_configure_center_point_x_modifiers(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[12];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_visual_interaction_source_2_configure_center_point_y_modifiers(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[13];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_visual_interaction_source_2_configure_delta_position_x_modifiers(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[14];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_visual_interaction_source_2_configure_delta_position_y_modifiers(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[15];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_visual_interaction_source_2_configure_delta_scale_modifiers(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_2 *self, WFOCO_IIterable_WUICOIN_CompositionConditionalValue* conditionalValues);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[16];
    return fn(self, conditionalValues);
}

HRESULT wuicoin_visual_interaction_source_3_get__pointer_wheel_config(WUICOIN_IVisualInteractionSource_3 *self, WUICOIN_InteractionSourceConfiguration** value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IVisualInteractionSource_3 *self, WUICOIN_InteractionSourceConfiguration** value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_2_get__is_inertia_from_impulse(WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_2 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_2 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

HRESULT wuicoin_interaction_tracker_inertia_state_entered_args_3_get__is_from_binding(WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_3 *self, BOOL *value)
{
    IUnknown *cwinrt_obj_ = (IUnknown *)self;
    typedef HRESULT (__stdcall *cwinrt_fn_t)(WUICOIN_IInteractionTrackerInertiaStateEnteredArgs_3 *self, BOOL *value);
    cwinrt_fn_t fn = (cwinrt_fn_t)((void **)cwinrt_obj_->lpVtbl)[6];
    return fn(self, value);
}

