/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_NETWORKING_H
#define CWINRT_WINDOWS_NETWORKING_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WNECO_IPInformation
#define CWINRT_FWD_WNECO_IPInformation
typedef struct WNECO_IPInformation WNECO_IPInformation;
#endif

/* Types (forward declarations) */
typedef struct WNE_IHostNameFactory WNE_IHostNameFactory;
typedef struct WNE_IEndpointPairFactory WNE_IEndpointPairFactory;
typedef struct WNE_HostName WNE_HostName;
typedef struct WNE_EndpointPair WNE_EndpointPair;
typedef struct WNE_IHostNameStatics WNE_IHostNameStatics;
typedef struct WNE_IHostName WNE_IHostName;
typedef struct WNE_IEndpointPair WNE_IEndpointPair;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WNECO_IPInformation
#define CWINRT_FWD_WNECO_IPInformation
typedef struct WNECO_IPInformation WNECO_IPInformation;
#endif

#ifndef CWINRT_FWD_WNE_HostNameType
#define CWINRT_FWD_WNE_HostNameType
typedef enum WNE_HostNameType {
    WNE_HostNameType_DomainName = 0,
    WNE_HostNameType_Ipv4 = 1,
    WNE_HostNameType_Ipv6 = 2,
    WNE_HostNameType_Bluetooth = 3
} WNE_HostNameType;
#endif

#ifndef CWINRT_FWD_WNE_HostNameSortOptions
#define CWINRT_FWD_WNE_HostNameSortOptions
typedef enum WNE_HostNameSortOptions {
    WNE_HostNameSortOptions_None = 0,
    WNE_HostNameSortOptions_OptimizeForLongConnections = 2
} WNE_HostNameSortOptions;
#endif

#ifndef CWINRT_FWD_WNE_DomainNameType
#define CWINRT_FWD_WNE_DomainNameType
typedef enum WNE_DomainNameType {
    WNE_DomainNameType_Suffix = 0,
    WNE_DomainNameType_FullyQualified = 1
} WNE_DomainNameType;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WNE_IHostNameFactory
#define CWINRT_IIDDEF_WNE_IHostNameFactory
static const IID CWINRT_IID_WNE_IHostNameFactory CWINRT_MAYBE_UNUSED = { 0x458C23ED, 0x712F, 0x4576, { 0xAD, 0xF1, 0xC2, 0x0B, 0x2C, 0x64, 0x35, 0x58 } };
#endif
#ifndef CWINRT_IIDDEF_WNE_IEndpointPairFactory
#define CWINRT_IIDDEF_WNE_IEndpointPairFactory
static const IID CWINRT_IID_WNE_IEndpointPairFactory CWINRT_MAYBE_UNUSED = { 0xB609D971, 0x64E0, 0x442B, { 0xAA, 0x6F, 0xCC, 0x8C, 0x8F, 0x18, 0x1F, 0x78 } };
#endif
#ifndef CWINRT_IIDDEF_WNE_IHostNameStatics
#define CWINRT_IIDDEF_WNE_IHostNameStatics
static const IID CWINRT_IID_WNE_IHostNameStatics CWINRT_MAYBE_UNUSED = { 0xF68CD4BF, 0xA388, 0x4E8B, { 0x91, 0xEA, 0x54, 0xDD, 0x6D, 0xD9, 0x01, 0xC0 } };
#endif
#ifndef CWINRT_IIDDEF_WNE_IHostName
#define CWINRT_IIDDEF_WNE_IHostName
static const IID CWINRT_IID_WNE_IHostName CWINRT_MAYBE_UNUSED = { 0xBF8ECAAD, 0xED96, 0x49A7, { 0x90, 0x84, 0xD4, 0x16, 0xCA, 0xE8, 0x8D, 0xCB } };
#endif
#ifndef CWINRT_IIDDEF_WNE_IEndpointPair
#define CWINRT_IIDDEF_WNE_IEndpointPair
static const IID CWINRT_IID_WNE_IEndpointPair CWINRT_MAYBE_UNUSED = { 0x33A0AA36, 0xF8FA, 0x4B30, { 0xB8, 0x56, 0x76, 0x51, 0x7C, 0x3B, 0xD0, 0x6D } };
#endif

/* Methods */

/* Windows.Networking.IHostNameFactory */
/* Windows.Networking.IHostNameFactory.CreateHostName(hostName) */
HRESULT wne_host_name_factory_create_host_name(WNE_IHostNameFactory *self, cwinrt_hstring hostName, WNE_HostName** out);

/* Windows.Networking.IEndpointPairFactory */
/* Windows.Networking.IEndpointPairFactory.CreateEndpointPair(localHostName, localServiceName, remoteHostName, remoteServiceName) */
HRESULT wne_endpoint_pair_factory_create_endpoint_pair(WNE_IEndpointPairFactory *self, WNE_HostName* localHostName, cwinrt_hstring localServiceName, WNE_HostName* remoteHostName, cwinrt_hstring remoteServiceName, WNE_EndpointPair** out);

/* activate Windows.Networking.HostName */
HRESULT wne_host_name_new(WNE_HostName **out);

/* Windows.Networking.HostName */
/* Windows.Networking.HostName.get_IPInformation() */
HRESULT wne_host_name_get__i_p_information(WNE_HostName *self, WNECO_IPInformation** value);

/* Windows.Networking.HostName.get_RawName() */
HRESULT wne_host_name_get__raw_name(WNE_HostName *self, cwinrt_hstring *value);

/* Windows.Networking.HostName.get_DisplayName() */
HRESULT wne_host_name_get__display_name(WNE_HostName *self, cwinrt_hstring *value);

/* Windows.Networking.HostName.get_CanonicalName() */
HRESULT wne_host_name_get__canonical_name(WNE_HostName *self, cwinrt_hstring *value);

/* Windows.Networking.HostName.get_Type() */
HRESULT wne_host_name_get__type(WNE_HostName *self, WNE_HostNameType *value);

/* Windows.Networking.HostName.IsEqual(hostName) */
HRESULT wne_host_name_is_equal(WNE_HostName *self, WNE_HostName* hostName, BOOL *out);

/* Windows.Networking.HostName.ToString() */
HRESULT wne_host_name_to_string(WNE_HostName *self, cwinrt_hstring *out);

/* Windows.Networking.HostName.Compare(value1, value2) */
HRESULT wne_host_name_compare(cwinrt_hstring value1, cwinrt_hstring value2, int32_t *out);

/* activate Windows.Networking.EndpointPair */
HRESULT wne_endpoint_pair_new(WNE_EndpointPair **out);

/* Windows.Networking.EndpointPair */
/* Windows.Networking.EndpointPair.get_LocalHostName() */
HRESULT wne_endpoint_pair_get__local_host_name(WNE_EndpointPair *self, WNE_HostName** value);

/* Windows.Networking.EndpointPair.put_LocalHostName() */
HRESULT wne_endpoint_pair_put__local_host_name(WNE_EndpointPair *self, WNE_HostName* value);

/* Windows.Networking.EndpointPair.get_LocalServiceName() */
HRESULT wne_endpoint_pair_get__local_service_name(WNE_EndpointPair *self, cwinrt_hstring *value);

/* Windows.Networking.EndpointPair.put_LocalServiceName() */
HRESULT wne_endpoint_pair_put__local_service_name(WNE_EndpointPair *self, cwinrt_hstring value);

/* Windows.Networking.EndpointPair.get_RemoteHostName() */
HRESULT wne_endpoint_pair_get__remote_host_name(WNE_EndpointPair *self, WNE_HostName** value);

/* Windows.Networking.EndpointPair.put_RemoteHostName() */
HRESULT wne_endpoint_pair_put__remote_host_name(WNE_EndpointPair *self, WNE_HostName* value);

/* Windows.Networking.EndpointPair.get_RemoteServiceName() */
HRESULT wne_endpoint_pair_get__remote_service_name(WNE_EndpointPair *self, cwinrt_hstring *value);

/* Windows.Networking.EndpointPair.put_RemoteServiceName() */
HRESULT wne_endpoint_pair_put__remote_service_name(WNE_EndpointPair *self, cwinrt_hstring value);

/* Windows.Networking.IHostNameStatics */
/* Windows.Networking.IHostNameStatics.Compare(value1, value2) */
HRESULT wne_host_name_statics_compare(WNE_IHostNameStatics *self, cwinrt_hstring value1, cwinrt_hstring value2, int32_t *out);

/* Windows.Networking.IHostName */
/* Windows.Networking.IEndpointPair */
#endif /* CWINRT_WINDOWS_NETWORKING_H */
