/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_APPLICATIONMODEL_STORE_H
#define CWINRT_WINDOWS_APPLICATIONMODEL_STORE_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WS_StorageFile
#define CWINRT_FWD_WS_StorageFile
typedef struct WS_StorageFile WS_StorageFile;
#endif

/* Types (forward declarations) */
typedef struct WAPST_ICurrentApp WAPST_ICurrentApp;
typedef struct WAPST_ICurrentApp2Statics WAPST_ICurrentApp2Statics;
typedef struct WAPST_ICurrentAppSimulator WAPST_ICurrentAppSimulator;
typedef struct WAPST_ICurrentAppSimulatorStaticsWithFiltering WAPST_ICurrentAppSimulatorStaticsWithFiltering;
typedef struct WAPST_ICurrentAppSimulatorWithCampaignId WAPST_ICurrentAppSimulatorWithCampaignId;
typedef struct WAPST_ICurrentAppStaticsWithFiltering WAPST_ICurrentAppStaticsWithFiltering;
typedef struct WAPST_ICurrentAppWithCampaignId WAPST_ICurrentAppWithCampaignId;
typedef struct WAPST_ICurrentAppWithConsumables WAPST_ICurrentAppWithConsumables;
typedef struct WAPST_IProductListingWithConsumables WAPST_IProductListingWithConsumables;
typedef struct WAPST_IProductPurchaseDisplayPropertiesFactory WAPST_IProductPurchaseDisplayPropertiesFactory;
typedef struct WAPST_LicenseChangedEventHandler WAPST_LicenseChangedEventHandler;
typedef struct WAPST_LicenseInformation WAPST_LicenseInformation;
typedef struct WAPST_ProductListing WAPST_ProductListing;
typedef struct WAPST_ProductPurchaseDisplayProperties WAPST_ProductPurchaseDisplayProperties;
typedef struct WAPST_PurchaseResults WAPST_PurchaseResults;
typedef struct WAPST_UnfulfilledConsumable WAPST_UnfulfilledConsumable;
typedef struct WAPST_CurrentAppSimulator WAPST_CurrentAppSimulator;
typedef struct WAPST_CurrentApp WAPST_CurrentApp;
typedef struct WAPST_ListingInformation WAPST_ListingInformation;
typedef struct WAPST_ICurrentAppSimulatorWithConsumables WAPST_ICurrentAppSimulatorWithConsumables;
typedef struct WAPST_ProductLicense WAPST_ProductLicense;
typedef struct WAPST_ILicenseInformation WAPST_ILicenseInformation;
typedef struct WAPST_IProductListingWithMetadata WAPST_IProductListingWithMetadata;
typedef struct WAPST_IProductListing_2 WAPST_IProductListing_2;
typedef struct WAPST_IProductPurchaseDisplayProperties WAPST_IProductPurchaseDisplayProperties;
typedef struct WAPST_IPurchaseResults WAPST_IPurchaseResults;
typedef struct WAPST_IUnfulfilledConsumable WAPST_IUnfulfilledConsumable;
typedef struct WAPST_IListingInformation WAPST_IListingInformation;
typedef struct WAPST_IListingInformation_2 WAPST_IListingInformation_2;
typedef struct WAPST_IProductLicenseWithFulfillment WAPST_IProductLicenseWithFulfillment;
typedef struct WAPST_IProductListing WAPST_IProductListing;
typedef struct WAPST_IProductLicense WAPST_IProductLicense;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WF_Uri
#define CWINRT_FWD_WF_Uri
typedef struct WF_Uri WF_Uri;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_HSTRING
#define CWINRT_FWD_WF_IAsyncOperation_HSTRING
typedef struct WF_IAsyncOperation_HSTRING WF_IAsyncOperation_HSTRING;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WAPST_ListingInformation
#define CWINRT_FWD_WF_IAsyncOperation_WAPST_ListingInformation
typedef struct WF_IAsyncOperation_WAPST_ListingInformation WF_IAsyncOperation_WAPST_ListingInformation;
#endif
#ifndef CWINRT_FWD_WS_StorageFile
#define CWINRT_FWD_WS_StorageFile
typedef struct WS_StorageFile WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WF_IAsyncAction
#define CWINRT_FWD_WF_IAsyncAction
typedef struct WF_IAsyncAction WF_IAsyncAction;
#endif
#ifndef CWINRT_FWD_WFOCO_IIterable_HSTRING
#define CWINRT_FWD_WFOCO_IIterable_HSTRING
typedef struct WFOCO_IIterable_HSTRING WFOCO_IIterable_HSTRING;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WAPST_FulfillmentResult
#define CWINRT_FWD_WF_IAsyncOperation_WAPST_FulfillmentResult
typedef struct WF_IAsyncOperation_WAPST_FulfillmentResult WF_IAsyncOperation_WAPST_FulfillmentResult;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WAPST_PurchaseResults
#define CWINRT_FWD_WF_IAsyncOperation_WAPST_PurchaseResults
typedef struct WF_IAsyncOperation_WAPST_PurchaseResults WF_IAsyncOperation_WAPST_PurchaseResults;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable
#define CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable
typedef struct WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable;
#endif
#ifndef CWINRT_FWD_WFOCO_IMapView_HSTRING_WAPST_ProductLicense
#define CWINRT_FWD_WFOCO_IMapView_HSTRING_WAPST_ProductLicense
typedef struct WFOCO_IMapView_HSTRING_WAPST_ProductLicense WFOCO_IMapView_HSTRING_WAPST_ProductLicense;
#endif
#ifndef CWINRT_FWD_WF_DateTime
#define CWINRT_FWD_WF_DateTime
typedef struct WF_DateTime WF_DateTime;
#endif
#ifndef CWINRT_FWD_WFOCO_IMapView_HSTRING_WAPST_ProductListing
#define CWINRT_FWD_WFOCO_IMapView_HSTRING_WAPST_ProductListing
typedef struct WFOCO_IMapView_HSTRING_WAPST_ProductListing WFOCO_IMapView_HSTRING_WAPST_ProductListing;
#endif

#ifndef CWINRT_FWD_WAPST_FulfillmentResult
#define CWINRT_FWD_WAPST_FulfillmentResult
typedef enum WAPST_FulfillmentResult {
    WAPST_FulfillmentResult_Succeeded = 0,
    WAPST_FulfillmentResult_NothingToFulfill = 1,
    WAPST_FulfillmentResult_PurchasePending = 2,
    WAPST_FulfillmentResult_PurchaseReverted = 3,
    WAPST_FulfillmentResult_ServerError = 4
} WAPST_FulfillmentResult;
#endif

#ifndef CWINRT_FWD_WAPST_ProductPurchaseStatus
#define CWINRT_FWD_WAPST_ProductPurchaseStatus
typedef enum WAPST_ProductPurchaseStatus {
    WAPST_ProductPurchaseStatus_Succeeded = 0,
    WAPST_ProductPurchaseStatus_AlreadyPurchased = 1,
    WAPST_ProductPurchaseStatus_NotFulfilled = 2,
    WAPST_ProductPurchaseStatus_NotPurchased = 3
} WAPST_ProductPurchaseStatus;
#endif

#ifndef CWINRT_FWD_WAPST_ProductType
#define CWINRT_FWD_WAPST_ProductType
typedef enum WAPST_ProductType {
    WAPST_ProductType_Unknown = 0,
    WAPST_ProductType_Durable = 1,
    WAPST_ProductType_Consumable = 2
} WAPST_ProductType;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentApp
#define CWINRT_IIDDEF_WAPST_ICurrentApp
static const IID CWINRT_IID_WAPST_ICurrentApp CWINRT_MAYBE_UNUSED = { 0xD52DC065, 0xDA3F, 0x4685, { 0x99, 0x5E, 0x9B, 0x48, 0x2E, 0xB5, 0xE6, 0x03 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentApp2Statics
#define CWINRT_IIDDEF_WAPST_ICurrentApp2Statics
static const IID CWINRT_IID_WAPST_ICurrentApp2Statics CWINRT_MAYBE_UNUSED = { 0xDF4E6E2D, 0x3171, 0x4AD3, { 0x86, 0x14, 0x2C, 0x61, 0x24, 0x43, 0x73, 0xCB } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppSimulator
#define CWINRT_IIDDEF_WAPST_ICurrentAppSimulator
static const IID CWINRT_IID_WAPST_ICurrentAppSimulator CWINRT_MAYBE_UNUSED = { 0xF17F9DB1, 0x74CD, 0x4787, { 0x97, 0x87, 0x19, 0x86, 0x6E, 0x9A, 0x55, 0x59 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorStaticsWithFiltering
#define CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorStaticsWithFiltering
static const IID CWINRT_IID_WAPST_ICurrentAppSimulatorStaticsWithFiltering CWINRT_MAYBE_UNUSED = { 0x617E70E2, 0xF86F, 0x4B54, { 0x96, 0x66, 0xDD, 0xE2, 0x85, 0x09, 0x2C, 0x68 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorWithCampaignId
#define CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorWithCampaignId
static const IID CWINRT_IID_WAPST_ICurrentAppSimulatorWithCampaignId CWINRT_MAYBE_UNUSED = { 0x84678A43, 0xDF00, 0x4672, { 0xA4, 0x3F, 0xB2, 0x5B, 0x14, 0x41, 0xCF, 0xCF } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppStaticsWithFiltering
#define CWINRT_IIDDEF_WAPST_ICurrentAppStaticsWithFiltering
static const IID CWINRT_IID_WAPST_ICurrentAppStaticsWithFiltering CWINRT_MAYBE_UNUSED = { 0xD36D6542, 0x9085, 0x438E, { 0x97, 0xBA, 0xA2, 0x5C, 0x97, 0x6B, 0xE2, 0xFD } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppWithCampaignId
#define CWINRT_IIDDEF_WAPST_ICurrentAppWithCampaignId
static const IID CWINRT_IID_WAPST_ICurrentAppWithCampaignId CWINRT_MAYBE_UNUSED = { 0x312F4CD0, 0x36C1, 0x44A6, { 0xB3, 0x2B, 0x43, 0x2D, 0x60, 0x8E, 0x4D, 0xD6 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppWithConsumables
#define CWINRT_IIDDEF_WAPST_ICurrentAppWithConsumables
static const IID CWINRT_IID_WAPST_ICurrentAppWithConsumables CWINRT_MAYBE_UNUSED = { 0x844E0071, 0x9E4F, 0x4F79, { 0x99, 0x5A, 0x5F, 0x91, 0x17, 0x2E, 0x6C, 0xEF } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductListingWithConsumables
#define CWINRT_IIDDEF_WAPST_IProductListingWithConsumables
static const IID CWINRT_IID_WAPST_IProductListingWithConsumables CWINRT_MAYBE_UNUSED = { 0xEB9E9790, 0x8F6B, 0x481F, { 0x93, 0xA7, 0x5C, 0x3A, 0x63, 0x06, 0x81, 0x49 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductPurchaseDisplayPropertiesFactory
#define CWINRT_IIDDEF_WAPST_IProductPurchaseDisplayPropertiesFactory
static const IID CWINRT_IID_WAPST_IProductPurchaseDisplayPropertiesFactory CWINRT_MAYBE_UNUSED = { 0x6F491DF4, 0x32D6, 0x4B40, { 0xB4, 0x74, 0xB8, 0x30, 0x38, 0xA4, 0xD9, 0xCF } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_LicenseChangedEventHandler
#define CWINRT_IIDDEF_WAPST_LicenseChangedEventHandler
static const IID CWINRT_IID_WAPST_LicenseChangedEventHandler CWINRT_MAYBE_UNUSED = { 0xD4A50255, 0x1369, 0x4C36, { 0x83, 0x2F, 0x6F, 0x2D, 0x88, 0xE3, 0x65, 0x9B } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorWithConsumables
#define CWINRT_IIDDEF_WAPST_ICurrentAppSimulatorWithConsumables
static const IID CWINRT_IID_WAPST_ICurrentAppSimulatorWithConsumables CWINRT_MAYBE_UNUSED = { 0x4E51F0AB, 0x20E7, 0x4412, { 0x9B, 0x85, 0x59, 0xBB, 0x78, 0x38, 0x86, 0x67 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_ILicenseInformation
#define CWINRT_IIDDEF_WAPST_ILicenseInformation
static const IID CWINRT_IID_WAPST_ILicenseInformation CWINRT_MAYBE_UNUSED = { 0x8EB7DC30, 0xF170, 0x4ED5, { 0x8E, 0x21, 0x15, 0x16, 0xDA, 0x3F, 0xD3, 0x67 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductListingWithMetadata
#define CWINRT_IIDDEF_WAPST_IProductListingWithMetadata
static const IID CWINRT_IID_WAPST_IProductListingWithMetadata CWINRT_MAYBE_UNUSED = { 0x124DA567, 0x23F8, 0x423E, { 0x95, 0x32, 0x18, 0x99, 0x43, 0xC4, 0x0A, 0xCE } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductListing_2
#define CWINRT_IIDDEF_WAPST_IProductListing_2
static const IID CWINRT_IID_WAPST_IProductListing_2 CWINRT_MAYBE_UNUSED = { 0xF89E290F, 0x73FE, 0x494D, { 0xA9, 0x39, 0x08, 0xA9, 0xB2, 0x49, 0x5A, 0xBE } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductPurchaseDisplayProperties
#define CWINRT_IIDDEF_WAPST_IProductPurchaseDisplayProperties
static const IID CWINRT_IID_WAPST_IProductPurchaseDisplayProperties CWINRT_MAYBE_UNUSED = { 0xD70B7420, 0xBC92, 0x401B, { 0xA8, 0x09, 0xC9, 0xB2, 0xE5, 0xDB, 0xBD, 0xAF } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IPurchaseResults
#define CWINRT_IIDDEF_WAPST_IPurchaseResults
static const IID CWINRT_IID_WAPST_IPurchaseResults CWINRT_MAYBE_UNUSED = { 0xED50B37E, 0x8656, 0x4F65, { 0xB8, 0xC8, 0xAC, 0x7E, 0x0C, 0xB1, 0xA1, 0xC2 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IUnfulfilledConsumable
#define CWINRT_IIDDEF_WAPST_IUnfulfilledConsumable
static const IID CWINRT_IID_WAPST_IUnfulfilledConsumable CWINRT_MAYBE_UNUSED = { 0x2DF7FBBB, 0x1CDD, 0x4CB8, { 0xA0, 0x14, 0x7B, 0x9C, 0xF8, 0x98, 0x69, 0x27 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IListingInformation
#define CWINRT_IIDDEF_WAPST_IListingInformation
static const IID CWINRT_IID_WAPST_IListingInformation CWINRT_MAYBE_UNUSED = { 0x588B4ABF, 0xBC74, 0x4383, { 0xB7, 0x8C, 0x99, 0x60, 0x63, 0x23, 0xDE, 0xCE } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IListingInformation_2
#define CWINRT_IIDDEF_WAPST_IListingInformation_2
static const IID CWINRT_IID_WAPST_IListingInformation_2 CWINRT_MAYBE_UNUSED = { 0xC0FD2C1D, 0xB30E, 0x4384, { 0x84, 0xEA, 0x72, 0xFE, 0xFA, 0x82, 0x22, 0x3E } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductLicenseWithFulfillment
#define CWINRT_IIDDEF_WAPST_IProductLicenseWithFulfillment
static const IID CWINRT_IID_WAPST_IProductLicenseWithFulfillment CWINRT_MAYBE_UNUSED = { 0xFC535C8A, 0xF667, 0x40F3, { 0xBA, 0x3C, 0x04, 0x5A, 0x63, 0xAB, 0xB3, 0xAC } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductListing
#define CWINRT_IIDDEF_WAPST_IProductListing
static const IID CWINRT_IID_WAPST_IProductListing CWINRT_MAYBE_UNUSED = { 0x45A7D6AD, 0xC750, 0x4D9C, { 0x94, 0x7C, 0xB0, 0x0D, 0xCB, 0xF9, 0xE9, 0xC2 } };
#endif
#ifndef CWINRT_IIDDEF_WAPST_IProductLicense
#define CWINRT_IIDDEF_WAPST_IProductLicense
static const IID CWINRT_IID_WAPST_IProductLicense CWINRT_MAYBE_UNUSED = { 0x363308C7, 0x2BCF, 0x4C0E, { 0x8F, 0x2F, 0xE8, 0x08, 0xAA, 0xA8, 0xF9, 0x9D } };
#endif

/* Methods */

/* Windows.ApplicationModel.Store.ICurrentApp */
/* Windows.ApplicationModel.Store.ICurrentApp2Statics */
/* Windows.ApplicationModel.Store.ICurrentApp2Statics.GetCustomerPurchaseIdAsync(serviceTicket, publisherUserId) */
HRESULT wapst_current_app2_statics_get_customer_purchase_id_async(WAPST_ICurrentApp2Statics *self, cwinrt_hstring serviceTicket, cwinrt_hstring publisherUserId, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.ICurrentApp2Statics.GetCustomerCollectionsIdAsync(serviceTicket, publisherUserId) */
HRESULT wapst_current_app2_statics_get_customer_collections_id_async(WAPST_ICurrentApp2Statics *self, cwinrt_hstring serviceTicket, cwinrt_hstring publisherUserId, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulator */
/* Windows.ApplicationModel.Store.ICurrentAppSimulatorStaticsWithFiltering */
/* Windows.ApplicationModel.Store.ICurrentAppSimulatorStaticsWithFiltering.LoadListingInformationByProductIdsAsync(productIds) */
HRESULT wapst_current_app_simulator_statics_with_filtering_load_listing_information_by_product_ids_async(WAPST_ICurrentAppSimulatorStaticsWithFiltering *self, WFOCO_IIterable_HSTRING* productIds, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorStaticsWithFiltering.LoadListingInformationByKeywordsAsync(keywords) */
HRESULT wapst_current_app_simulator_statics_with_filtering_load_listing_information_by_keywords_async(WAPST_ICurrentAppSimulatorStaticsWithFiltering *self, WFOCO_IIterable_HSTRING* keywords, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithCampaignId */
/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithCampaignId.GetAppPurchaseCampaignIdAsync() */
HRESULT wapst_current_app_simulator_with_campaign_id_get_app_purchase_campaign_id_async(WAPST_ICurrentAppSimulatorWithCampaignId *self, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.ICurrentAppStaticsWithFiltering */
/* Windows.ApplicationModel.Store.ICurrentAppStaticsWithFiltering.LoadListingInformationByProductIdsAsync(productIds) */
HRESULT wapst_current_app_statics_with_filtering_load_listing_information_by_product_ids_async(WAPST_ICurrentAppStaticsWithFiltering *self, WFOCO_IIterable_HSTRING* productIds, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.ICurrentAppStaticsWithFiltering.LoadListingInformationByKeywordsAsync(keywords) */
HRESULT wapst_current_app_statics_with_filtering_load_listing_information_by_keywords_async(WAPST_ICurrentAppStaticsWithFiltering *self, WFOCO_IIterable_HSTRING* keywords, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.ICurrentAppStaticsWithFiltering.ReportProductFulfillment(productId) */
HRESULT wapst_current_app_statics_with_filtering_report_product_fulfillment(WAPST_ICurrentAppStaticsWithFiltering *self, cwinrt_hstring productId);

/* Windows.ApplicationModel.Store.ICurrentAppWithCampaignId */
/* Windows.ApplicationModel.Store.ICurrentAppWithCampaignId.GetAppPurchaseCampaignIdAsync() */
HRESULT wapst_current_app_with_campaign_id_get_app_purchase_campaign_id_async(WAPST_ICurrentAppWithCampaignId *self, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.ICurrentAppWithConsumables */
/* Windows.ApplicationModel.Store.ICurrentAppWithConsumables.ReportConsumableFulfillmentAsync(productId, transactionId) */
HRESULT wapst_current_app_with_consumables_report_consumable_fulfillment_async(WAPST_ICurrentAppWithConsumables *self, cwinrt_hstring productId, GUID transactionId, WF_IAsyncOperation_WAPST_FulfillmentResult** out);

/* Windows.ApplicationModel.Store.ICurrentAppWithConsumables.RequestProductPurchaseAsync(productId) */
HRESULT wapst_current_app_with_consumables_request_product_purchase_async(WAPST_ICurrentAppWithConsumables *self, cwinrt_hstring productId, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.ICurrentAppWithConsumables.RequestProductPurchaseAsync(productId, offerId, displayProperties) */
HRESULT wapst_current_app_with_consumables_request_product_purchase_async_str_str_p_p(WAPST_ICurrentAppWithConsumables *self, cwinrt_hstring productId, cwinrt_hstring offerId, WAPST_ProductPurchaseDisplayProperties* displayProperties, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.ICurrentAppWithConsumables.GetUnfulfilledConsumablesAsync() */
HRESULT wapst_current_app_with_consumables_get_unfulfilled_consumables_async(WAPST_ICurrentAppWithConsumables *self, WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable** out);

/* Windows.ApplicationModel.Store.IProductListingWithConsumables */
/* Windows.ApplicationModel.Store.IProductListingWithConsumables.get_ProductType() */
HRESULT wapst_product_listing_with_consumables_get__product_type(WAPST_IProductListingWithConsumables *self, WAPST_ProductType *value);

/* Windows.ApplicationModel.Store.IProductPurchaseDisplayPropertiesFactory */
/* Windows.ApplicationModel.Store.IProductPurchaseDisplayPropertiesFactory.CreateProductPurchaseDisplayProperties(name) */
HRESULT wapst_product_purchase_display_properties_factory_create_product_purchase_display_properties(WAPST_IProductPurchaseDisplayPropertiesFactory *self, cwinrt_hstring name, WAPST_ProductPurchaseDisplayProperties** out);

/* Windows.ApplicationModel.Store.LicenseChangedEventHandler */
/* Windows.ApplicationModel.Store.LicenseChangedEventHandler.Invoke() */
HRESULT wapst_license_changed_event_handler_invoke(WAPST_LicenseChangedEventHandler *self);

/* activate Windows.ApplicationModel.Store.LicenseInformation */
HRESULT wapst_license_information_new(WAPST_LicenseInformation **out);

/* Windows.ApplicationModel.Store.LicenseInformation */
/* Windows.ApplicationModel.Store.LicenseInformation.get_ProductLicenses() */
HRESULT wapst_license_information_get__product_licenses(WAPST_LicenseInformation *self, WFOCO_IMapView_HSTRING_WAPST_ProductLicense** value);

/* Windows.ApplicationModel.Store.LicenseInformation.get_IsActive() */
HRESULT wapst_license_information_get__is_active(WAPST_LicenseInformation *self, BOOL *value);

/* Windows.ApplicationModel.Store.LicenseInformation.get_IsTrial() */
HRESULT wapst_license_information_get__is_trial(WAPST_LicenseInformation *self, BOOL *value);

/* Windows.ApplicationModel.Store.LicenseInformation.get_ExpirationDate() */
HRESULT wapst_license_information_get__expiration_date(WAPST_LicenseInformation *self, WF_DateTime *value);

/* Event subscriptions (on_/off_) */
#include <cwinrt/event.h>

cwinrt_token wapst_license_information_on_license_changed(WAPST_LicenseInformation *self, cwinrt_event_fn fn, void *ctx);
void wapst_license_information_off_license_changed(WAPST_LicenseInformation *self, cwinrt_token token);

/* activate Windows.ApplicationModel.Store.ProductListing */
HRESULT wapst_product_listing_new(WAPST_ProductListing **out);

/* Windows.ApplicationModel.Store.ProductListing */
/* Windows.ApplicationModel.Store.ProductListing.get_ProductId() */
HRESULT wapst_product_listing_get__product_id(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_FormattedPrice() */
HRESULT wapst_product_listing_get__formatted_price(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_Name() */
HRESULT wapst_product_listing_get__name(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_Description() */
HRESULT wapst_product_listing_get__description(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_Keywords() */
HRESULT wapst_product_listing_get__keywords(WAPST_ProductListing *self, WFOCO_IIterable_HSTRING** value);

/* Windows.ApplicationModel.Store.ProductListing.get_ProductType() */
HRESULT wapst_product_listing_get__product_type(WAPST_ProductListing *self, WAPST_ProductType *value);

/* Windows.ApplicationModel.Store.ProductListing.get_Tag() */
HRESULT wapst_product_listing_get__tag(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_ImageUri() */
HRESULT wapst_product_listing_get__image_uri(WAPST_ProductListing *self, WF_Uri** value);

/* Windows.ApplicationModel.Store.ProductListing.get_FormattedBasePrice() */
HRESULT wapst_product_listing_get__formatted_base_price(WAPST_ProductListing *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductListing.get_SaleEndDate() */
HRESULT wapst_product_listing_get__sale_end_date(WAPST_ProductListing *self, WF_DateTime *value);

/* Windows.ApplicationModel.Store.ProductListing.get_IsOnSale() */
HRESULT wapst_product_listing_get__is_on_sale(WAPST_ProductListing *self, BOOL *value);

/* Windows.ApplicationModel.Store.ProductListing.get_CurrencyCode() */
HRESULT wapst_product_listing_get__currency_code(WAPST_ProductListing *self, cwinrt_hstring *value);

/* activate Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties */
HRESULT wapst_product_purchase_display_properties_new(WAPST_ProductPurchaseDisplayProperties **out);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties */
/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.get_Name() */
HRESULT wapst_product_purchase_display_properties_get__name(WAPST_ProductPurchaseDisplayProperties *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.put_Name() */
HRESULT wapst_product_purchase_display_properties_put__name(WAPST_ProductPurchaseDisplayProperties *self, cwinrt_hstring value);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.get_Description() */
HRESULT wapst_product_purchase_display_properties_get__description(WAPST_ProductPurchaseDisplayProperties *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.put_Description() */
HRESULT wapst_product_purchase_display_properties_put__description(WAPST_ProductPurchaseDisplayProperties *self, cwinrt_hstring value);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.get_Image() */
HRESULT wapst_product_purchase_display_properties_get__image(WAPST_ProductPurchaseDisplayProperties *self, WF_Uri** value);

/* Windows.ApplicationModel.Store.ProductPurchaseDisplayProperties.put_Image() */
HRESULT wapst_product_purchase_display_properties_put__image(WAPST_ProductPurchaseDisplayProperties *self, WF_Uri* value);

/* activate Windows.ApplicationModel.Store.PurchaseResults */
HRESULT wapst_purchase_results_new(WAPST_PurchaseResults **out);

/* Windows.ApplicationModel.Store.PurchaseResults */
/* Windows.ApplicationModel.Store.PurchaseResults.get_Status() */
HRESULT wapst_purchase_results_get__status(WAPST_PurchaseResults *self, WAPST_ProductPurchaseStatus *value);

/* Windows.ApplicationModel.Store.PurchaseResults.get_TransactionId() */
HRESULT wapst_purchase_results_get__transaction_id(WAPST_PurchaseResults *self, GUID *value);

/* Windows.ApplicationModel.Store.PurchaseResults.get_ReceiptXml() */
HRESULT wapst_purchase_results_get__receipt_xml(WAPST_PurchaseResults *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.PurchaseResults.get_OfferId() */
HRESULT wapst_purchase_results_get__offer_id(WAPST_PurchaseResults *self, cwinrt_hstring *value);

/* activate Windows.ApplicationModel.Store.UnfulfilledConsumable */
HRESULT wapst_unfulfilled_consumable_new(WAPST_UnfulfilledConsumable **out);

/* Windows.ApplicationModel.Store.UnfulfilledConsumable */
/* Windows.ApplicationModel.Store.UnfulfilledConsumable.get_ProductId() */
HRESULT wapst_unfulfilled_consumable_get__product_id(WAPST_UnfulfilledConsumable *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.UnfulfilledConsumable.get_TransactionId() */
HRESULT wapst_unfulfilled_consumable_get__transaction_id(WAPST_UnfulfilledConsumable *self, GUID *value);

/* Windows.ApplicationModel.Store.UnfulfilledConsumable.get_OfferId() */
HRESULT wapst_unfulfilled_consumable_get__offer_id(WAPST_UnfulfilledConsumable *self, cwinrt_hstring *value);

/* activate Windows.ApplicationModel.Store.CurrentAppSimulator */
HRESULT wapst_current_app_simulator_new(WAPST_CurrentAppSimulator **out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator */
/* Windows.ApplicationModel.Store.CurrentAppSimulator.GetAppPurchaseCampaignIdAsync() */
HRESULT wapst_current_app_simulator_get_app_purchase_campaign_id_async(WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.LoadListingInformationByProductIdsAsync(productIds) */
HRESULT wapst_current_app_simulator_load_listing_information_by_product_ids_async(WFOCO_IIterable_HSTRING* productIds, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.LoadListingInformationByKeywordsAsync(keywords) */
HRESULT wapst_current_app_simulator_load_listing_information_by_keywords_async(WFOCO_IIterable_HSTRING* keywords, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.ReportConsumableFulfillmentAsync(productId, transactionId) */
HRESULT wapst_current_app_simulator_report_consumable_fulfillment_async(cwinrt_hstring productId, GUID transactionId, WF_IAsyncOperation_WAPST_FulfillmentResult** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.RequestProductPurchaseAsync(productId) */
HRESULT wapst_current_app_simulator_request_product_purchase_async(cwinrt_hstring productId, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.RequestProductPurchaseAsync(productId, offerId, displayProperties) */
HRESULT wapst_current_app_simulator_request_product_purchase_async_str_str_p_p(cwinrt_hstring productId, cwinrt_hstring offerId, WAPST_ProductPurchaseDisplayProperties* displayProperties, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.GetUnfulfilledConsumablesAsync() */
HRESULT wapst_current_app_simulator_get_unfulfilled_consumables_async(WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.get_LicenseInformation() */
HRESULT wapst_current_app_simulator_get__license_information(WAPST_LicenseInformation** value);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.get_LinkUri() */
HRESULT wapst_current_app_simulator_get__link_uri(WF_Uri** value);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.get_AppId() */
HRESULT wapst_current_app_simulator_get__app_id(GUID *value);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.RequestAppPurchaseAsync(includeReceipt) */
HRESULT wapst_current_app_simulator_request_app_purchase_async(BOOL includeReceipt, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.RequestProductPurchaseAsync(productId, includeReceipt) */
HRESULT wapst_current_app_simulator_request_product_purchase_async_str_b_p(cwinrt_hstring productId, BOOL includeReceipt, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.LoadListingInformationAsync() */
HRESULT wapst_current_app_simulator_load_listing_information_async(WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.GetAppReceiptAsync() */
HRESULT wapst_current_app_simulator_get_app_receipt_async(WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.GetProductReceiptAsync(productId) */
HRESULT wapst_current_app_simulator_get_product_receipt_async(cwinrt_hstring productId, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentAppSimulator.ReloadSimulatorAsync(simulatorSettingsFile) */
HRESULT wapst_current_app_simulator_reload_simulator_async(WS_StorageFile* simulatorSettingsFile, WF_IAsyncAction** out);

/* activate Windows.ApplicationModel.Store.CurrentApp */
HRESULT wapst_current_app_new(WAPST_CurrentApp **out);

/* Windows.ApplicationModel.Store.CurrentApp */
/* Windows.ApplicationModel.Store.CurrentApp.GetCustomerPurchaseIdAsync(serviceTicket, publisherUserId) */
HRESULT wapst_current_app_get_customer_purchase_id_async(cwinrt_hstring serviceTicket, cwinrt_hstring publisherUserId, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.GetCustomerCollectionsIdAsync(serviceTicket, publisherUserId) */
HRESULT wapst_current_app_get_customer_collections_id_async(cwinrt_hstring serviceTicket, cwinrt_hstring publisherUserId, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.GetAppPurchaseCampaignIdAsync() */
HRESULT wapst_current_app_get_app_purchase_campaign_id_async(WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.LoadListingInformationByProductIdsAsync(productIds) */
HRESULT wapst_current_app_load_listing_information_by_product_ids_async(WFOCO_IIterable_HSTRING* productIds, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentApp.LoadListingInformationByKeywordsAsync(keywords) */
HRESULT wapst_current_app_load_listing_information_by_keywords_async(WFOCO_IIterable_HSTRING* keywords, WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentApp.ReportProductFulfillment(productId) */
HRESULT wapst_current_app_report_product_fulfillment(cwinrt_hstring productId);

/* Windows.ApplicationModel.Store.CurrentApp.ReportConsumableFulfillmentAsync(productId, transactionId) */
HRESULT wapst_current_app_report_consumable_fulfillment_async(cwinrt_hstring productId, GUID transactionId, WF_IAsyncOperation_WAPST_FulfillmentResult** out);

/* Windows.ApplicationModel.Store.CurrentApp.RequestProductPurchaseAsync(productId) */
HRESULT wapst_current_app_request_product_purchase_async(cwinrt_hstring productId, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.CurrentApp.RequestProductPurchaseAsync(productId, offerId, displayProperties) */
HRESULT wapst_current_app_request_product_purchase_async_str_str_p_p(cwinrt_hstring productId, cwinrt_hstring offerId, WAPST_ProductPurchaseDisplayProperties* displayProperties, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.CurrentApp.GetUnfulfilledConsumablesAsync() */
HRESULT wapst_current_app_get_unfulfilled_consumables_async(WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable** out);

/* Windows.ApplicationModel.Store.CurrentApp.get_LicenseInformation() */
HRESULT wapst_current_app_get__license_information(WAPST_LicenseInformation** value);

/* Windows.ApplicationModel.Store.CurrentApp.get_LinkUri() */
HRESULT wapst_current_app_get__link_uri(WF_Uri** value);

/* Windows.ApplicationModel.Store.CurrentApp.get_AppId() */
HRESULT wapst_current_app_get__app_id(GUID *value);

/* Windows.ApplicationModel.Store.CurrentApp.RequestAppPurchaseAsync(includeReceipt) */
HRESULT wapst_current_app_request_app_purchase_async(BOOL includeReceipt, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.RequestProductPurchaseAsync(productId, includeReceipt) */
HRESULT wapst_current_app_request_product_purchase_async_str_b_p(cwinrt_hstring productId, BOOL includeReceipt, WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.LoadListingInformationAsync() */
HRESULT wapst_current_app_load_listing_information_async(WF_IAsyncOperation_WAPST_ListingInformation** out);

/* Windows.ApplicationModel.Store.CurrentApp.GetAppReceiptAsync() */
HRESULT wapst_current_app_get_app_receipt_async(WF_IAsyncOperation_HSTRING** out);

/* Windows.ApplicationModel.Store.CurrentApp.GetProductReceiptAsync(productId) */
HRESULT wapst_current_app_get_product_receipt_async(cwinrt_hstring productId, WF_IAsyncOperation_HSTRING** out);

/* activate Windows.ApplicationModel.Store.ListingInformation */
HRESULT wapst_listing_information_new(WAPST_ListingInformation **out);

/* Windows.ApplicationModel.Store.ListingInformation */
/* Windows.ApplicationModel.Store.ListingInformation.get_CurrentMarket() */
HRESULT wapst_listing_information_get__current_market(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_Description() */
HRESULT wapst_listing_information_get__description(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_ProductListings() */
HRESULT wapst_listing_information_get__product_listings(WAPST_ListingInformation *self, WFOCO_IMapView_HSTRING_WAPST_ProductListing** value);

/* Windows.ApplicationModel.Store.ListingInformation.get_FormattedPrice() */
HRESULT wapst_listing_information_get__formatted_price(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_Name() */
HRESULT wapst_listing_information_get__name(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_AgeRating() */
HRESULT wapst_listing_information_get__age_rating(WAPST_ListingInformation *self, uint32_t *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_FormattedBasePrice() */
HRESULT wapst_listing_information_get__formatted_base_price(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_SaleEndDate() */
HRESULT wapst_listing_information_get__sale_end_date(WAPST_ListingInformation *self, WF_DateTime *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_IsOnSale() */
HRESULT wapst_listing_information_get__is_on_sale(WAPST_ListingInformation *self, BOOL *value);

/* Windows.ApplicationModel.Store.ListingInformation.get_CurrencyCode() */
HRESULT wapst_listing_information_get__currency_code(WAPST_ListingInformation *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithConsumables */
/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithConsumables.ReportConsumableFulfillmentAsync(productId, transactionId) */
HRESULT wapst_current_app_simulator_with_consumables_report_consumable_fulfillment_async(WAPST_ICurrentAppSimulatorWithConsumables *self, cwinrt_hstring productId, GUID transactionId, WF_IAsyncOperation_WAPST_FulfillmentResult** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithConsumables.RequestProductPurchaseAsync(productId) */
HRESULT wapst_current_app_simulator_with_consumables_request_product_purchase_async(WAPST_ICurrentAppSimulatorWithConsumables *self, cwinrt_hstring productId, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithConsumables.RequestProductPurchaseAsync(productId, offerId, displayProperties) */
HRESULT wapst_current_app_simulator_with_consumables_request_product_purchase_async_str_str_p_p(WAPST_ICurrentAppSimulatorWithConsumables *self, cwinrt_hstring productId, cwinrt_hstring offerId, WAPST_ProductPurchaseDisplayProperties* displayProperties, WF_IAsyncOperation_WAPST_PurchaseResults** out);

/* Windows.ApplicationModel.Store.ICurrentAppSimulatorWithConsumables.GetUnfulfilledConsumablesAsync() */
HRESULT wapst_current_app_simulator_with_consumables_get_unfulfilled_consumables_async(WAPST_ICurrentAppSimulatorWithConsumables *self, WF_IAsyncOperation_WFOCO_IVectorView_WAPST_UnfulfilledConsumable** out);

/* activate Windows.ApplicationModel.Store.ProductLicense */
HRESULT wapst_product_license_new(WAPST_ProductLicense **out);

/* Windows.ApplicationModel.Store.ProductLicense */
/* Windows.ApplicationModel.Store.ProductLicense.get_ProductId() */
HRESULT wapst_product_license_get__product_id(WAPST_ProductLicense *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.ProductLicense.get_IsActive() */
HRESULT wapst_product_license_get__is_active(WAPST_ProductLicense *self, BOOL *value);

/* Windows.ApplicationModel.Store.ProductLicense.get_ExpirationDate() */
HRESULT wapst_product_license_get__expiration_date(WAPST_ProductLicense *self, WF_DateTime *value);

/* Windows.ApplicationModel.Store.ProductLicense.get_IsConsumable() */
HRESULT wapst_product_license_get__is_consumable(WAPST_ProductLicense *self, BOOL *value);

/* Windows.ApplicationModel.Store.ILicenseInformation */
/* Windows.ApplicationModel.Store.IProductListingWithMetadata */
/* Windows.ApplicationModel.Store.IProductListingWithMetadata.get_Description() */
HRESULT wapst_product_listing_with_metadata_get__description(WAPST_IProductListingWithMetadata *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IProductListingWithMetadata.get_Keywords() */
HRESULT wapst_product_listing_with_metadata_get__keywords(WAPST_IProductListingWithMetadata *self, WFOCO_IIterable_HSTRING** value);

/* Windows.ApplicationModel.Store.IProductListingWithMetadata.get_ProductType() */
HRESULT wapst_product_listing_with_metadata_get__product_type(WAPST_IProductListingWithMetadata *self, WAPST_ProductType *value);

/* Windows.ApplicationModel.Store.IProductListingWithMetadata.get_Tag() */
HRESULT wapst_product_listing_with_metadata_get__tag(WAPST_IProductListingWithMetadata *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IProductListingWithMetadata.get_ImageUri() */
HRESULT wapst_product_listing_with_metadata_get__image_uri(WAPST_IProductListingWithMetadata *self, WF_Uri** value);

/* Windows.ApplicationModel.Store.IProductListing2 */
/* Windows.ApplicationModel.Store.IProductListing2.get_FormattedBasePrice() */
HRESULT wapst_product_listing_2_get__formatted_base_price(WAPST_IProductListing_2 *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IProductListing2.get_SaleEndDate() */
HRESULT wapst_product_listing_2_get__sale_end_date(WAPST_IProductListing_2 *self, WF_DateTime *value);

/* Windows.ApplicationModel.Store.IProductListing2.get_IsOnSale() */
HRESULT wapst_product_listing_2_get__is_on_sale(WAPST_IProductListing_2 *self, BOOL *value);

/* Windows.ApplicationModel.Store.IProductListing2.get_CurrencyCode() */
HRESULT wapst_product_listing_2_get__currency_code(WAPST_IProductListing_2 *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IProductPurchaseDisplayProperties */
/* Windows.ApplicationModel.Store.IPurchaseResults */
/* Windows.ApplicationModel.Store.IUnfulfilledConsumable */
/* Windows.ApplicationModel.Store.IListingInformation */
/* Windows.ApplicationModel.Store.IListingInformation2 */
/* Windows.ApplicationModel.Store.IListingInformation2.get_FormattedBasePrice() */
HRESULT wapst_listing_information_2_get__formatted_base_price(WAPST_IListingInformation_2 *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IListingInformation2.get_SaleEndDate() */
HRESULT wapst_listing_information_2_get__sale_end_date(WAPST_IListingInformation_2 *self, WF_DateTime *value);

/* Windows.ApplicationModel.Store.IListingInformation2.get_IsOnSale() */
HRESULT wapst_listing_information_2_get__is_on_sale(WAPST_IListingInformation_2 *self, BOOL *value);

/* Windows.ApplicationModel.Store.IListingInformation2.get_CurrencyCode() */
HRESULT wapst_listing_information_2_get__currency_code(WAPST_IListingInformation_2 *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.Store.IProductLicenseWithFulfillment */
/* Windows.ApplicationModel.Store.IProductLicenseWithFulfillment.get_IsConsumable() */
HRESULT wapst_product_license_with_fulfillment_get__is_consumable(WAPST_IProductLicenseWithFulfillment *self, BOOL *value);

/* Windows.ApplicationModel.Store.IProductListing */
/* Windows.ApplicationModel.Store.IProductLicense */
#endif /* CWINRT_WINDOWS_APPLICATIONMODEL_STORE_H */
