/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_STORAGE_PICKERS_H
#define CWINRT_WINDOWS_STORAGE_PICKERS_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/Windows.Storage.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WSY_User
#define CWINRT_FWD_WSY_User
typedef struct WSY_User WSY_User;
#endif

/* Types (forward declarations) */
typedef struct WSTPI_IFolderPickerStatics WSTPI_IFolderPickerStatics;
typedef struct WSTPI_FileOpenPicker WSTPI_FileOpenPicker;
typedef struct WSTPI_FilePickerFileTypesOrderedMap WSTPI_FilePickerFileTypesOrderedMap;
typedef struct WSTPI_FilePickerSelectedFilesArray WSTPI_FilePickerSelectedFilesArray;
typedef struct WSTPI_FileSavePicker WSTPI_FileSavePicker;
typedef struct WSTPI_FolderPicker WSTPI_FolderPicker;
typedef struct WSTPI_IFileOpenPickerStatics WSTPI_IFileOpenPickerStatics;
typedef struct WSTPI_IFileOpenPickerStatics_2 WSTPI_IFileOpenPickerStatics_2;
typedef struct WSTPI_IFileSavePickerStatics WSTPI_IFileSavePickerStatics;
typedef struct WSTPI_FileExtensionVector WSTPI_FileExtensionVector;
typedef struct WSTPI_IFileOpenPicker_2 WSTPI_IFileOpenPicker_2;
typedef struct WSTPI_IFileOpenPickerWithOperationId WSTPI_IFileOpenPickerWithOperationId;
typedef struct WSTPI_IFileOpenPicker WSTPI_IFileOpenPicker;
typedef struct WSTPI_IFileOpenPicker_3 WSTPI_IFileOpenPicker_3;
typedef struct WSTPI_IFileSavePicker_2 WSTPI_IFileSavePicker_2;
typedef struct WSTPI_IFileSavePicker_3 WSTPI_IFileSavePicker_3;
typedef struct WSTPI_IFileSavePicker WSTPI_IFileSavePicker;
typedef struct WSTPI_IFileSavePicker_4 WSTPI_IFileSavePicker_4;
typedef struct WSTPI_IFolderPicker_2 WSTPI_IFolderPicker_2;
typedef struct WSTPI_IFolderPicker WSTPI_IFolderPicker;
typedef struct WSTPI_IFolderPicker_3 WSTPI_IFolderPicker_3;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WSY_User
#define CWINRT_FWD_WSY_User
typedef struct WSY_User WSY_User;
#endif
#ifndef CWINRT_FWD_WFOCO_ValueSet
#define CWINRT_FWD_WFOCO_ValueSet
typedef struct WFOCO_ValueSet WFOCO_ValueSet;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WS_StorageFile
#define CWINRT_FWD_WF_IAsyncOperation_WS_StorageFile
typedef struct WF_IAsyncOperation_WS_StorageFile WF_IAsyncOperation_WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WFOCO_IVector_HSTRING
#define CWINRT_FWD_WFOCO_IVector_HSTRING
typedef struct WFOCO_IVector_HSTRING WFOCO_IVector_HSTRING;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WS_StorageFile
#define CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WS_StorageFile
typedef struct WF_IAsyncOperation_WFOCO_IVectorView_WS_StorageFile WF_IAsyncOperation_WFOCO_IVectorView_WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WFOCO_IMapView_HSTRING_WFOCO_IVector_HSTRING
#define CWINRT_FWD_WFOCO_IMapView_HSTRING_WFOCO_IVector_HSTRING
typedef struct WFOCO_IMapView_HSTRING_WFOCO_IVector_HSTRING WFOCO_IMapView_HSTRING_WFOCO_IVector_HSTRING;
#endif
#ifndef CWINRT_FWD_WFOCO_IIterator_WFOCO_IKeyValuePair_HSTRING_WFOCO_IVector_HSTRING
#define CWINRT_FWD_WFOCO_IIterator_WFOCO_IKeyValuePair_HSTRING_WFOCO_IVector_HSTRING
typedef struct WFOCO_IIterator_WFOCO_IKeyValuePair_HSTRING_WFOCO_IVector_HSTRING WFOCO_IIterator_WFOCO_IKeyValuePair_HSTRING_WFOCO_IVector_HSTRING;
#endif
#ifndef CWINRT_FWD_WS_StorageFile
#define CWINRT_FWD_WS_StorageFile
typedef struct WS_StorageFile WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WFOCO_IIterator_WS_StorageFile
#define CWINRT_FWD_WFOCO_IIterator_WS_StorageFile
typedef struct WFOCO_IIterator_WS_StorageFile WFOCO_IIterator_WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WFOCO_IMap_HSTRING_WFOCO_IVector_HSTRING
#define CWINRT_FWD_WFOCO_IMap_HSTRING_WFOCO_IVector_HSTRING
typedef struct WFOCO_IMap_HSTRING_WFOCO_IVector_HSTRING WFOCO_IMap_HSTRING_WFOCO_IVector_HSTRING;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WS_StorageFolder
#define CWINRT_FWD_WF_IAsyncOperation_WS_StorageFolder
typedef struct WF_IAsyncOperation_WS_StorageFolder WF_IAsyncOperation_WS_StorageFolder;
#endif
#ifndef CWINRT_FWD_WFOCO_IVectorView_HSTRING
#define CWINRT_FWD_WFOCO_IVectorView_HSTRING
typedef struct WFOCO_IVectorView_HSTRING WFOCO_IVectorView_HSTRING;
#endif
#ifndef CWINRT_FWD_WFOCO_IIterator_HSTRING
#define CWINRT_FWD_WFOCO_IIterator_HSTRING
typedef struct WFOCO_IIterator_HSTRING WFOCO_IIterator_HSTRING;
#endif

#ifndef CWINRT_FWD_WSTPI_PickerViewMode
#define CWINRT_FWD_WSTPI_PickerViewMode
typedef enum WSTPI_PickerViewMode {
    WSTPI_PickerViewMode_List = 0,
    WSTPI_PickerViewMode_Thumbnail = 1
} WSTPI_PickerViewMode;
#endif

#ifndef CWINRT_FWD_WSTPI_PickerLocationId
#define CWINRT_FWD_WSTPI_PickerLocationId
typedef enum WSTPI_PickerLocationId {
    WSTPI_PickerLocationId_DocumentsLibrary = 0,
    WSTPI_PickerLocationId_ComputerFolder = 1,
    WSTPI_PickerLocationId_Desktop = 2,
    WSTPI_PickerLocationId_Downloads = 3,
    WSTPI_PickerLocationId_HomeGroup = 4,
    WSTPI_PickerLocationId_MusicLibrary = 5,
    WSTPI_PickerLocationId_PicturesLibrary = 6,
    WSTPI_PickerLocationId_VideosLibrary = 7,
    WSTPI_PickerLocationId_Objects3D = 8,
    WSTPI_PickerLocationId_Unspecified = 9
} WSTPI_PickerLocationId;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFolderPickerStatics
#define CWINRT_IIDDEF_WSTPI_IFolderPickerStatics
static const IID CWINRT_IID_WSTPI_IFolderPickerStatics CWINRT_MAYBE_UNUSED = { 0x9BE34740, 0x7CA1, 0x5942, { 0xA3, 0xC8, 0x46, 0xF2, 0x55, 0x1E, 0xCF, 0xF3 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPickerStatics
#define CWINRT_IIDDEF_WSTPI_IFileOpenPickerStatics
static const IID CWINRT_IID_WSTPI_IFileOpenPickerStatics CWINRT_MAYBE_UNUSED = { 0x6821573B, 0x2F02, 0x4833, { 0x96, 0xD4, 0xAB, 0xBF, 0xAD, 0x72, 0xB6, 0x7B } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPickerStatics_2
#define CWINRT_IIDDEF_WSTPI_IFileOpenPickerStatics_2
static const IID CWINRT_IID_WSTPI_IFileOpenPickerStatics_2 CWINRT_MAYBE_UNUSED = { 0xE8917415, 0xEDDD, 0x5C98, { 0xB6, 0xF3, 0x36, 0x6F, 0xDF, 0xCA, 0xD3, 0x92 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileSavePickerStatics
#define CWINRT_IIDDEF_WSTPI_IFileSavePickerStatics
static const IID CWINRT_IID_WSTPI_IFileSavePickerStatics CWINRT_MAYBE_UNUSED = { 0x28E3CF9E, 0x961C, 0x5E2C, { 0xAE, 0xD7, 0xE6, 0x47, 0x37, 0xF4, 0xCE, 0x37 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPicker_2
#define CWINRT_IIDDEF_WSTPI_IFileOpenPicker_2
static const IID CWINRT_IID_WSTPI_IFileOpenPicker_2 CWINRT_MAYBE_UNUSED = { 0x8CEB6CD2, 0xB446, 0x46F7, { 0xB2, 0x65, 0x90, 0xF8, 0xE5, 0x5A, 0xD6, 0x50 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPickerWithOperationId
#define CWINRT_IIDDEF_WSTPI_IFileOpenPickerWithOperationId
static const IID CWINRT_IID_WSTPI_IFileOpenPickerWithOperationId CWINRT_MAYBE_UNUSED = { 0x3F57B569, 0x2522, 0x4CA5, { 0xAA, 0x73, 0xA1, 0x55, 0x09, 0xF1, 0xFC, 0xBF } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPicker
#define CWINRT_IIDDEF_WSTPI_IFileOpenPicker
static const IID CWINRT_IID_WSTPI_IFileOpenPicker CWINRT_MAYBE_UNUSED = { 0x2CA8278A, 0x12C5, 0x4C5F, { 0x89, 0x77, 0x94, 0x54, 0x77, 0x93, 0xC2, 0x41 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileOpenPicker_3
#define CWINRT_IIDDEF_WSTPI_IFileOpenPicker_3
static const IID CWINRT_IID_WSTPI_IFileOpenPicker_3 CWINRT_MAYBE_UNUSED = { 0xD9A5C5B3, 0xC5DC, 0x5B98, { 0xBD, 0x80, 0xA8, 0xD0, 0xCA, 0x05, 0x84, 0xD8 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileSavePicker_2
#define CWINRT_IIDDEF_WSTPI_IFileSavePicker_2
static const IID CWINRT_IID_WSTPI_IFileSavePicker_2 CWINRT_MAYBE_UNUSED = { 0x0EC313A2, 0xD24B, 0x449A, { 0x81, 0x97, 0xE8, 0x91, 0x04, 0xFD, 0x42, 0xCC } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileSavePicker_3
#define CWINRT_IIDDEF_WSTPI_IFileSavePicker_3
static const IID CWINRT_IID_WSTPI_IFileSavePicker_3 CWINRT_MAYBE_UNUSED = { 0x698AEC69, 0xBA3C, 0x4E51, { 0xBD, 0x90, 0x4A, 0xBC, 0xBB, 0xF4, 0xCF, 0xAF } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileSavePicker
#define CWINRT_IIDDEF_WSTPI_IFileSavePicker
static const IID CWINRT_IID_WSTPI_IFileSavePicker CWINRT_MAYBE_UNUSED = { 0x3286FFCB, 0x617F, 0x4CC5, { 0xAF, 0x6A, 0xB3, 0xFD, 0xF2, 0x9A, 0xD1, 0x45 } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFileSavePicker_4
#define CWINRT_IIDDEF_WSTPI_IFileSavePicker_4
static const IID CWINRT_IID_WSTPI_IFileSavePicker_4 CWINRT_MAYBE_UNUSED = { 0xE7D83A5A, 0xDDFA, 0x5DE0, { 0x8B, 0x70, 0xC8, 0x42, 0xC2, 0x19, 0x88, 0xEC } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFolderPicker_2
#define CWINRT_IIDDEF_WSTPI_IFolderPicker_2
static const IID CWINRT_IID_WSTPI_IFolderPicker_2 CWINRT_MAYBE_UNUSED = { 0x8EB3BA97, 0xDC85, 0x4616, { 0xBE, 0x94, 0x96, 0x60, 0x88, 0x1F, 0x2F, 0x5D } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFolderPicker
#define CWINRT_IIDDEF_WSTPI_IFolderPicker
static const IID CWINRT_IID_WSTPI_IFolderPicker CWINRT_MAYBE_UNUSED = { 0x084F7799, 0xF3FB, 0x400A, { 0x99, 0xB1, 0x7B, 0x4A, 0x77, 0x2F, 0xD6, 0x0D } };
#endif
#ifndef CWINRT_IIDDEF_WSTPI_IFolderPicker_3
#define CWINRT_IIDDEF_WSTPI_IFolderPicker_3
static const IID CWINRT_IID_WSTPI_IFolderPicker_3 CWINRT_MAYBE_UNUSED = { 0x673B1E29, 0xD326, 0x53C0, { 0xBD, 0x24, 0xA2, 0x5C, 0x71, 0x4C, 0xEE, 0x36 } };
#endif

/* Methods */

/* Windows.Storage.Pickers.IFolderPickerStatics */
/* Windows.Storage.Pickers.IFolderPickerStatics.CreateForUser(user) */
HRESULT wstpi_folder_picker_statics_create_for_user(WSTPI_IFolderPickerStatics *self, WSY_User* user, WSTPI_FolderPicker** out);

/* activate Windows.Storage.Pickers.FileOpenPicker */
HRESULT wstpi_file_open_picker_new(WSTPI_FileOpenPicker **out);

/* Windows.Storage.Pickers.FileOpenPicker */
/* Windows.Storage.Pickers.FileOpenPicker.get_ContinuationData() */
HRESULT wstpi_file_open_picker_get__continuation_data(WSTPI_FileOpenPicker *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.FileOpenPicker.PickSingleFileAndContinue() */
HRESULT wstpi_file_open_picker_pick_single_file_and_continue(WSTPI_FileOpenPicker *self);

/* Windows.Storage.Pickers.FileOpenPicker.PickMultipleFilesAndContinue() */
HRESULT wstpi_file_open_picker_pick_multiple_files_and_continue(WSTPI_FileOpenPicker *self);

/* Windows.Storage.Pickers.FileOpenPicker.PickSingleFileAsync(pickerOperationId) */
HRESULT wstpi_file_open_picker_pick_single_file_async_str_p(WSTPI_FileOpenPicker *self, cwinrt_hstring pickerOperationId, WF_IAsyncOperation_WS_StorageFile** out);

/* Windows.Storage.Pickers.FileOpenPicker.get_ViewMode() */
HRESULT wstpi_file_open_picker_get__view_mode(WSTPI_FileOpenPicker *self, WSTPI_PickerViewMode *value);

/* Windows.Storage.Pickers.FileOpenPicker.put_ViewMode() */
HRESULT wstpi_file_open_picker_put__view_mode(WSTPI_FileOpenPicker *self, WSTPI_PickerViewMode value);

/* Windows.Storage.Pickers.FileOpenPicker.get_SettingsIdentifier() */
HRESULT wstpi_file_open_picker_get__settings_identifier(WSTPI_FileOpenPicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileOpenPicker.put_SettingsIdentifier() */
HRESULT wstpi_file_open_picker_put__settings_identifier(WSTPI_FileOpenPicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileOpenPicker.get_SuggestedStartLocation() */
HRESULT wstpi_file_open_picker_get__suggested_start_location(WSTPI_FileOpenPicker *self, WSTPI_PickerLocationId *value);

/* Windows.Storage.Pickers.FileOpenPicker.put_SuggestedStartLocation() */
HRESULT wstpi_file_open_picker_put__suggested_start_location(WSTPI_FileOpenPicker *self, WSTPI_PickerLocationId value);

/* Windows.Storage.Pickers.FileOpenPicker.get_CommitButtonText() */
HRESULT wstpi_file_open_picker_get__commit_button_text(WSTPI_FileOpenPicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileOpenPicker.put_CommitButtonText() */
HRESULT wstpi_file_open_picker_put__commit_button_text(WSTPI_FileOpenPicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileOpenPicker.get_FileTypeFilter() */
HRESULT wstpi_file_open_picker_get__file_type_filter(WSTPI_FileOpenPicker *self, WFOCO_IVector_HSTRING** value);

/* Windows.Storage.Pickers.FileOpenPicker.PickSingleFileAsync() */
HRESULT wstpi_file_open_picker_pick_single_file_async(WSTPI_FileOpenPicker *self, WF_IAsyncOperation_WS_StorageFile** out);

/* Windows.Storage.Pickers.FileOpenPicker.PickMultipleFilesAsync() */
HRESULT wstpi_file_open_picker_pick_multiple_files_async(WSTPI_FileOpenPicker *self, WF_IAsyncOperation_WFOCO_IVectorView_WS_StorageFile** out);

/* Windows.Storage.Pickers.FileOpenPicker.get_User() */
HRESULT wstpi_file_open_picker_get__user(WSTPI_FileOpenPicker *self, WSY_User** value);

/* Windows.Storage.Pickers.FileOpenPicker.CreateForUser(user) */
HRESULT wstpi_file_open_picker_create_for_user(WSY_User* user, WSTPI_FileOpenPicker** out);

/* Windows.Storage.Pickers.FileOpenPicker.ResumePickSingleFileAsync() */
HRESULT wstpi_file_open_picker_resume_pick_single_file_async(WF_IAsyncOperation_WS_StorageFile** out);

/* activate Windows.Storage.Pickers.FilePickerFileTypesOrderedMap */
HRESULT wstpi_file_picker_file_types_ordered_map_new(WSTPI_FilePickerFileTypesOrderedMap **out);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap */
/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.Lookup(key) */
HRESULT wstpi_file_picker_file_types_ordered_map_lookup(WSTPI_FilePickerFileTypesOrderedMap *self, cwinrt_hstring key, WFOCO_IVector_HSTRING** out);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.get_Size() */
HRESULT wstpi_file_picker_file_types_ordered_map_get__size(WSTPI_FilePickerFileTypesOrderedMap *self, uint32_t *value);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.HasKey(key) */
HRESULT wstpi_file_picker_file_types_ordered_map_has_key(WSTPI_FilePickerFileTypesOrderedMap *self, cwinrt_hstring key, BOOL *out);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.GetView() */
HRESULT wstpi_file_picker_file_types_ordered_map_get_view(WSTPI_FilePickerFileTypesOrderedMap *self, WFOCO_IMapView_HSTRING_WFOCO_IVector_HSTRING** out);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.Insert(key) */
HRESULT wstpi_file_picker_file_types_ordered_map_insert(WSTPI_FilePickerFileTypesOrderedMap *self, cwinrt_hstring key, WFOCO_IVector_HSTRING* value, BOOL *out);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.Remove(key) */
HRESULT wstpi_file_picker_file_types_ordered_map_remove(WSTPI_FilePickerFileTypesOrderedMap *self, cwinrt_hstring key);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.Clear() */
HRESULT wstpi_file_picker_file_types_ordered_map_clear(WSTPI_FilePickerFileTypesOrderedMap *self);

/* Windows.Storage.Pickers.FilePickerFileTypesOrderedMap.First() */
HRESULT wstpi_file_picker_file_types_ordered_map_first(WSTPI_FilePickerFileTypesOrderedMap *self, WFOCO_IIterator_WFOCO_IKeyValuePair_HSTRING_WFOCO_IVector_HSTRING** out);

/* activate Windows.Storage.Pickers.FilePickerSelectedFilesArray */
HRESULT wstpi_file_picker_selected_files_array_new(WSTPI_FilePickerSelectedFilesArray **out);

/* Windows.Storage.Pickers.FilePickerSelectedFilesArray */
/* Windows.Storage.Pickers.FilePickerSelectedFilesArray.GetAt(index) */
HRESULT wstpi_file_picker_selected_files_array_get_at(WSTPI_FilePickerSelectedFilesArray *self, uint32_t index, WS_StorageFile** out);

/* Windows.Storage.Pickers.FilePickerSelectedFilesArray.get_Size() */
HRESULT wstpi_file_picker_selected_files_array_get__size(WSTPI_FilePickerSelectedFilesArray *self, uint32_t *value);

/* Windows.Storage.Pickers.FilePickerSelectedFilesArray.IndexOf(index) */
HRESULT wstpi_file_picker_selected_files_array_index_of(WSTPI_FilePickerSelectedFilesArray *self, WS_StorageFile* value, uint32_t index, BOOL *out);

/* Windows.Storage.Pickers.FilePickerSelectedFilesArray.GetMany(startIndex, items) */
HRESULT wstpi_file_picker_selected_files_array_get_many(WSTPI_FilePickerSelectedFilesArray *self, uint32_t startIndex, WS_StorageFile *items, uint32_t items_len, uint32_t *out);

/* Windows.Storage.Pickers.FilePickerSelectedFilesArray.First() */
HRESULT wstpi_file_picker_selected_files_array_first(WSTPI_FilePickerSelectedFilesArray *self, WFOCO_IIterator_WS_StorageFile** out);

/* activate Windows.Storage.Pickers.FileSavePicker */
HRESULT wstpi_file_save_picker_new(WSTPI_FileSavePicker **out);

/* Windows.Storage.Pickers.FileSavePicker */
/* Windows.Storage.Pickers.FileSavePicker.get_ContinuationData() */
HRESULT wstpi_file_save_picker_get__continuation_data(WSTPI_FileSavePicker *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.FileSavePicker.PickSaveFileAndContinue() */
HRESULT wstpi_file_save_picker_pick_save_file_and_continue(WSTPI_FileSavePicker *self);

/* Windows.Storage.Pickers.FileSavePicker.get_EnterpriseId() */
HRESULT wstpi_file_save_picker_get__enterprise_id(WSTPI_FileSavePicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileSavePicker.put_EnterpriseId() */
HRESULT wstpi_file_save_picker_put__enterprise_id(WSTPI_FileSavePicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileSavePicker.get_SettingsIdentifier() */
HRESULT wstpi_file_save_picker_get__settings_identifier(WSTPI_FileSavePicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileSavePicker.put_SettingsIdentifier() */
HRESULT wstpi_file_save_picker_put__settings_identifier(WSTPI_FileSavePicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileSavePicker.get_SuggestedStartLocation() */
HRESULT wstpi_file_save_picker_get__suggested_start_location(WSTPI_FileSavePicker *self, WSTPI_PickerLocationId *value);

/* Windows.Storage.Pickers.FileSavePicker.put_SuggestedStartLocation() */
HRESULT wstpi_file_save_picker_put__suggested_start_location(WSTPI_FileSavePicker *self, WSTPI_PickerLocationId value);

/* Windows.Storage.Pickers.FileSavePicker.get_CommitButtonText() */
HRESULT wstpi_file_save_picker_get__commit_button_text(WSTPI_FileSavePicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileSavePicker.put_CommitButtonText() */
HRESULT wstpi_file_save_picker_put__commit_button_text(WSTPI_FileSavePicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileSavePicker.get_FileTypeChoices() */
HRESULT wstpi_file_save_picker_get__file_type_choices(WSTPI_FileSavePicker *self, WFOCO_IMap_HSTRING_WFOCO_IVector_HSTRING** value);

/* Windows.Storage.Pickers.FileSavePicker.get_DefaultFileExtension() */
HRESULT wstpi_file_save_picker_get__default_file_extension(WSTPI_FileSavePicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileSavePicker.put_DefaultFileExtension() */
HRESULT wstpi_file_save_picker_put__default_file_extension(WSTPI_FileSavePicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileSavePicker.get_SuggestedSaveFile() */
HRESULT wstpi_file_save_picker_get__suggested_save_file(WSTPI_FileSavePicker *self, WS_StorageFile** value);

/* Windows.Storage.Pickers.FileSavePicker.put_SuggestedSaveFile() */
HRESULT wstpi_file_save_picker_put__suggested_save_file(WSTPI_FileSavePicker *self, WS_StorageFile* value);

/* Windows.Storage.Pickers.FileSavePicker.get_SuggestedFileName() */
HRESULT wstpi_file_save_picker_get__suggested_file_name(WSTPI_FileSavePicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FileSavePicker.put_SuggestedFileName() */
HRESULT wstpi_file_save_picker_put__suggested_file_name(WSTPI_FileSavePicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileSavePicker.PickSaveFileAsync() */
HRESULT wstpi_file_save_picker_pick_save_file_async(WSTPI_FileSavePicker *self, WF_IAsyncOperation_WS_StorageFile** out);

/* Windows.Storage.Pickers.FileSavePicker.get_User() */
HRESULT wstpi_file_save_picker_get__user(WSTPI_FileSavePicker *self, WSY_User** value);

/* Windows.Storage.Pickers.FileSavePicker.CreateForUser(user) */
HRESULT wstpi_file_save_picker_create_for_user(WSY_User* user, WSTPI_FileSavePicker** out);

/* activate Windows.Storage.Pickers.FolderPicker */
HRESULT wstpi_folder_picker_new(WSTPI_FolderPicker **out);

/* Windows.Storage.Pickers.FolderPicker */
/* Windows.Storage.Pickers.FolderPicker.get_ContinuationData() */
HRESULT wstpi_folder_picker_get__continuation_data(WSTPI_FolderPicker *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.FolderPicker.PickFolderAndContinue() */
HRESULT wstpi_folder_picker_pick_folder_and_continue(WSTPI_FolderPicker *self);

/* Windows.Storage.Pickers.FolderPicker.get_ViewMode() */
HRESULT wstpi_folder_picker_get__view_mode(WSTPI_FolderPicker *self, WSTPI_PickerViewMode *value);

/* Windows.Storage.Pickers.FolderPicker.put_ViewMode() */
HRESULT wstpi_folder_picker_put__view_mode(WSTPI_FolderPicker *self, WSTPI_PickerViewMode value);

/* Windows.Storage.Pickers.FolderPicker.get_SettingsIdentifier() */
HRESULT wstpi_folder_picker_get__settings_identifier(WSTPI_FolderPicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FolderPicker.put_SettingsIdentifier() */
HRESULT wstpi_folder_picker_put__settings_identifier(WSTPI_FolderPicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FolderPicker.get_SuggestedStartLocation() */
HRESULT wstpi_folder_picker_get__suggested_start_location(WSTPI_FolderPicker *self, WSTPI_PickerLocationId *value);

/* Windows.Storage.Pickers.FolderPicker.put_SuggestedStartLocation() */
HRESULT wstpi_folder_picker_put__suggested_start_location(WSTPI_FolderPicker *self, WSTPI_PickerLocationId value);

/* Windows.Storage.Pickers.FolderPicker.get_CommitButtonText() */
HRESULT wstpi_folder_picker_get__commit_button_text(WSTPI_FolderPicker *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.FolderPicker.put_CommitButtonText() */
HRESULT wstpi_folder_picker_put__commit_button_text(WSTPI_FolderPicker *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FolderPicker.get_FileTypeFilter() */
HRESULT wstpi_folder_picker_get__file_type_filter(WSTPI_FolderPicker *self, WFOCO_IVector_HSTRING** value);

/* Windows.Storage.Pickers.FolderPicker.PickSingleFolderAsync() */
HRESULT wstpi_folder_picker_pick_single_folder_async(WSTPI_FolderPicker *self, WF_IAsyncOperation_WS_StorageFolder** out);

/* Windows.Storage.Pickers.FolderPicker.get_User() */
HRESULT wstpi_folder_picker_get__user(WSTPI_FolderPicker *self, WSY_User** value);

/* Windows.Storage.Pickers.FolderPicker.CreateForUser(user) */
HRESULT wstpi_folder_picker_create_for_user(WSY_User* user, WSTPI_FolderPicker** out);

/* Windows.Storage.Pickers.IFileOpenPickerStatics */
/* Windows.Storage.Pickers.IFileOpenPickerStatics.ResumePickSingleFileAsync() */
HRESULT wstpi_file_open_picker_statics_resume_pick_single_file_async(WSTPI_IFileOpenPickerStatics *self, WF_IAsyncOperation_WS_StorageFile** out);

/* Windows.Storage.Pickers.IFileOpenPickerStatics2 */
/* Windows.Storage.Pickers.IFileOpenPickerStatics2.CreateForUser(user) */
HRESULT wstpi_file_open_picker_statics_2_create_for_user(WSTPI_IFileOpenPickerStatics_2 *self, WSY_User* user, WSTPI_FileOpenPicker** out);

/* Windows.Storage.Pickers.IFileSavePickerStatics */
/* Windows.Storage.Pickers.IFileSavePickerStatics.CreateForUser(user) */
HRESULT wstpi_file_save_picker_statics_create_for_user(WSTPI_IFileSavePickerStatics *self, WSY_User* user, WSTPI_FileSavePicker** out);

/* activate Windows.Storage.Pickers.FileExtensionVector */
HRESULT wstpi_file_extension_vector_new(WSTPI_FileExtensionVector **out);

/* Windows.Storage.Pickers.FileExtensionVector */
/* Windows.Storage.Pickers.FileExtensionVector.GetAt(index) */
HRESULT wstpi_file_extension_vector_get_at(WSTPI_FileExtensionVector *self, uint32_t index, cwinrt_hstring *out);

/* Windows.Storage.Pickers.FileExtensionVector.get_Size() */
HRESULT wstpi_file_extension_vector_get__size(WSTPI_FileExtensionVector *self, uint32_t *value);

/* Windows.Storage.Pickers.FileExtensionVector.GetView() */
HRESULT wstpi_file_extension_vector_get_view(WSTPI_FileExtensionVector *self, WFOCO_IVectorView_HSTRING** out);

/* Windows.Storage.Pickers.FileExtensionVector.IndexOf(index) */
HRESULT wstpi_file_extension_vector_index_of(WSTPI_FileExtensionVector *self, cwinrt_hstring value, uint32_t index, BOOL *out);

/* Windows.Storage.Pickers.FileExtensionVector.SetAt(index) */
HRESULT wstpi_file_extension_vector_set_at(WSTPI_FileExtensionVector *self, uint32_t index, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileExtensionVector.InsertAt(index) */
HRESULT wstpi_file_extension_vector_insert_at(WSTPI_FileExtensionVector *self, uint32_t index, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileExtensionVector.RemoveAt(index) */
HRESULT wstpi_file_extension_vector_remove_at(WSTPI_FileExtensionVector *self, uint32_t index);

/* Windows.Storage.Pickers.FileExtensionVector.Append() */
HRESULT wstpi_file_extension_vector_append(WSTPI_FileExtensionVector *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.FileExtensionVector.RemoveAtEnd() */
HRESULT wstpi_file_extension_vector_remove_at_end(WSTPI_FileExtensionVector *self);

/* Windows.Storage.Pickers.FileExtensionVector.Clear() */
HRESULT wstpi_file_extension_vector_clear(WSTPI_FileExtensionVector *self);

/* Windows.Storage.Pickers.FileExtensionVector.GetMany(startIndex, items) */
HRESULT wstpi_file_extension_vector_get_many(WSTPI_FileExtensionVector *self, uint32_t startIndex, cwinrt_hstring *items, uint32_t items_len, uint32_t *out);

/* Windows.Storage.Pickers.FileExtensionVector.ReplaceAll(items) */
HRESULT wstpi_file_extension_vector_replace_all(WSTPI_FileExtensionVector *self, cwinrt_hstring *items, uint32_t items_len);

/* Windows.Storage.Pickers.FileExtensionVector.First() */
HRESULT wstpi_file_extension_vector_first(WSTPI_FileExtensionVector *self, WFOCO_IIterator_HSTRING** out);

/* Windows.Storage.Pickers.IFileOpenPicker2 */
/* Windows.Storage.Pickers.IFileOpenPicker2.get_ContinuationData() */
HRESULT wstpi_file_open_picker_2_get__continuation_data(WSTPI_IFileOpenPicker_2 *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.IFileOpenPicker2.PickSingleFileAndContinue() */
HRESULT wstpi_file_open_picker_2_pick_single_file_and_continue(WSTPI_IFileOpenPicker_2 *self);

/* Windows.Storage.Pickers.IFileOpenPicker2.PickMultipleFilesAndContinue() */
HRESULT wstpi_file_open_picker_2_pick_multiple_files_and_continue(WSTPI_IFileOpenPicker_2 *self);

/* Windows.Storage.Pickers.IFileOpenPickerWithOperationId */
/* Windows.Storage.Pickers.IFileOpenPickerWithOperationId.PickSingleFileAsync(pickerOperationId) */
HRESULT wstpi_file_open_picker_with_operation_id_pick_single_file_async(WSTPI_IFileOpenPickerWithOperationId *self, cwinrt_hstring pickerOperationId, WF_IAsyncOperation_WS_StorageFile** out);

/* Windows.Storage.Pickers.IFileOpenPicker */
/* Windows.Storage.Pickers.IFileOpenPicker3 */
/* Windows.Storage.Pickers.IFileOpenPicker3.get_User() */
HRESULT wstpi_file_open_picker_3_get__user(WSTPI_IFileOpenPicker_3 *self, WSY_User** value);

/* Windows.Storage.Pickers.IFileSavePicker2 */
/* Windows.Storage.Pickers.IFileSavePicker2.get_ContinuationData() */
HRESULT wstpi_file_save_picker_2_get__continuation_data(WSTPI_IFileSavePicker_2 *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.IFileSavePicker2.PickSaveFileAndContinue() */
HRESULT wstpi_file_save_picker_2_pick_save_file_and_continue(WSTPI_IFileSavePicker_2 *self);

/* Windows.Storage.Pickers.IFileSavePicker3 */
/* Windows.Storage.Pickers.IFileSavePicker3.get_EnterpriseId() */
HRESULT wstpi_file_save_picker_3_get__enterprise_id(WSTPI_IFileSavePicker_3 *self, cwinrt_hstring *value);

/* Windows.Storage.Pickers.IFileSavePicker3.put_EnterpriseId() */
HRESULT wstpi_file_save_picker_3_put__enterprise_id(WSTPI_IFileSavePicker_3 *self, cwinrt_hstring value);

/* Windows.Storage.Pickers.IFileSavePicker */
/* Windows.Storage.Pickers.IFileSavePicker4 */
/* Windows.Storage.Pickers.IFileSavePicker4.get_User() */
HRESULT wstpi_file_save_picker_4_get__user(WSTPI_IFileSavePicker_4 *self, WSY_User** value);

/* Windows.Storage.Pickers.IFolderPicker2 */
/* Windows.Storage.Pickers.IFolderPicker2.get_ContinuationData() */
HRESULT wstpi_folder_picker_2_get__continuation_data(WSTPI_IFolderPicker_2 *self, WFOCO_ValueSet** value);

/* Windows.Storage.Pickers.IFolderPicker2.PickFolderAndContinue() */
HRESULT wstpi_folder_picker_2_pick_folder_and_continue(WSTPI_IFolderPicker_2 *self);

/* Windows.Storage.Pickers.IFolderPicker */
/* Windows.Storage.Pickers.IFolderPicker3 */
/* Windows.Storage.Pickers.IFolderPicker3.get_User() */
HRESULT wstpi_folder_picker_3_get__user(WSTPI_IFolderPicker_3 *self, WSY_User** value);

#endif /* CWINRT_WINDOWS_STORAGE_PICKERS_H */
