/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_MEDIA_APPRECORDING_H
#define CWINRT_WINDOWS_MEDIA_APPRECORDING_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WS_StorageFile
#define CWINRT_FWD_WS_StorageFile
typedef struct WS_StorageFile WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WS_StorageFolder
#define CWINRT_FWD_WS_StorageFolder
typedef struct WS_StorageFolder WS_StorageFolder;
#endif

/* Types (forward declarations) */
typedef struct WMEAP_AppRecordingResult WMEAP_AppRecordingResult;
typedef struct WMEAP_AppRecordingSaveScreenshotResult WMEAP_AppRecordingSaveScreenshotResult;
typedef struct WMEAP_AppRecordingSavedScreenshotInfo WMEAP_AppRecordingSavedScreenshotInfo;
typedef struct WMEAP_AppRecordingStatus WMEAP_AppRecordingStatus;
typedef struct WMEAP_AppRecordingStatusDetails WMEAP_AppRecordingStatusDetails;
typedef struct WMEAP_IAppRecordingManagerStatics WMEAP_IAppRecordingManagerStatics;
typedef struct WMEAP_AppRecordingManager WMEAP_AppRecordingManager;
typedef struct WMEAP_IAppRecordingResult WMEAP_IAppRecordingResult;
typedef struct WMEAP_IAppRecordingSaveScreenshotResult WMEAP_IAppRecordingSaveScreenshotResult;
typedef struct WMEAP_IAppRecordingSavedScreenshotInfo WMEAP_IAppRecordingSavedScreenshotInfo;
typedef struct WMEAP_IAppRecordingStatus WMEAP_IAppRecordingStatus;
typedef struct WMEAP_IAppRecordingStatusDetails WMEAP_IAppRecordingStatusDetails;
typedef struct WMEAP_IAppRecordingManager WMEAP_IAppRecordingManager;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WF_TimeSpan
#define CWINRT_FWD_WF_TimeSpan
typedef struct WF_TimeSpan WF_TimeSpan;
#endif
#ifndef CWINRT_FWD_WFOCO_IVectorView_WMEAP_AppRecordingSavedScreenshotInfo
#define CWINRT_FWD_WFOCO_IVectorView_WMEAP_AppRecordingSavedScreenshotInfo
typedef struct WFOCO_IVectorView_WMEAP_AppRecordingSavedScreenshotInfo WFOCO_IVectorView_WMEAP_AppRecordingSavedScreenshotInfo;
#endif
#ifndef CWINRT_FWD_WS_StorageFile
#define CWINRT_FWD_WS_StorageFile
typedef struct WS_StorageFile WS_StorageFile;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WMEAP_AppRecordingResult
#define CWINRT_FWD_WF_IAsyncOperation_WMEAP_AppRecordingResult
typedef struct WF_IAsyncOperation_WMEAP_AppRecordingResult WF_IAsyncOperation_WMEAP_AppRecordingResult;
#endif
#ifndef CWINRT_FWD_WF_DateTime
#define CWINRT_FWD_WF_DateTime
typedef struct WF_DateTime WF_DateTime;
#endif
#ifndef CWINRT_FWD_WFOCO_IVectorView_HSTRING
#define CWINRT_FWD_WFOCO_IVectorView_HSTRING
typedef struct WFOCO_IVectorView_HSTRING WFOCO_IVectorView_HSTRING;
#endif
#ifndef CWINRT_FWD_WS_StorageFolder
#define CWINRT_FWD_WS_StorageFolder
typedef struct WS_StorageFolder WS_StorageFolder;
#endif
#ifndef CWINRT_FWD_WFOCO_IIterable_HSTRING
#define CWINRT_FWD_WFOCO_IIterable_HSTRING
typedef struct WFOCO_IIterable_HSTRING WFOCO_IIterable_HSTRING;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WMEAP_AppRecordingSaveScreenshotResult
#define CWINRT_FWD_WF_IAsyncOperation_WMEAP_AppRecordingSaveScreenshotResult
typedef struct WF_IAsyncOperation_WMEAP_AppRecordingSaveScreenshotResult WF_IAsyncOperation_WMEAP_AppRecordingSaveScreenshotResult;
#endif

#ifndef CWINRT_FWD_WMEAP_AppRecordingSaveScreenshotOption
#define CWINRT_FWD_WMEAP_AppRecordingSaveScreenshotOption
typedef enum WMEAP_AppRecordingSaveScreenshotOption {
    WMEAP_AppRecordingSaveScreenshotOption_None = 0,
    WMEAP_AppRecordingSaveScreenshotOption_HdrContentVisible = 1
} WMEAP_AppRecordingSaveScreenshotOption;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingManagerStatics
#define CWINRT_IIDDEF_WMEAP_IAppRecordingManagerStatics
static const IID CWINRT_IID_WMEAP_IAppRecordingManagerStatics CWINRT_MAYBE_UNUSED = { 0x50E709F7, 0x38CE, 0x4BD3, { 0x9D, 0xB2, 0xE7, 0x2B, 0xBE, 0x9D, 0xE1, 0x1D } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingResult
#define CWINRT_IIDDEF_WMEAP_IAppRecordingResult
static const IID CWINRT_IID_WMEAP_IAppRecordingResult CWINRT_MAYBE_UNUSED = { 0x3A900864, 0xC66D, 0x46F9, { 0xB2, 0xD9, 0x5B, 0xC2, 0xDA, 0xD0, 0x70, 0xD7 } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingSaveScreenshotResult
#define CWINRT_IIDDEF_WMEAP_IAppRecordingSaveScreenshotResult
static const IID CWINRT_IID_WMEAP_IAppRecordingSaveScreenshotResult CWINRT_MAYBE_UNUSED = { 0x9C5B8D0A, 0x0ABB, 0x4457, { 0xAA, 0xEE, 0x24, 0xF9, 0xC1, 0x2E, 0xC7, 0x78 } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingSavedScreenshotInfo
#define CWINRT_IIDDEF_WMEAP_IAppRecordingSavedScreenshotInfo
static const IID CWINRT_IID_WMEAP_IAppRecordingSavedScreenshotInfo CWINRT_MAYBE_UNUSED = { 0x9B642D0A, 0x189A, 0x4D00, { 0xBF, 0x25, 0xE1, 0xBB, 0x12, 0x49, 0xD5, 0x94 } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingStatus
#define CWINRT_IIDDEF_WMEAP_IAppRecordingStatus
static const IID CWINRT_IID_WMEAP_IAppRecordingStatus CWINRT_MAYBE_UNUSED = { 0x1D0CC82C, 0xBC18, 0x4B8A, { 0xA6, 0xEF, 0x12, 0x7E, 0xFA, 0xB3, 0xB5, 0xD9 } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingStatusDetails
#define CWINRT_IIDDEF_WMEAP_IAppRecordingStatusDetails
static const IID CWINRT_IID_WMEAP_IAppRecordingStatusDetails CWINRT_MAYBE_UNUSED = { 0xB538A9B0, 0x14ED, 0x4412, { 0xAC, 0x45, 0x6D, 0x67, 0x2C, 0x9C, 0x99, 0x49 } };
#endif
#ifndef CWINRT_IIDDEF_WMEAP_IAppRecordingManager
#define CWINRT_IIDDEF_WMEAP_IAppRecordingManager
static const IID CWINRT_IID_WMEAP_IAppRecordingManager CWINRT_MAYBE_UNUSED = { 0xE7E26076, 0xA044, 0x48E2, { 0xA5, 0x12, 0x30, 0x94, 0xD5, 0x74, 0xC7, 0xCC } };
#endif

/* Methods */

/* activate Windows.Media.AppRecording.AppRecordingResult */
HRESULT wmeap_app_recording_result_new(WMEAP_AppRecordingResult **out);

/* Windows.Media.AppRecording.AppRecordingResult */
/* Windows.Media.AppRecording.AppRecordingResult.get_Succeeded() */
HRESULT wmeap_app_recording_result_get__succeeded(WMEAP_AppRecordingResult *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingResult.get_ExtendedError() */
HRESULT wmeap_app_recording_result_get__extended_error(WMEAP_AppRecordingResult *self, HRESULT *value);

/* Windows.Media.AppRecording.AppRecordingResult.get_Duration() */
HRESULT wmeap_app_recording_result_get__duration(WMEAP_AppRecordingResult *self, WF_TimeSpan *value);

/* Windows.Media.AppRecording.AppRecordingResult.get_IsFileTruncated() */
HRESULT wmeap_app_recording_result_get__is_file_truncated(WMEAP_AppRecordingResult *self, BOOL *value);

/* activate Windows.Media.AppRecording.AppRecordingSaveScreenshotResult */
HRESULT wmeap_app_recording_save_screenshot_result_new(WMEAP_AppRecordingSaveScreenshotResult **out);

/* Windows.Media.AppRecording.AppRecordingSaveScreenshotResult */
/* Windows.Media.AppRecording.AppRecordingSaveScreenshotResult.get_Succeeded() */
HRESULT wmeap_app_recording_save_screenshot_result_get__succeeded(WMEAP_AppRecordingSaveScreenshotResult *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingSaveScreenshotResult.get_ExtendedError() */
HRESULT wmeap_app_recording_save_screenshot_result_get__extended_error(WMEAP_AppRecordingSaveScreenshotResult *self, HRESULT *value);

/* Windows.Media.AppRecording.AppRecordingSaveScreenshotResult.get_SavedScreenshotInfos() */
HRESULT wmeap_app_recording_save_screenshot_result_get__saved_screenshot_infos(WMEAP_AppRecordingSaveScreenshotResult *self, WFOCO_IVectorView_WMEAP_AppRecordingSavedScreenshotInfo** value);

/* activate Windows.Media.AppRecording.AppRecordingSavedScreenshotInfo */
HRESULT wmeap_app_recording_saved_screenshot_info_new(WMEAP_AppRecordingSavedScreenshotInfo **out);

/* Windows.Media.AppRecording.AppRecordingSavedScreenshotInfo */
/* Windows.Media.AppRecording.AppRecordingSavedScreenshotInfo.get_File() */
HRESULT wmeap_app_recording_saved_screenshot_info_get__file(WMEAP_AppRecordingSavedScreenshotInfo *self, WS_StorageFile** value);

/* Windows.Media.AppRecording.AppRecordingSavedScreenshotInfo.get_MediaEncodingSubtype() */
HRESULT wmeap_app_recording_saved_screenshot_info_get__media_encoding_subtype(WMEAP_AppRecordingSavedScreenshotInfo *self, cwinrt_hstring *value);

/* activate Windows.Media.AppRecording.AppRecordingStatus */
HRESULT wmeap_app_recording_status_new(WMEAP_AppRecordingStatus **out);

/* Windows.Media.AppRecording.AppRecordingStatus */
/* Windows.Media.AppRecording.AppRecordingStatus.get_CanRecord() */
HRESULT wmeap_app_recording_status_get__can_record(WMEAP_AppRecordingStatus *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatus.get_CanRecordTimeSpan() */
HRESULT wmeap_app_recording_status_get__can_record_time_span(WMEAP_AppRecordingStatus *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatus.get_HistoricalBufferDuration() */
HRESULT wmeap_app_recording_status_get__historical_buffer_duration(WMEAP_AppRecordingStatus *self, WF_TimeSpan *value);

/* Windows.Media.AppRecording.AppRecordingStatus.get_Details() */
HRESULT wmeap_app_recording_status_get__details(WMEAP_AppRecordingStatus *self, WMEAP_AppRecordingStatusDetails** value);

/* activate Windows.Media.AppRecording.AppRecordingStatusDetails */
HRESULT wmeap_app_recording_status_details_new(WMEAP_AppRecordingStatusDetails **out);

/* Windows.Media.AppRecording.AppRecordingStatusDetails */
/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsAnyAppBroadcasting() */
HRESULT wmeap_app_recording_status_details_get__is_any_app_broadcasting(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsCaptureResourceUnavailable() */
HRESULT wmeap_app_recording_status_details_get__is_capture_resource_unavailable(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsGameStreamInProgress() */
HRESULT wmeap_app_recording_status_details_get__is_game_stream_in_progress(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsTimeSpanRecordingDisabled() */
HRESULT wmeap_app_recording_status_details_get__is_time_span_recording_disabled(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsGpuConstrained() */
HRESULT wmeap_app_recording_status_details_get__is_gpu_constrained(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsAppInactive() */
HRESULT wmeap_app_recording_status_details_get__is_app_inactive(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsBlockedForApp() */
HRESULT wmeap_app_recording_status_details_get__is_blocked_for_app(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsDisabledByUser() */
HRESULT wmeap_app_recording_status_details_get__is_disabled_by_user(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.AppRecordingStatusDetails.get_IsDisabledBySystem() */
HRESULT wmeap_app_recording_status_details_get__is_disabled_by_system(WMEAP_AppRecordingStatusDetails *self, BOOL *value);

/* Windows.Media.AppRecording.IAppRecordingManagerStatics */
/* Windows.Media.AppRecording.IAppRecordingManagerStatics.GetDefault() */
HRESULT wmeap_app_recording_manager_statics_get_default(WMEAP_IAppRecordingManagerStatics *self, WMEAP_AppRecordingManager** out);

/* activate Windows.Media.AppRecording.AppRecordingManager */
HRESULT wmeap_app_recording_manager_new(WMEAP_AppRecordingManager **out);

/* Windows.Media.AppRecording.AppRecordingManager */
/* Windows.Media.AppRecording.AppRecordingManager.GetStatus() */
HRESULT wmeap_app_recording_manager_get_status(WMEAP_AppRecordingManager *self, WMEAP_AppRecordingStatus** out);

/* Windows.Media.AppRecording.AppRecordingManager.StartRecordingToFileAsync(file) */
HRESULT wmeap_app_recording_manager_start_recording_to_file_async(WMEAP_AppRecordingManager *self, WS_StorageFile* file, WF_IAsyncOperation_WMEAP_AppRecordingResult** out);

/* Windows.Media.AppRecording.AppRecordingManager.RecordTimeSpanToFileAsync(startTime, duration, file) */
HRESULT wmeap_app_recording_manager_record_time_span_to_file_async(WMEAP_AppRecordingManager *self, WF_DateTime startTime, WF_TimeSpan duration, WS_StorageFile* file, WF_IAsyncOperation_WMEAP_AppRecordingResult** out);

/* Windows.Media.AppRecording.AppRecordingManager.get_SupportedScreenshotMediaEncodingSubtypes() */
HRESULT wmeap_app_recording_manager_get__supported_screenshot_media_encoding_subtypes(WMEAP_AppRecordingManager *self, WFOCO_IVectorView_HSTRING** value);

/* Windows.Media.AppRecording.AppRecordingManager.SaveScreenshotToFilesAsync(folder, filenamePrefix, option, requestedFormats) */
HRESULT wmeap_app_recording_manager_save_screenshot_to_files_async(WMEAP_AppRecordingManager *self, WS_StorageFolder* folder, cwinrt_hstring filenamePrefix, WMEAP_AppRecordingSaveScreenshotOption option, WFOCO_IIterable_HSTRING* requestedFormats, WF_IAsyncOperation_WMEAP_AppRecordingSaveScreenshotResult** out);

/* Windows.Media.AppRecording.AppRecordingManager.GetDefault() */
HRESULT wmeap_app_recording_manager_get_default(WMEAP_AppRecordingManager** out);

/* Windows.Media.AppRecording.IAppRecordingResult */
/* Windows.Media.AppRecording.IAppRecordingSaveScreenshotResult */
/* Windows.Media.AppRecording.IAppRecordingSavedScreenshotInfo */
/* Windows.Media.AppRecording.IAppRecordingStatus */
/* Windows.Media.AppRecording.IAppRecordingStatusDetails */
/* Windows.Media.AppRecording.IAppRecordingManager */
#endif /* CWINRT_WINDOWS_MEDIA_APPRECORDING_H */
