/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_UI_XAML_MEDIA_IMAGING_H
#define CWINRT_WINDOWS_UI_XAML_MEDIA_IMAGING_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/Windows.UI.Xaml.Media.h>
#include <cwinrt/Windows.UI.Xaml.h>
#include <cwinrt/Windows.Graphics.Imaging.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WSTST_IRandomAccessStream
#define CWINRT_FWD_WSTST_IRandomAccessStream
typedef struct WSTST_IRandomAccessStream WSTST_IRandomAccessStream;
#endif
#ifndef CWINRT_FWD_WSTST_IBuffer
#define CWINRT_FWD_WSTST_IBuffer
typedef struct WSTST_IBuffer WSTST_IBuffer;
#endif
#ifndef CWINRT_FWD_WAPBA_IBackgroundTaskInstance
#define CWINRT_FWD_WAPBA_IBackgroundTaskInstance
typedef struct WAPBA_IBackgroundTaskInstance WAPBA_IBackgroundTaskInstance;
#endif

/* Types (forward declarations) */
typedef struct WUIXAMEIM_XamlRenderingBackgroundTask WUIXAMEIM_XamlRenderingBackgroundTask;
typedef struct WUIXAMEIM_VirtualSurfaceImageSource WUIXAMEIM_VirtualSurfaceImageSource;
typedef struct WUIXAMEIM_WriteableBitmap WUIXAMEIM_WriteableBitmap;
typedef struct WUIXAMEIM_SvgImageSourceFailedEventArgs WUIXAMEIM_SvgImageSourceFailedEventArgs;
typedef struct WUIXAMEIM_BitmapSource WUIXAMEIM_BitmapSource;
typedef struct WUIXAMEIM_BitmapImage WUIXAMEIM_BitmapImage;
typedef struct WUIXAMEIM_DownloadProgressEventArgs WUIXAMEIM_DownloadProgressEventArgs;
typedef struct WUIXAMEIM_DownloadProgressEventHandler WUIXAMEIM_DownloadProgressEventHandler;
typedef struct WUIXAMEIM_IBitmapImageFactory WUIXAMEIM_IBitmapImageFactory;
typedef struct WUIXAMEIM_IBitmapImageStatics WUIXAMEIM_IBitmapImageStatics;
typedef struct WUIXAMEIM_IBitmapImageStatics_2 WUIXAMEIM_IBitmapImageStatics_2;
typedef struct WUIXAMEIM_IBitmapImageStatics_3 WUIXAMEIM_IBitmapImageStatics_3;
typedef struct WUIXAMEIM_IBitmapSourceFactory WUIXAMEIM_IBitmapSourceFactory;
typedef struct WUIXAMEIM_IBitmapSourceStatics WUIXAMEIM_IBitmapSourceStatics;
typedef struct WUIXAMEIM_IRenderTargetBitmapStatics WUIXAMEIM_IRenderTargetBitmapStatics;
typedef struct WUIXAMEIM_ISurfaceImageSourceFactory WUIXAMEIM_ISurfaceImageSourceFactory;
typedef struct WUIXAMEIM_SvgImageSource WUIXAMEIM_SvgImageSource;
typedef struct WUIXAMEIM_SvgImageSourceOpenedEventArgs WUIXAMEIM_SvgImageSourceOpenedEventArgs;
typedef struct WUIXAMEIM_ISvgImageSourceFactory WUIXAMEIM_ISvgImageSourceFactory;
typedef struct WUIXAMEIM_ISvgImageSourceStatics WUIXAMEIM_ISvgImageSourceStatics;
typedef struct WUIXAMEIM_IVirtualSurfaceImageSourceFactory WUIXAMEIM_IVirtualSurfaceImageSourceFactory;
typedef struct WUIXAMEIM_IWriteableBitmapFactory WUIXAMEIM_IWriteableBitmapFactory;
typedef struct WUIXAMEIM_IXamlRenderingBackgroundTaskFactory WUIXAMEIM_IXamlRenderingBackgroundTaskFactory;
typedef struct WUIXAMEIM_RenderTargetBitmap WUIXAMEIM_RenderTargetBitmap;
typedef struct WUIXAMEIM_SoftwareBitmapSource WUIXAMEIM_SoftwareBitmapSource;
typedef struct WUIXAMEIM_SurfaceImageSource WUIXAMEIM_SurfaceImageSource;
typedef struct WUIXAMEIM_IXamlRenderingBackgroundTask WUIXAMEIM_IXamlRenderingBackgroundTask;
typedef struct WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides;
typedef struct WUIXAMEIM_IVirtualSurfaceImageSource WUIXAMEIM_IVirtualSurfaceImageSource;
typedef struct WUIXAMEIM_IWriteableBitmap WUIXAMEIM_IWriteableBitmap;
typedef struct WUIXAMEIM_ISvgImageSourceFailedEventArgs WUIXAMEIM_ISvgImageSourceFailedEventArgs;
typedef struct WUIXAMEIM_IBitmapSource WUIXAMEIM_IBitmapSource;
typedef struct WUIXAMEIM_IBitmapImage WUIXAMEIM_IBitmapImage;
typedef struct WUIXAMEIM_IBitmapImage_2 WUIXAMEIM_IBitmapImage_2;
typedef struct WUIXAMEIM_IBitmapImage_3 WUIXAMEIM_IBitmapImage_3;
typedef struct WUIXAMEIM_IDownloadProgressEventArgs WUIXAMEIM_IDownloadProgressEventArgs;
typedef struct WUIXAMEIM_ISvgImageSource WUIXAMEIM_ISvgImageSource;
typedef struct WUIXAMEIM_ISvgImageSourceOpenedEventArgs WUIXAMEIM_ISvgImageSourceOpenedEventArgs;
typedef struct WUIXAMEIM_IRenderTargetBitmap WUIXAMEIM_IRenderTargetBitmap;
typedef struct WUIXAMEIM_ISoftwareBitmapSource WUIXAMEIM_ISoftwareBitmapSource;
typedef struct WUIXAMEIM_ISurfaceImageSource WUIXAMEIM_ISurfaceImageSource;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WAPBA_IBackgroundTaskInstance
#define CWINRT_FWD_WAPBA_IBackgroundTaskInstance
typedef struct WAPBA_IBackgroundTaskInstance WAPBA_IBackgroundTaskInstance;
#endif
#ifndef CWINRT_FWD_WSTST_IBuffer
#define CWINRT_FWD_WSTST_IBuffer
typedef struct WSTST_IBuffer WSTST_IBuffer;
#endif
#ifndef CWINRT_FWD_WSTST_IRandomAccessStream
#define CWINRT_FWD_WSTST_IRandomAccessStream
typedef struct WSTST_IRandomAccessStream WSTST_IRandomAccessStream;
#endif
#ifndef CWINRT_FWD_WF_IAsyncAction
#define CWINRT_FWD_WF_IAsyncAction
typedef struct WF_IAsyncAction WF_IAsyncAction;
#endif
#ifndef CWINRT_FWD_WUIXA_DependencyProperty
#define CWINRT_FWD_WUIXA_DependencyProperty
typedef struct WUIXA_DependencyProperty WUIXA_DependencyProperty;
#endif
#ifndef CWINRT_FWD_WF_Uri
#define CWINRT_FWD_WF_Uri
typedef struct WF_Uri WF_Uri;
#endif
#ifndef CWINRT_FWD_WUIXA_RoutedEventHandler
#define CWINRT_FWD_WUIXA_RoutedEventHandler
typedef struct WUIXA_RoutedEventHandler WUIXA_RoutedEventHandler;
#endif
#ifndef CWINRT_FWD_WUIXA_ExceptionRoutedEventHandler
#define CWINRT_FWD_WUIXA_ExceptionRoutedEventHandler
typedef struct WUIXA_ExceptionRoutedEventHandler WUIXA_ExceptionRoutedEventHandler;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceOpenedEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceOpenedEventArgs
typedef struct WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceOpenedEventArgs WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceOpenedEventArgs;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceFailedEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceFailedEventArgs
typedef struct WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceFailedEventArgs WF_TypedEventHandler_WUIXAMEIM_SvgImageSource_WUIXAMEIM_SvgImageSourceFailedEventArgs;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WUIXAMEIM_SvgImageSourceLoadStatus
#define CWINRT_FWD_WF_IAsyncOperation_WUIXAMEIM_SvgImageSourceLoadStatus
typedef struct WF_IAsyncOperation_WUIXAMEIM_SvgImageSourceLoadStatus WF_IAsyncOperation_WUIXAMEIM_SvgImageSourceLoadStatus;
#endif
#ifndef CWINRT_FWD_WUIXA_UIElement
#define CWINRT_FWD_WUIXA_UIElement
typedef struct WUIXA_UIElement WUIXA_UIElement;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WSTST_IBuffer
#define CWINRT_FWD_WF_IAsyncOperation_WSTST_IBuffer
typedef struct WF_IAsyncOperation_WSTST_IBuffer WF_IAsyncOperation_WSTST_IBuffer;
#endif
#ifndef CWINRT_FWD_WGRIM_SoftwareBitmap
#define CWINRT_FWD_WGRIM_SoftwareBitmap
typedef struct WGRIM_SoftwareBitmap WGRIM_SoftwareBitmap;
#endif

#ifndef CWINRT_FWD_WUIXAMEIM_SvgImageSourceLoadStatus
#define CWINRT_FWD_WUIXAMEIM_SvgImageSourceLoadStatus
typedef enum WUIXAMEIM_SvgImageSourceLoadStatus {
    WUIXAMEIM_SvgImageSourceLoadStatus_Success = 0,
    WUIXAMEIM_SvgImageSourceLoadStatus_NetworkError = 1,
    WUIXAMEIM_SvgImageSourceLoadStatus_InvalidFormat = 2,
    WUIXAMEIM_SvgImageSourceLoadStatus_Other = 3
} WUIXAMEIM_SvgImageSourceLoadStatus;
#endif

#ifndef CWINRT_FWD_WUIXAMEIM_BitmapCreateOptions
#define CWINRT_FWD_WUIXAMEIM_BitmapCreateOptions
typedef enum WUIXAMEIM_BitmapCreateOptions {
    WUIXAMEIM_BitmapCreateOptions_None = 0,
    WUIXAMEIM_BitmapCreateOptions_IgnoreImageCache = 8
} WUIXAMEIM_BitmapCreateOptions;
#endif

#ifndef CWINRT_FWD_WUIXAMEIM_DecodePixelType
#define CWINRT_FWD_WUIXAMEIM_DecodePixelType
typedef enum WUIXAMEIM_DecodePixelType {
    WUIXAMEIM_DecodePixelType_Physical = 0,
    WUIXAMEIM_DecodePixelType_Logical = 1
} WUIXAMEIM_DecodePixelType;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_DownloadProgressEventHandler
#define CWINRT_IIDDEF_WUIXAMEIM_DownloadProgressEventHandler
static const IID CWINRT_IID_WUIXAMEIM_DownloadProgressEventHandler CWINRT_MAYBE_UNUSED = { 0x1ABAEE23, 0x74EE, 0x4CC7, { 0x99, 0xBA, 0xB1, 0x71, 0xE3, 0xCD, 0xA6, 0x1E } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageFactory
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageFactory
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImageFactory CWINRT_MAYBE_UNUSED = { 0xC9132978, 0x4810, 0x4E5E, { 0x80, 0x87, 0x03, 0x67, 0x1E, 0xE6, 0x0D, 0x85 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImageStatics CWINRT_MAYBE_UNUSED = { 0x9E282143, 0x70E8, 0x437C, { 0x9F, 0xA4, 0x2C, 0xBF, 0x29, 0x5C, 0xFF, 0x84 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics_2
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics_2
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImageStatics_2 CWINRT_MAYBE_UNUSED = { 0xC5F5576A, 0x75AF, 0x41A4, { 0xB8, 0x93, 0x8F, 0xE9, 0x1F, 0xEE, 0x28, 0x82 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics_3
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImageStatics_3
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImageStatics_3 CWINRT_MAYBE_UNUSED = { 0x2B44E30D, 0xF6D5, 0x4411, { 0xA8, 0xCD, 0xBF, 0x76, 0x03, 0xC4, 0xFA, 0xA0 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapSourceFactory
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapSourceFactory
static const IID CWINRT_IID_WUIXAMEIM_IBitmapSourceFactory CWINRT_MAYBE_UNUSED = { 0xE240420E, 0xD4A7, 0x49A4, { 0xA0, 0xB4, 0xA5, 0x9F, 0xDD, 0x77, 0xE5, 0x08 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapSourceStatics
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapSourceStatics
static const IID CWINRT_IID_WUIXAMEIM_IBitmapSourceStatics CWINRT_MAYBE_UNUSED = { 0x9A9C9981, 0x827B, 0x4E51, { 0x89, 0x1B, 0x8A, 0x15, 0xB5, 0x11, 0x84, 0x2D } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IRenderTargetBitmapStatics
#define CWINRT_IIDDEF_WUIXAMEIM_IRenderTargetBitmapStatics
static const IID CWINRT_IID_WUIXAMEIM_IRenderTargetBitmapStatics CWINRT_MAYBE_UNUSED = { 0xF0A1EFEE, 0xC131, 0x4D40, { 0x9C, 0x47, 0xF7, 0xD7, 0xCF, 0x2B, 0x07, 0x7F } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISurfaceImageSourceFactory
#define CWINRT_IIDDEF_WUIXAMEIM_ISurfaceImageSourceFactory
static const IID CWINRT_IID_WUIXAMEIM_ISurfaceImageSourceFactory CWINRT_MAYBE_UNUSED = { 0x3AB2212A, 0xEF65, 0x4A5F, { 0xBF, 0xAC, 0x73, 0x99, 0x3E, 0x8C, 0x12, 0xC9 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceFactory
#define CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceFactory
static const IID CWINRT_IID_WUIXAMEIM_ISvgImageSourceFactory CWINRT_MAYBE_UNUSED = { 0xC794E9E7, 0xCF23, 0x4D72, { 0xBF, 0x1A, 0xDF, 0xAA, 0x16, 0xD8, 0xEA, 0x52 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceStatics
#define CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceStatics
static const IID CWINRT_IID_WUIXAMEIM_ISvgImageSourceStatics CWINRT_MAYBE_UNUSED = { 0x9C6638CE, 0xBED1, 0x4AAB, { 0xAC, 0xBB, 0xD3, 0xE2, 0x18, 0x5D, 0x31, 0x5A } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IVirtualSurfaceImageSourceFactory
#define CWINRT_IIDDEF_WUIXAMEIM_IVirtualSurfaceImageSourceFactory
static const IID CWINRT_IID_WUIXAMEIM_IVirtualSurfaceImageSourceFactory CWINRT_MAYBE_UNUSED = { 0x3AB2212A, 0xBFAC, 0x11E0, { 0x8A, 0x92, 0x69, 0xE4, 0x47, 0x24, 0x01, 0x9B } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IWriteableBitmapFactory
#define CWINRT_IIDDEF_WUIXAMEIM_IWriteableBitmapFactory
static const IID CWINRT_IID_WUIXAMEIM_IWriteableBitmapFactory CWINRT_MAYBE_UNUSED = { 0x5563EBB1, 0x3EF2, 0x42C5, { 0x9C, 0x6D, 0x1C, 0xF5, 0xDC, 0xC0, 0x41, 0xFF } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTaskFactory
#define CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTaskFactory
static const IID CWINRT_IID_WUIXAMEIM_IXamlRenderingBackgroundTaskFactory CWINRT_MAYBE_UNUSED = { 0xA3D1BB63, 0x38F8, 0x4DA3, { 0x9F, 0xCA, 0xFD, 0x81, 0x28, 0xA2, 0xCB, 0xF9 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTask
#define CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTask
static const IID CWINRT_IID_WUIXAMEIM_IXamlRenderingBackgroundTask CWINRT_MAYBE_UNUSED = { 0x5D5FE9AA, 0x533E, 0x44B8, { 0xA9, 0x75, 0xFC, 0x5F, 0x1E, 0x3B, 0xFF, 0x52 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides
#define CWINRT_IIDDEF_WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides
static const IID CWINRT_IID_WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides CWINRT_MAYBE_UNUSED = { 0x9C2A6997, 0xA908, 0x4711, { 0xB4, 0xB2, 0xA9, 0x60, 0xDB, 0x3D, 0x8E, 0x5A } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IVirtualSurfaceImageSource
#define CWINRT_IIDDEF_WUIXAMEIM_IVirtualSurfaceImageSource
static const IID CWINRT_IID_WUIXAMEIM_IVirtualSurfaceImageSource CWINRT_MAYBE_UNUSED = { 0x4A711FEA, 0xBFAC, 0x11E0, { 0xA0, 0x6A, 0x9D, 0xE4, 0x47, 0x24, 0x01, 0x9B } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IWriteableBitmap
#define CWINRT_IIDDEF_WUIXAMEIM_IWriteableBitmap
static const IID CWINRT_IID_WUIXAMEIM_IWriteableBitmap CWINRT_MAYBE_UNUSED = { 0xBF0B7E6F, 0xDF7C, 0x4A85, { 0x84, 0x13, 0xA1, 0x21, 0x62, 0x85, 0x83, 0x5C } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceFailedEventArgs
#define CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceFailedEventArgs
static const IID CWINRT_IID_WUIXAMEIM_ISvgImageSourceFailedEventArgs CWINRT_MAYBE_UNUSED = { 0x68BB3170, 0x3CCC, 0x4035, { 0xAC, 0x01, 0x98, 0x34, 0x54, 0x3D, 0x74, 0x4E } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapSource
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapSource
static const IID CWINRT_IID_WUIXAMEIM_IBitmapSource CWINRT_MAYBE_UNUSED = { 0x23D86411, 0x202F, 0x41B2, { 0x8C, 0x5B, 0xA8, 0xA3, 0xB3, 0x33, 0x80, 0x0B } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImage CWINRT_MAYBE_UNUSED = { 0x31AF3271, 0xE3B4, 0x442D, { 0xA3, 0x41, 0x4C, 0x02, 0x26, 0xB2, 0x72, 0x5B } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage_2
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage_2
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImage_2 CWINRT_MAYBE_UNUSED = { 0x1069C1B6, 0x8C9B, 0x4762, { 0xBE, 0x3D, 0x75, 0x9F, 0x56, 0x98, 0xF2, 0xB3 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage_3
#define CWINRT_IIDDEF_WUIXAMEIM_IBitmapImage_3
static const IID CWINRT_IID_WUIXAMEIM_IBitmapImage_3 CWINRT_MAYBE_UNUSED = { 0xF1DE6F26, 0x3C73, 0x453F, { 0xA7, 0xBA, 0x9B, 0x85, 0xC1, 0x8B, 0x37, 0x33 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IDownloadProgressEventArgs
#define CWINRT_IIDDEF_WUIXAMEIM_IDownloadProgressEventArgs
static const IID CWINRT_IID_WUIXAMEIM_IDownloadProgressEventArgs CWINRT_MAYBE_UNUSED = { 0x7311E0D4, 0xFE94, 0x4E70, { 0x9B, 0x90, 0xCD, 0xD4, 0x7A, 0xC2, 0x3A, 0xFB } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSource
#define CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSource
static const IID CWINRT_IID_WUIXAMEIM_ISvgImageSource CWINRT_MAYBE_UNUSED = { 0x03E1CEC3, 0x0CA8, 0x4A4E, { 0x8D, 0x7C, 0xC8, 0x08, 0xA0, 0x83, 0x85, 0x86 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceOpenedEventArgs
#define CWINRT_IIDDEF_WUIXAMEIM_ISvgImageSourceOpenedEventArgs
static const IID CWINRT_IID_WUIXAMEIM_ISvgImageSourceOpenedEventArgs CWINRT_MAYBE_UNUSED = { 0x85EF4C16, 0x748E, 0x4008, { 0x95, 0xC7, 0x6A, 0x23, 0xDD, 0x73, 0x16, 0xDB } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_IRenderTargetBitmap
#define CWINRT_IIDDEF_WUIXAMEIM_IRenderTargetBitmap
static const IID CWINRT_IID_WUIXAMEIM_IRenderTargetBitmap CWINRT_MAYBE_UNUSED = { 0x500DEE81, 0x893C, 0x4C0A, { 0x8F, 0xEC, 0x46, 0x78, 0xAC, 0x71, 0x75, 0x89 } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISoftwareBitmapSource
#define CWINRT_IIDDEF_WUIXAMEIM_ISoftwareBitmapSource
static const IID CWINRT_IID_WUIXAMEIM_ISoftwareBitmapSource CWINRT_MAYBE_UNUSED = { 0xD2DD9ED0, 0xD3C5, 0x4056, { 0x91, 0xB5, 0xB7, 0xC1, 0xD1, 0xE8, 0x13, 0x0E } };
#endif
#ifndef CWINRT_IIDDEF_WUIXAMEIM_ISurfaceImageSource
#define CWINRT_IIDDEF_WUIXAMEIM_ISurfaceImageSource
static const IID CWINRT_IID_WUIXAMEIM_ISurfaceImageSource CWINRT_MAYBE_UNUSED = { 0x62F7D416, 0xC714, 0x4C4C, { 0x82, 0x73, 0xF8, 0x39, 0xBC, 0x58, 0x13, 0x5C } };
#endif

/* Methods */

/* Windows.UI.Xaml.Media.Imaging.XamlRenderingBackgroundTask */
/* Windows.UI.Xaml.Media.Imaging.XamlRenderingBackgroundTask.OnRun(taskInstance) */
HRESULT wuixameim_xaml_rendering_background_task_handle_run(WUIXAMEIM_XamlRenderingBackgroundTask *self, WAPBA_IBackgroundTaskInstance* taskInstance);

/* activate Windows.UI.Xaml.Media.Imaging.WriteableBitmap */
HRESULT wuixameim_writeable_bitmap_new(WUIXAMEIM_WriteableBitmap **out);

/* Windows.UI.Xaml.Media.Imaging.WriteableBitmap */
/* Windows.UI.Xaml.Media.Imaging.WriteableBitmap.get_PixelBuffer() */
HRESULT wuixameim_writeable_bitmap_get__pixel_buffer(WUIXAMEIM_WriteableBitmap *self, WSTST_IBuffer** value);

/* Windows.UI.Xaml.Media.Imaging.WriteableBitmap.Invalidate() */
HRESULT wuixameim_writeable_bitmap_invalidate(WUIXAMEIM_WriteableBitmap *self);

/* activate Windows.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs */
HRESULT wuixameim_svg_image_source_failed_event_args_new(WUIXAMEIM_SvgImageSourceFailedEventArgs **out);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs */
/* Windows.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs.get_Status() */
HRESULT wuixameim_svg_image_source_failed_event_args_get__status(WUIXAMEIM_SvgImageSourceFailedEventArgs *self, WUIXAMEIM_SvgImageSourceLoadStatus *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource */
/* Windows.UI.Xaml.Media.Imaging.BitmapSource.get_PixelWidth() */
HRESULT wuixameim_bitmap_source_get__pixel_width(WUIXAMEIM_BitmapSource *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource.get_PixelHeight() */
HRESULT wuixameim_bitmap_source_get__pixel_height(WUIXAMEIM_BitmapSource *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource.SetSource(streamSource) */
HRESULT wuixameim_bitmap_source_set_source(WUIXAMEIM_BitmapSource *self, WSTST_IRandomAccessStream* streamSource);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource.SetSourceAsync(streamSource) */
HRESULT wuixameim_bitmap_source_set_source_async(WUIXAMEIM_BitmapSource *self, WSTST_IRandomAccessStream* streamSource, WF_IAsyncAction** out);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource.get_PixelWidthProperty() */
HRESULT wuixameim_bitmap_source_get__pixel_width_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapSource.get_PixelHeightProperty() */
HRESULT wuixameim_bitmap_source_get__pixel_height_property(WUIXA_DependencyProperty** value);

/* activate Windows.UI.Xaml.Media.Imaging.BitmapImage */
HRESULT wuixameim_bitmap_image_new(WUIXAMEIM_BitmapImage **out);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage */
/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_CreateOptions() */
HRESULT wuixameim_bitmap_image_get__create_options(WUIXAMEIM_BitmapImage *self, WUIXAMEIM_BitmapCreateOptions *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_CreateOptions() */
HRESULT wuixameim_bitmap_image_put__create_options(WUIXAMEIM_BitmapImage *self, WUIXAMEIM_BitmapCreateOptions value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_UriSource() */
HRESULT wuixameim_bitmap_image_get__uri_source(WUIXAMEIM_BitmapImage *self, WF_Uri** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_UriSource() */
HRESULT wuixameim_bitmap_image_put__uri_source(WUIXAMEIM_BitmapImage *self, WF_Uri* value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelWidth() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_width(WUIXAMEIM_BitmapImage *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_DecodePixelWidth() */
HRESULT wuixameim_bitmap_image_put__decode_pixel_width(WUIXAMEIM_BitmapImage *self, int32_t value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelHeight() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_height(WUIXAMEIM_BitmapImage *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_DecodePixelHeight() */
HRESULT wuixameim_bitmap_image_put__decode_pixel_height(WUIXAMEIM_BitmapImage *self, int32_t value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelType() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_type(WUIXAMEIM_BitmapImage *self, WUIXAMEIM_DecodePixelType *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_DecodePixelType() */
HRESULT wuixameim_bitmap_image_put__decode_pixel_type(WUIXAMEIM_BitmapImage *self, WUIXAMEIM_DecodePixelType value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_IsAnimatedBitmap() */
HRESULT wuixameim_bitmap_image_get__is_animated_bitmap(WUIXAMEIM_BitmapImage *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_IsPlaying() */
HRESULT wuixameim_bitmap_image_get__is_playing(WUIXAMEIM_BitmapImage *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_AutoPlay() */
HRESULT wuixameim_bitmap_image_get__auto_play(WUIXAMEIM_BitmapImage *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.put_AutoPlay() */
HRESULT wuixameim_bitmap_image_put__auto_play(WUIXAMEIM_BitmapImage *self, BOOL value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.Play() */
HRESULT wuixameim_bitmap_image_play(WUIXAMEIM_BitmapImage *self);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.Stop() */
HRESULT wuixameim_bitmap_image_stop(WUIXAMEIM_BitmapImage *self);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_IsAnimatedBitmapProperty() */
HRESULT wuixameim_bitmap_image_get__is_animated_bitmap_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_IsPlayingProperty() */
HRESULT wuixameim_bitmap_image_get__is_playing_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_AutoPlayProperty() */
HRESULT wuixameim_bitmap_image_get__auto_play_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelTypeProperty() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_type_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_CreateOptionsProperty() */
HRESULT wuixameim_bitmap_image_get__create_options_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_UriSourceProperty() */
HRESULT wuixameim_bitmap_image_get__uri_source_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelWidthProperty() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_width_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.BitmapImage.get_DecodePixelHeightProperty() */
HRESULT wuixameim_bitmap_image_get__decode_pixel_height_property(WUIXA_DependencyProperty** value);

/* Event subscriptions (on_/off_) */
#include <cwinrt/event.h>

cwinrt_token wuixameim_bitmap_image_on_download_progress(WUIXAMEIM_BitmapImage *self, cwinrt_event_fn fn, void *ctx);
void wuixameim_bitmap_image_off_download_progress(WUIXAMEIM_BitmapImage *self, cwinrt_token token);

cwinrt_token wuixameim_bitmap_image_on_image_opened(WUIXAMEIM_BitmapImage *self, cwinrt_event_fn fn, void *ctx);
void wuixameim_bitmap_image_off_image_opened(WUIXAMEIM_BitmapImage *self, cwinrt_token token);

cwinrt_token wuixameim_bitmap_image_on_image_failed(WUIXAMEIM_BitmapImage *self, cwinrt_event_fn fn, void *ctx);
void wuixameim_bitmap_image_off_image_failed(WUIXAMEIM_BitmapImage *self, cwinrt_token token);

/* activate Windows.UI.Xaml.Media.Imaging.DownloadProgressEventArgs */
HRESULT wuixameim_download_progress_event_args_new(WUIXAMEIM_DownloadProgressEventArgs **out);

/* Windows.UI.Xaml.Media.Imaging.DownloadProgressEventArgs */
/* Windows.UI.Xaml.Media.Imaging.DownloadProgressEventArgs.get_Progress() */
HRESULT wuixameim_download_progress_event_args_get__progress(WUIXAMEIM_DownloadProgressEventArgs *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.DownloadProgressEventArgs.put_Progress() */
HRESULT wuixameim_download_progress_event_args_put__progress(WUIXAMEIM_DownloadProgressEventArgs *self, int32_t value);

/* Windows.UI.Xaml.Media.Imaging.DownloadProgressEventHandler */
/* Windows.UI.Xaml.Media.Imaging.DownloadProgressEventHandler.Invoke(sender, e) */
HRESULT wuixameim_download_progress_event_handler_invoke(WUIXAMEIM_DownloadProgressEventHandler *self, IInspectable* sender, WUIXAMEIM_DownloadProgressEventArgs* e);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageFactory */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImageFactory.CreateInstanceWithUriSource(uriSource) */
HRESULT wuixameim_bitmap_image_factory_create_instance_with_uri_source(WUIXAMEIM_IBitmapImageFactory *self, WF_Uri* uriSource, WUIXAMEIM_BitmapImage** out);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics.get_CreateOptionsProperty() */
HRESULT wuixameim_bitmap_image_statics_get__create_options_property(WUIXAMEIM_IBitmapImageStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics.get_UriSourceProperty() */
HRESULT wuixameim_bitmap_image_statics_get__uri_source_property(WUIXAMEIM_IBitmapImageStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics.get_DecodePixelWidthProperty() */
HRESULT wuixameim_bitmap_image_statics_get__decode_pixel_width_property(WUIXAMEIM_IBitmapImageStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics.get_DecodePixelHeightProperty() */
HRESULT wuixameim_bitmap_image_statics_get__decode_pixel_height_property(WUIXAMEIM_IBitmapImageStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics2 */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics2.get_DecodePixelTypeProperty() */
HRESULT wuixameim_bitmap_image_statics_2_get__decode_pixel_type_property(WUIXAMEIM_IBitmapImageStatics_2 *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics3 */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics3.get_IsAnimatedBitmapProperty() */
HRESULT wuixameim_bitmap_image_statics_3_get__is_animated_bitmap_property(WUIXAMEIM_IBitmapImageStatics_3 *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics3.get_IsPlayingProperty() */
HRESULT wuixameim_bitmap_image_statics_3_get__is_playing_property(WUIXAMEIM_IBitmapImageStatics_3 *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImageStatics3.get_AutoPlayProperty() */
HRESULT wuixameim_bitmap_image_statics_3_get__auto_play_property(WUIXAMEIM_IBitmapImageStatics_3 *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapSourceFactory */
/* Windows.UI.Xaml.Media.Imaging.IBitmapSourceFactory.CreateInstance(baseInterface, innerInterface) */
HRESULT wuixameim_bitmap_source_factory_create_instance(WUIXAMEIM_IBitmapSourceFactory *self, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_BitmapSource** out);

/* Windows.UI.Xaml.Media.Imaging.IBitmapSourceStatics */
/* Windows.UI.Xaml.Media.Imaging.IBitmapSourceStatics.get_PixelWidthProperty() */
HRESULT wuixameim_bitmap_source_statics_get__pixel_width_property(WUIXAMEIM_IBitmapSourceStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapSourceStatics.get_PixelHeightProperty() */
HRESULT wuixameim_bitmap_source_statics_get__pixel_height_property(WUIXAMEIM_IBitmapSourceStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IRenderTargetBitmapStatics */
/* Windows.UI.Xaml.Media.Imaging.IRenderTargetBitmapStatics.get_PixelWidthProperty() */
HRESULT wuixameim_render_target_bitmap_statics_get__pixel_width_property(WUIXAMEIM_IRenderTargetBitmapStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IRenderTargetBitmapStatics.get_PixelHeightProperty() */
HRESULT wuixameim_render_target_bitmap_statics_get__pixel_height_property(WUIXAMEIM_IRenderTargetBitmapStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.ISurfaceImageSourceFactory */
/* Windows.UI.Xaml.Media.Imaging.ISurfaceImageSourceFactory.CreateInstanceWithDimensions(pixelWidth, pixelHeight, baseInterface, innerInterface) */
HRESULT wuixameim_surface_image_source_factory_create_instance_with_dimensions(WUIXAMEIM_ISurfaceImageSourceFactory *self, int32_t pixelWidth, int32_t pixelHeight, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_SurfaceImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.ISurfaceImageSourceFactory.CreateInstanceWithDimensionsAndOpacity(pixelWidth, pixelHeight, isOpaque, baseInterface, innerInterface) */
HRESULT wuixameim_surface_image_source_factory_create_instance_with_dimensions_and_opacity(WUIXAMEIM_ISurfaceImageSourceFactory *self, int32_t pixelWidth, int32_t pixelHeight, BOOL isOpaque, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_SurfaceImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource */
/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_UriSource() */
HRESULT wuixameim_svg_image_source_get__uri_source(WUIXAMEIM_SvgImageSource *self, WF_Uri** value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.put_UriSource() */
HRESULT wuixameim_svg_image_source_put__uri_source(WUIXAMEIM_SvgImageSource *self, WF_Uri* value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_RasterizePixelWidth() */
HRESULT wuixameim_svg_image_source_get__rasterize_pixel_width(WUIXAMEIM_SvgImageSource *self, double *value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.put_RasterizePixelWidth() */
HRESULT wuixameim_svg_image_source_put__rasterize_pixel_width(WUIXAMEIM_SvgImageSource *self, double value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_RasterizePixelHeight() */
HRESULT wuixameim_svg_image_source_get__rasterize_pixel_height(WUIXAMEIM_SvgImageSource *self, double *value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.put_RasterizePixelHeight() */
HRESULT wuixameim_svg_image_source_put__rasterize_pixel_height(WUIXAMEIM_SvgImageSource *self, double value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.SetSourceAsync(streamSource) */
HRESULT wuixameim_svg_image_source_set_source_async(WUIXAMEIM_SvgImageSource *self, WSTST_IRandomAccessStream* streamSource, WF_IAsyncOperation_WUIXAMEIM_SvgImageSourceLoadStatus** out);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_UriSourceProperty() */
HRESULT wuixameim_svg_image_source_get__uri_source_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_RasterizePixelWidthProperty() */
HRESULT wuixameim_svg_image_source_get__rasterize_pixel_width_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.SvgImageSource.get_RasterizePixelHeightProperty() */
HRESULT wuixameim_svg_image_source_get__rasterize_pixel_height_property(WUIXA_DependencyProperty** value);

/* Event subscriptions (on_/off_) */
#include <cwinrt/event.h>

cwinrt_token wuixameim_svg_image_source_on_opened(WUIXAMEIM_SvgImageSource *self, cwinrt_event_fn fn, void *ctx);
void wuixameim_svg_image_source_off_opened(WUIXAMEIM_SvgImageSource *self, cwinrt_token token);

cwinrt_token wuixameim_svg_image_source_on_open_failed(WUIXAMEIM_SvgImageSource *self, cwinrt_event_fn fn, void *ctx);
void wuixameim_svg_image_source_off_open_failed(WUIXAMEIM_SvgImageSource *self, cwinrt_token token);

/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceFactory */
/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceFactory.CreateInstance(baseInterface, innerInterface) */
HRESULT wuixameim_svg_image_source_factory_create_instance(WUIXAMEIM_ISvgImageSourceFactory *self, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_SvgImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceFactory.CreateInstanceWithUriSource(uriSource, baseInterface, innerInterface) */
HRESULT wuixameim_svg_image_source_factory_create_instance_with_uri_source(WUIXAMEIM_ISvgImageSourceFactory *self, WF_Uri* uriSource, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_SvgImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceStatics */
/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceStatics.get_UriSourceProperty() */
HRESULT wuixameim_svg_image_source_statics_get__uri_source_property(WUIXAMEIM_ISvgImageSourceStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceStatics.get_RasterizePixelWidthProperty() */
HRESULT wuixameim_svg_image_source_statics_get__rasterize_pixel_width_property(WUIXAMEIM_ISvgImageSourceStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceStatics.get_RasterizePixelHeightProperty() */
HRESULT wuixameim_svg_image_source_statics_get__rasterize_pixel_height_property(WUIXAMEIM_ISvgImageSourceStatics *self, WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.IVirtualSurfaceImageSourceFactory */
/* Windows.UI.Xaml.Media.Imaging.IVirtualSurfaceImageSourceFactory.CreateInstanceWithDimensions(pixelWidth, pixelHeight) */
HRESULT wuixameim_virtual_surface_image_source_factory_create_instance_with_dimensions(WUIXAMEIM_IVirtualSurfaceImageSourceFactory *self, int32_t pixelWidth, int32_t pixelHeight, WUIXAMEIM_VirtualSurfaceImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.IVirtualSurfaceImageSourceFactory.CreateInstanceWithDimensionsAndOpacity(pixelWidth, pixelHeight, isOpaque) */
HRESULT wuixameim_virtual_surface_image_source_factory_create_instance_with_dimensions_and_opacity(WUIXAMEIM_IVirtualSurfaceImageSourceFactory *self, int32_t pixelWidth, int32_t pixelHeight, BOOL isOpaque, WUIXAMEIM_VirtualSurfaceImageSource** out);

/* Windows.UI.Xaml.Media.Imaging.IWriteableBitmapFactory */
/* Windows.UI.Xaml.Media.Imaging.IWriteableBitmapFactory.CreateInstanceWithDimensions(pixelWidth, pixelHeight) */
HRESULT wuixameim_writeable_bitmap_factory_create_instance_with_dimensions(WUIXAMEIM_IWriteableBitmapFactory *self, int32_t pixelWidth, int32_t pixelHeight, WUIXAMEIM_WriteableBitmap** out);

/* Windows.UI.Xaml.Media.Imaging.IXamlRenderingBackgroundTaskFactory */
/* Windows.UI.Xaml.Media.Imaging.IXamlRenderingBackgroundTaskFactory.CreateInstance(baseInterface, innerInterface) */
HRESULT wuixameim_xaml_rendering_background_task_factory_create_instance(WUIXAMEIM_IXamlRenderingBackgroundTaskFactory *self, IInspectable* baseInterface, IInspectable* innerInterface, WUIXAMEIM_XamlRenderingBackgroundTask** out);

/* activate Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap */
HRESULT wuixameim_render_target_bitmap_new(WUIXAMEIM_RenderTargetBitmap **out);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap */
/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.get_PixelWidth() */
HRESULT wuixameim_render_target_bitmap_get__pixel_width(WUIXAMEIM_RenderTargetBitmap *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.get_PixelHeight() */
HRESULT wuixameim_render_target_bitmap_get__pixel_height(WUIXAMEIM_RenderTargetBitmap *self, int32_t *value);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.RenderAsync(element) */
HRESULT wuixameim_render_target_bitmap_render_async(WUIXAMEIM_RenderTargetBitmap *self, WUIXA_UIElement* element, WF_IAsyncAction** out);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.RenderAsync(element, scaledWidth, scaledHeight) */
HRESULT wuixameim_render_target_bitmap_render_async_p_i32_i32_p(WUIXAMEIM_RenderTargetBitmap *self, WUIXA_UIElement* element, int32_t scaledWidth, int32_t scaledHeight, WF_IAsyncAction** out);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.GetPixelsAsync() */
HRESULT wuixameim_render_target_bitmap_get_pixels_async(WUIXAMEIM_RenderTargetBitmap *self, WF_IAsyncOperation_WSTST_IBuffer** out);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.get_PixelWidthProperty() */
HRESULT wuixameim_render_target_bitmap_get__pixel_width_property(WUIXA_DependencyProperty** value);

/* Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.get_PixelHeightProperty() */
HRESULT wuixameim_render_target_bitmap_get__pixel_height_property(WUIXA_DependencyProperty** value);

/* activate Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource */
HRESULT wuixameim_software_bitmap_source_new(WUIXAMEIM_SoftwareBitmapSource **out);

/* Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource */
/* Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource.SetBitmapAsync(softwareBitmap) */
HRESULT wuixameim_software_bitmap_source_set_bitmap_async(WUIXAMEIM_SoftwareBitmapSource *self, WGRIM_SoftwareBitmap* softwareBitmap, WF_IAsyncAction** out);

/* Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource.Close() */
HRESULT wuixameim_software_bitmap_source_close(WUIXAMEIM_SoftwareBitmapSource *self);

/* Windows.UI.Xaml.Media.Imaging.IXamlRenderingBackgroundTaskOverrides */
/* Windows.UI.Xaml.Media.Imaging.IXamlRenderingBackgroundTaskOverrides.OnRun(taskInstance) */
HRESULT wuixameim_xaml_rendering_background_task_overrides_handle_run(WUIXAMEIM_IXamlRenderingBackgroundTaskOverrides *self, WAPBA_IBackgroundTaskInstance* taskInstance);

/* Windows.UI.Xaml.Media.Imaging.IWriteableBitmap */
/* Windows.UI.Xaml.Media.Imaging.ISvgImageSourceFailedEventArgs */
/* Windows.UI.Xaml.Media.Imaging.IBitmapSource */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImage */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImage2 */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImage2.get_DecodePixelType() */
HRESULT wuixameim_bitmap_image_2_get__decode_pixel_type(WUIXAMEIM_IBitmapImage_2 *self, WUIXAMEIM_DecodePixelType *value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage2.put_DecodePixelType() */
HRESULT wuixameim_bitmap_image_2_put__decode_pixel_type(WUIXAMEIM_IBitmapImage_2 *self, WUIXAMEIM_DecodePixelType value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3 */
/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.get_IsAnimatedBitmap() */
HRESULT wuixameim_bitmap_image_3_get__is_animated_bitmap(WUIXAMEIM_IBitmapImage_3 *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.get_IsPlaying() */
HRESULT wuixameim_bitmap_image_3_get__is_playing(WUIXAMEIM_IBitmapImage_3 *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.get_AutoPlay() */
HRESULT wuixameim_bitmap_image_3_get__auto_play(WUIXAMEIM_IBitmapImage_3 *self, BOOL *value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.put_AutoPlay() */
HRESULT wuixameim_bitmap_image_3_put__auto_play(WUIXAMEIM_IBitmapImage_3 *self, BOOL value);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.Play() */
HRESULT wuixameim_bitmap_image_3_play(WUIXAMEIM_IBitmapImage_3 *self);

/* Windows.UI.Xaml.Media.Imaging.IBitmapImage3.Stop() */
HRESULT wuixameim_bitmap_image_3_stop(WUIXAMEIM_IBitmapImage_3 *self);

/* Windows.UI.Xaml.Media.Imaging.IDownloadProgressEventArgs */
/* Windows.UI.Xaml.Media.Imaging.ISvgImageSource */
/* Windows.UI.Xaml.Media.Imaging.IRenderTargetBitmap */
/* Windows.UI.Xaml.Media.Imaging.ISoftwareBitmapSource */
#endif /* CWINRT_WINDOWS_UI_XAML_MEDIA_IMAGING_H */
