/* Generated by cwinrt-gen; do not edit. */

#ifndef CWINRT_WINDOWS_APPLICATIONMODEL_APPEXTENSIONS_H
#define CWINRT_WINDOWS_APPLICATIONMODEL_APPEXTENSIONS_H

#include <stdint.h>
#include <windows.h>
#include <cwinrt/hstring.h>
#include <unknwn.h>
#include <inspectable.h>
#include <cwinrt/Windows.Foundation.h>
#include <cwinrt/Windows.Foundation.Collections.h>
#include <cwinrt/Windows.ApplicationModel.h>
#include <cwinrt/cwinrt_piids.h>

/* External types (forward declarations) */
#ifndef CWINRT_FWD_WS_StorageFolder
#define CWINRT_FWD_WS_StorageFolder
typedef struct WS_StorageFolder WS_StorageFolder;
#endif

/* Types (forward declarations) */
typedef struct WAPAP_AppExtension WAPAP_AppExtension;
typedef struct WAPAP_AppExtensionCatalog WAPAP_AppExtensionCatalog;
typedef struct WAPAP_AppExtensionPackageInstalledEventArgs WAPAP_AppExtensionPackageInstalledEventArgs;
typedef struct WAPAP_AppExtensionPackageStatusChangedEventArgs WAPAP_AppExtensionPackageStatusChangedEventArgs;
typedef struct WAPAP_AppExtensionPackageUninstallingEventArgs WAPAP_AppExtensionPackageUninstallingEventArgs;
typedef struct WAPAP_AppExtensionPackageUpdatedEventArgs WAPAP_AppExtensionPackageUpdatedEventArgs;
typedef struct WAPAP_AppExtensionPackageUpdatingEventArgs WAPAP_AppExtensionPackageUpdatingEventArgs;
typedef struct WAPAP_IAppExtensionCatalogStatics WAPAP_IAppExtensionCatalogStatics;
typedef struct WAPAP_IAppExtension WAPAP_IAppExtension;
typedef struct WAPAP_IAppExtension_2 WAPAP_IAppExtension_2;
typedef struct WAPAP_IAppExtension_3 WAPAP_IAppExtension_3;
typedef struct WAPAP_IAppExtensionCatalog WAPAP_IAppExtensionCatalog;
typedef struct WAPAP_IAppExtensionCatalog_2 WAPAP_IAppExtensionCatalog_2;
typedef struct WAPAP_IAppExtensionPackageInstalledEventArgs WAPAP_IAppExtensionPackageInstalledEventArgs;
typedef struct WAPAP_IAppExtensionPackageStatusChangedEventArgs WAPAP_IAppExtensionPackageStatusChangedEventArgs;
typedef struct WAPAP_IAppExtensionPackageUninstallingEventArgs WAPAP_IAppExtensionPackageUninstallingEventArgs;
typedef struct WAPAP_IAppExtensionPackageUpdatedEventArgs WAPAP_IAppExtensionPackageUpdatedEventArgs;
typedef struct WAPAP_IAppExtensionPackageUpdatingEventArgs WAPAP_IAppExtensionPackageUpdatingEventArgs;

/* Signature-referenced types */
#ifndef CWINRT_FWD_WAM_Package
#define CWINRT_FWD_WAM_Package
typedef struct WAM_Package WAM_Package;
#endif
#ifndef CWINRT_FWD_WAM_AppInfo
#define CWINRT_FWD_WAM_AppInfo
typedef struct WAM_AppInfo WAM_AppInfo;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WFOCO_IPropertySet
#define CWINRT_FWD_WF_IAsyncOperation_WFOCO_IPropertySet
typedef struct WF_IAsyncOperation_WFOCO_IPropertySet WF_IAsyncOperation_WFOCO_IPropertySet;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WS_StorageFolder
#define CWINRT_FWD_WF_IAsyncOperation_WS_StorageFolder
typedef struct WF_IAsyncOperation_WS_StorageFolder WF_IAsyncOperation_WS_StorageFolder;
#endif
#ifndef CWINRT_FWD_WFOCO_IPropertySet
#define CWINRT_FWD_WFOCO_IPropertySet
typedef struct WFOCO_IPropertySet WFOCO_IPropertySet;
#endif
#ifndef CWINRT_FWD_WS_StorageFolder
#define CWINRT_FWD_WS_StorageFolder
typedef struct WS_StorageFolder WS_StorageFolder;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WAPAP_AppExtension
#define CWINRT_FWD_WF_IAsyncOperation_WFOCO_IVectorView_WAPAP_AppExtension
typedef struct WF_IAsyncOperation_WFOCO_IVectorView_WAPAP_AppExtension WF_IAsyncOperation_WFOCO_IVectorView_WAPAP_AppExtension;
#endif
#ifndef CWINRT_FWD_WF_IAsyncOperation_Bool
#define CWINRT_FWD_WF_IAsyncOperation_Bool
typedef struct WF_IAsyncOperation_Bool WF_IAsyncOperation_Bool;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageInstalledEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageInstalledEventArgs
typedef struct WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageInstalledEventArgs WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageInstalledEventArgs;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatingEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatingEventArgs
typedef struct WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatingEventArgs WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatingEventArgs;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatedEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatedEventArgs
typedef struct WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatedEventArgs WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUpdatedEventArgs;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUninstallingEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUninstallingEventArgs
typedef struct WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUninstallingEventArgs WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageUninstallingEventArgs;
#endif
#ifndef CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageStatusChangedEventArgs
#define CWINRT_FWD_WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageStatusChangedEventArgs
typedef struct WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageStatusChangedEventArgs WF_TypedEventHandler_WAPAP_AppExtensionCatalog_WAPAP_AppExtensionPackageStatusChangedEventArgs;
#endif
#ifndef CWINRT_FWD_WFOCO_IVectorView_WAPAP_AppExtension
#define CWINRT_FWD_WFOCO_IVectorView_WAPAP_AppExtension
typedef struct WFOCO_IVectorView_WAPAP_AppExtension WFOCO_IVectorView_WAPAP_AppExtension;
#endif

/* Interface IIDs */
#ifndef CWINRT_MAYBE_UNUSED
#  if defined(__GNUC__) || defined(__clang__)
#    define CWINRT_MAYBE_UNUSED __attribute__((unused))
#  else
#    define CWINRT_MAYBE_UNUSED
#  endif
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionCatalogStatics
#define CWINRT_IIDDEF_WAPAP_IAppExtensionCatalogStatics
static const IID CWINRT_IID_WAPAP_IAppExtensionCatalogStatics CWINRT_MAYBE_UNUSED = { 0x3C36668A, 0x5F18, 0x4F0B, { 0x9C, 0xE5, 0xCA, 0xB6, 0x1D, 0x19, 0x6F, 0x11 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtension
#define CWINRT_IIDDEF_WAPAP_IAppExtension
static const IID CWINRT_IID_WAPAP_IAppExtension CWINRT_MAYBE_UNUSED = { 0x8450902C, 0x15ED, 0x4FAF, { 0x93, 0xEA, 0x22, 0x37, 0xBB, 0xF8, 0xCB, 0xD6 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtension_2
#define CWINRT_IIDDEF_WAPAP_IAppExtension_2
static const IID CWINRT_IID_WAPAP_IAppExtension_2 CWINRT_MAYBE_UNUSED = { 0xAB3B15F0, 0x14F9, 0x4B9F, { 0x94, 0x19, 0xA3, 0x49, 0xA2, 0x42, 0xEF, 0x38 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtension_3
#define CWINRT_IIDDEF_WAPAP_IAppExtension_3
static const IID CWINRT_IID_WAPAP_IAppExtension_3 CWINRT_MAYBE_UNUSED = { 0x5923C101, 0xAA38, 0x4009, { 0x84, 0xD9, 0x5B, 0x54, 0xA0, 0xDF, 0x30, 0xAE } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionCatalog
#define CWINRT_IIDDEF_WAPAP_IAppExtensionCatalog
static const IID CWINRT_IID_WAPAP_IAppExtensionCatalog CWINRT_MAYBE_UNUSED = { 0x97872032, 0x8426, 0x4AD1, { 0x90, 0x84, 0x92, 0xE8, 0x8C, 0x2D, 0xA2, 0x00 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionCatalog_2
#define CWINRT_IIDDEF_WAPAP_IAppExtensionCatalog_2
static const IID CWINRT_IID_WAPAP_IAppExtensionCatalog_2 CWINRT_MAYBE_UNUSED = { 0x50056EBA, 0x58B6, 0x4147, { 0xB5, 0xA5, 0x8F, 0xEC, 0xA6, 0xDF, 0xB4, 0x9D } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionPackageInstalledEventArgs
#define CWINRT_IIDDEF_WAPAP_IAppExtensionPackageInstalledEventArgs
static const IID CWINRT_IID_WAPAP_IAppExtensionPackageInstalledEventArgs CWINRT_MAYBE_UNUSED = { 0x39E59234, 0x3351, 0x4A8D, { 0x97, 0x45, 0xE7, 0xD3, 0xDD, 0x45, 0xBC, 0x48 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionPackageStatusChangedEventArgs
#define CWINRT_IIDDEF_WAPAP_IAppExtensionPackageStatusChangedEventArgs
static const IID CWINRT_IID_WAPAP_IAppExtensionPackageStatusChangedEventArgs CWINRT_MAYBE_UNUSED = { 0x1CE17433, 0x1153, 0x44FD, { 0x87, 0xB1, 0x8A, 0xE1, 0x05, 0x03, 0x03, 0xDF } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUninstallingEventArgs
#define CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUninstallingEventArgs
static const IID CWINRT_IID_WAPAP_IAppExtensionPackageUninstallingEventArgs CWINRT_MAYBE_UNUSED = { 0x60F160C5, 0x171E, 0x40FF, { 0xAE, 0x98, 0xAB, 0x2C, 0x20, 0xDD, 0x4D, 0x75 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUpdatedEventArgs
#define CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUpdatedEventArgs
static const IID CWINRT_IID_WAPAP_IAppExtensionPackageUpdatedEventArgs CWINRT_MAYBE_UNUSED = { 0x3A83C43F, 0x797E, 0x44B5, { 0xBA, 0x24, 0xA4, 0xC8, 0xB5, 0xA5, 0x43, 0xD7 } };
#endif
#ifndef CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUpdatingEventArgs
#define CWINRT_IIDDEF_WAPAP_IAppExtensionPackageUpdatingEventArgs
static const IID CWINRT_IID_WAPAP_IAppExtensionPackageUpdatingEventArgs CWINRT_MAYBE_UNUSED = { 0x7ED59329, 0x1A65, 0x4800, { 0xA7, 0x00, 0xB3, 0x21, 0x00, 0x9E, 0x30, 0x6A } };
#endif

/* Methods */

/* activate Windows.ApplicationModel.AppExtensions.AppExtension */
HRESULT wapap_app_extension_new(WAPAP_AppExtension **out);

/* Windows.ApplicationModel.AppExtensions.AppExtension */
/* Windows.ApplicationModel.AppExtensions.AppExtension.get_Id() */
HRESULT wapap_app_extension_get__id(WAPAP_AppExtension *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.get_DisplayName() */
HRESULT wapap_app_extension_get__display_name(WAPAP_AppExtension *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.get_Description() */
HRESULT wapap_app_extension_get__description(WAPAP_AppExtension *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.get_Package() */
HRESULT wapap_app_extension_get__package(WAPAP_AppExtension *self, WAM_Package** value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.get_AppInfo() */
HRESULT wapap_app_extension_get__app_info(WAPAP_AppExtension *self, WAM_AppInfo** value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.GetExtensionPropertiesAsync() */
HRESULT wapap_app_extension_get_extension_properties_async(WAPAP_AppExtension *self, WF_IAsyncOperation_WFOCO_IPropertySet** out);

/* Windows.ApplicationModel.AppExtensions.AppExtension.GetPublicFolderAsync() */
HRESULT wapap_app_extension_get_public_folder_async(WAPAP_AppExtension *self, WF_IAsyncOperation_WS_StorageFolder** out);

/* Windows.ApplicationModel.AppExtensions.AppExtension.get_AppUserModelId() */
HRESULT wapap_app_extension_get__app_user_model_id(WAPAP_AppExtension *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtension.GetExtensionProperties() */
HRESULT wapap_app_extension_get_extension_properties(WAPAP_AppExtension *self, WFOCO_IPropertySet** out);

/* Windows.ApplicationModel.AppExtensions.AppExtension.GetPublicPath() */
HRESULT wapap_app_extension_get_public_path(WAPAP_AppExtension *self, cwinrt_hstring *out);

/* Windows.ApplicationModel.AppExtensions.AppExtension.GetPublicFolder() */
HRESULT wapap_app_extension_get_public_folder(WAPAP_AppExtension *self, WS_StorageFolder** out);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionCatalog */
HRESULT wapap_app_extension_catalog_new(WAPAP_AppExtensionCatalog **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionCatalog */
/* Windows.ApplicationModel.AppExtensions.AppExtensionCatalog.FindAllAsync() */
HRESULT wapap_app_extension_catalog_find_all_async(WAPAP_AppExtensionCatalog *self, WF_IAsyncOperation_WFOCO_IVectorView_WAPAP_AppExtension** out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionCatalog.RequestRemovePackageAsync(packageFullName) */
HRESULT wapap_app_extension_catalog_request_remove_package_async(WAPAP_AppExtensionCatalog *self, cwinrt_hstring packageFullName, WF_IAsyncOperation_Bool** out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionCatalog.FindAll() */
HRESULT wapap_app_extension_catalog_find_all(WAPAP_AppExtensionCatalog *self, WFOCO_IVectorView_WAPAP_AppExtension** out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionCatalog.Open(appExtensionName) */
HRESULT wapap_app_extension_catalog_open(cwinrt_hstring appExtensionName, WAPAP_AppExtensionCatalog** out);

/* Event subscriptions (on_/off_) */
#include <cwinrt/event.h>

cwinrt_token wapap_app_extension_catalog_on_package_installed(WAPAP_AppExtensionCatalog *self, cwinrt_event_fn fn, void *ctx);
void wapap_app_extension_catalog_off_package_installed(WAPAP_AppExtensionCatalog *self, cwinrt_token token);

cwinrt_token wapap_app_extension_catalog_on_package_updating(WAPAP_AppExtensionCatalog *self, cwinrt_event_fn fn, void *ctx);
void wapap_app_extension_catalog_off_package_updating(WAPAP_AppExtensionCatalog *self, cwinrt_token token);

cwinrt_token wapap_app_extension_catalog_on_package_updated(WAPAP_AppExtensionCatalog *self, cwinrt_event_fn fn, void *ctx);
void wapap_app_extension_catalog_off_package_updated(WAPAP_AppExtensionCatalog *self, cwinrt_token token);

cwinrt_token wapap_app_extension_catalog_on_package_uninstalling(WAPAP_AppExtensionCatalog *self, cwinrt_event_fn fn, void *ctx);
void wapap_app_extension_catalog_off_package_uninstalling(WAPAP_AppExtensionCatalog *self, cwinrt_token token);

cwinrt_token wapap_app_extension_catalog_on_package_status_changed(WAPAP_AppExtensionCatalog *self, cwinrt_event_fn fn, void *ctx);
void wapap_app_extension_catalog_off_package_status_changed(WAPAP_AppExtensionCatalog *self, cwinrt_token token);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionPackageInstalledEventArgs */
HRESULT wapap_app_extension_package_installed_event_args_new(WAPAP_AppExtensionPackageInstalledEventArgs **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageInstalledEventArgs */
/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageInstalledEventArgs.get_AppExtensionName() */
HRESULT wapap_app_extension_package_installed_event_args_get__app_extension_name(WAPAP_AppExtensionPackageInstalledEventArgs *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageInstalledEventArgs.get_Package() */
HRESULT wapap_app_extension_package_installed_event_args_get__package(WAPAP_AppExtensionPackageInstalledEventArgs *self, WAM_Package** value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageInstalledEventArgs.get_Extensions() */
HRESULT wapap_app_extension_package_installed_event_args_get__extensions(WAPAP_AppExtensionPackageInstalledEventArgs *self, WFOCO_IVectorView_WAPAP_AppExtension** value);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionPackageStatusChangedEventArgs */
HRESULT wapap_app_extension_package_status_changed_event_args_new(WAPAP_AppExtensionPackageStatusChangedEventArgs **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageStatusChangedEventArgs */
/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageStatusChangedEventArgs.get_AppExtensionName() */
HRESULT wapap_app_extension_package_status_changed_event_args_get__app_extension_name(WAPAP_AppExtensionPackageStatusChangedEventArgs *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageStatusChangedEventArgs.get_Package() */
HRESULT wapap_app_extension_package_status_changed_event_args_get__package(WAPAP_AppExtensionPackageStatusChangedEventArgs *self, WAM_Package** value);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionPackageUninstallingEventArgs */
HRESULT wapap_app_extension_package_uninstalling_event_args_new(WAPAP_AppExtensionPackageUninstallingEventArgs **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUninstallingEventArgs */
/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUninstallingEventArgs.get_AppExtensionName() */
HRESULT wapap_app_extension_package_uninstalling_event_args_get__app_extension_name(WAPAP_AppExtensionPackageUninstallingEventArgs *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUninstallingEventArgs.get_Package() */
HRESULT wapap_app_extension_package_uninstalling_event_args_get__package(WAPAP_AppExtensionPackageUninstallingEventArgs *self, WAM_Package** value);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatedEventArgs */
HRESULT wapap_app_extension_package_updated_event_args_new(WAPAP_AppExtensionPackageUpdatedEventArgs **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatedEventArgs */
/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatedEventArgs.get_AppExtensionName() */
HRESULT wapap_app_extension_package_updated_event_args_get__app_extension_name(WAPAP_AppExtensionPackageUpdatedEventArgs *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatedEventArgs.get_Package() */
HRESULT wapap_app_extension_package_updated_event_args_get__package(WAPAP_AppExtensionPackageUpdatedEventArgs *self, WAM_Package** value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatedEventArgs.get_Extensions() */
HRESULT wapap_app_extension_package_updated_event_args_get__extensions(WAPAP_AppExtensionPackageUpdatedEventArgs *self, WFOCO_IVectorView_WAPAP_AppExtension** value);

/* activate Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatingEventArgs */
HRESULT wapap_app_extension_package_updating_event_args_new(WAPAP_AppExtensionPackageUpdatingEventArgs **out);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatingEventArgs */
/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatingEventArgs.get_AppExtensionName() */
HRESULT wapap_app_extension_package_updating_event_args_get__app_extension_name(WAPAP_AppExtensionPackageUpdatingEventArgs *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.AppExtensionPackageUpdatingEventArgs.get_Package() */
HRESULT wapap_app_extension_package_updating_event_args_get__package(WAPAP_AppExtensionPackageUpdatingEventArgs *self, WAM_Package** value);

/* Windows.ApplicationModel.AppExtensions.IAppExtensionCatalogStatics */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionCatalogStatics.Open(appExtensionName) */
HRESULT wapap_app_extension_catalog_statics_open(WAPAP_IAppExtensionCatalogStatics *self, cwinrt_hstring appExtensionName, WAPAP_AppExtensionCatalog** out);

/* Windows.ApplicationModel.AppExtensions.IAppExtension */
/* Windows.ApplicationModel.AppExtensions.IAppExtension2 */
/* Windows.ApplicationModel.AppExtensions.IAppExtension2.get_AppUserModelId() */
HRESULT wapap_app_extension_2_get__app_user_model_id(WAPAP_IAppExtension_2 *self, cwinrt_hstring *value);

/* Windows.ApplicationModel.AppExtensions.IAppExtension3 */
/* Windows.ApplicationModel.AppExtensions.IAppExtension3.GetExtensionProperties() */
HRESULT wapap_app_extension_3_get_extension_properties(WAPAP_IAppExtension_3 *self, WFOCO_IPropertySet** out);

/* Windows.ApplicationModel.AppExtensions.IAppExtension3.GetPublicPath() */
HRESULT wapap_app_extension_3_get_public_path(WAPAP_IAppExtension_3 *self, cwinrt_hstring *out);

/* Windows.ApplicationModel.AppExtensions.IAppExtension3.GetPublicFolder() */
HRESULT wapap_app_extension_3_get_public_folder(WAPAP_IAppExtension_3 *self, WS_StorageFolder** out);

/* Windows.ApplicationModel.AppExtensions.IAppExtensionCatalog */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionCatalog2 */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionCatalog2.FindAll() */
HRESULT wapap_app_extension_catalog_2_find_all(WAPAP_IAppExtensionCatalog_2 *self, WFOCO_IVectorView_WAPAP_AppExtension** out);

/* Windows.ApplicationModel.AppExtensions.IAppExtensionPackageInstalledEventArgs */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionPackageStatusChangedEventArgs */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionPackageUninstallingEventArgs */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionPackageUpdatedEventArgs */
/* Windows.ApplicationModel.AppExtensions.IAppExtensionPackageUpdatingEventArgs */
#endif /* CWINRT_WINDOWS_APPLICATIONMODEL_APPEXTENSIONS_H */
